==== Erlöskonten für POS-Aufträge

Wenn im plentymarkets Backend Erlöskonten gepflegt werden, werden Aufträge, die über plentymarkets POS generiert werden, Erlöskonten basierend der folgenden Logik zugewiesen:

. Es wird geprüft, ob am Artikel der Variante ein Erlöskonto gespeichert ist. Wenn ein Erlöskonto am Artikel gespeichert ist, wird dieses Erlöskonto herangezogen. Erlöskonten werden im Menü
*Artikel » Artikel bearbeiten » Artikel öffnen » Tab: Global » Option: Erlöskonto* gespeichert.
. Ist kein Erlöskonto am Artikel gespeichert, wird das Erlöskonto anhand der Steuersätze des Standorts der Kasse ermittelt. Dieser Steuersatz wird im Menü *System » Mandant » Mandant öffnen » Standorte » Standort öffnen » Buchhaltung » Tab: Konten » Tab: Erlöskonten » Land öffnen* gespeichert.
. Sind für den Standort der Kasse keine Steuersätze gespeichert, wird das Erlöskonto anhand der Steuersätze des Standard-Standorts des Mandanten ermittelt. Dieser Steuersatz wird im Menü *System » Mandant » Mandant öffnen » Standorte » Standardstandort öffnen » Buchhaltung » Tab: Konten » Tab: Erlöskonten » Land öffnen* gespeichert.
. Sind auch am Standardstandort keine Erlöskonten gespeichert, wird dem Auftrag kein Erlöskonto zugewiesen.

==== Buchungskonten für weitere Kassenvorfälle

Da Einlagen, Entnahmen und Kassenstürze keine Aufträge sind, greift die oben beschriebene Logik für die Zuordnung eines Buchungskontos bei diesen Kassenvorfällen nicht. Ab plentymarkets App Version 1.7.x können daher systemseitig Buchungskonten gespeichert werden, die Einlagen, Entnahmen und Kassensturzdifferenzen zugewiesen werden. Die Buchungskonten für Kassenvorfälle werden im Menü *System » Mandant » Mandant wählen » Standorte » Standort wählen » Buchhaltung » Tab: Konten » Tab: Kassenvorfälle* gepflegt. Das Verwalten der Buchungskonten wird im Handbuch des ERP-Systems plentymarkets beschrieben: https://knowledge.plentymarkets.com/omni-channel/pos/pos-einrichten#xxx[https://knowledge.plentymarkets.com/omni-channel/pos/pos-einrichten#xxx]

Systemseitig werden Buchungskonten für Kassenvorfälle in der Tabelle *plenty_accounting_posting_accounts* und dort in folgenden Spalten gespeichert:

* *id* -> Die ID der Kombination aus Bezeichnung und Buchungskonto.
* *locationId* -> xxxxxxx.
* *type* -> xxxxxxx.
* *position* -> Die Position der Kombination aus Bezeichnung und Buchungskonto.
* *subtype* -> xxxxxxx.
* *name* -> Die Bezeichnung
* *account* -> Das Buchungskonto
* *deleted_at* -> Zeitpunkt (Datum/Uhrzeit), zu dem die Kombination aus Bezeichnung und Buchungskonto gelöscht wurde. Beim Löschen bleiben die gespeicherten Daten erhalten, die Kombination wird jedoch im ERP-System plentymarkets und in der plentymarkets App nicht mehr angezeigt. Sie kann also neuen Kassenvorfällen nicht mehr zugewiesen werden.
* *created_at* -> Zeitpunkt (Datum/Uhrzeit), zu dem die Kombination aus Bezeichnung und Buchungskonto erstellt wurde.
* *updated_at* -> Zeitpunkt (Datum/Uhrzeit), zu dem die Kombination aus Bezeichnung und Buchungskonto aktualisiert wurde.






==== Zuordnung von Buchungskonten im Unternehmen


Entnahmen 

* [_Name, Vorname, ggf. Personalnummer, Organisationseinheit, Funktion im Unternehmen_]

|===
|Bezeichnung|Buchungskonto|Einsatzzeitraum (von/bis)

3+|Entnahmen

|Entnahme
|
|

|Kassensturz
|
|

|[_Weitere Entnahmevorfälle einfügen_]
|
|

3+|Einlagen

|Einlage
|
|

|Kassensturz
|
|

|[_Weitere Einlagevorfälle einfügen_]
|
|
|===
