= Allgemeine fachliche Beschreibung der Software plentymarkets

plentymarkets ist eine modular aufgebaute und Plugin-fähige Software für den Handel mit Sachgütern, digitalen Gütern und immateriellen Gütern. plentymarkets ist ein Produkt der plentysystems AG und wird ausschließlich im SaaSA-Modell angeboten. Die Software verfügt über integrale und optionale Module. plentymarkets wird in verschiedenen Tarifen angeboten. Je nach Tarif unterscheiden sich die integralen und optionalen Module.

Folgende Module sind verfügbar: Artikel, Auftragsabwicklung, CRM (Kundenkontakt / Beziehungsmanagement), Payment (Zahlungsanbindungen / Zahlungszuordnung), Fulfillment (Versandanbindungen), Online-Shop, Multi-Channel (Online-Marktplatz- und Vergleichsportalanbindungen), Warenwirtschaft und POS (Kassensystem für stationären Handel).

plentymarkets dient insbesondere der Verwaltung und Abwicklung von Daten und Arbeitsabläufen, die im Zusammenhang mit dem Handel von Sachgütern, digitalen Gütern und immateriellen Gütern stehen. Hierbei kommen die genannten Module zum Einsatz. Die Vorteile beim Einsatz von plentymarkets liegen insbesondere darin, dass Artikelinformationen zentral in plentymarkets erfasst und verwaltet werden und von hier aus an verschiedene Kanäle für den Verkauf übermittelt werden. Des Weiteren liegen Vorteile darin, dass – unabhängig davon, über welchen Kanal ein Artikel verkauft wurde – nach dem Verkauf eine Übermittlung der Auftrags- und Kundendaten an das plentymarkets System des Anwenders erfolgt, sodass die anschließende Abwicklung wieder zentral im plentymarkets System des Anwenders erfolgt. Ein weiterer Vorteil liegt in der Möglichkeit, diese Abwicklung bis zu einem hohen Grad zu automatisieren.

Als Verkaufskanäle kommen Marktplätze oder Vergleichsportale aus dem Modul Multi-Channel, Kassen aus dem Modul POS, eigene Online-Shops sowie über Plugins angebundene Kanäle infrage. Der Anwender entscheidet, welche Verkaufskanäle genutzt werden, sodass sich die verwendeten Kanäle für jeden Anwender unterscheiden.

Der Grad der Automatisierung wird durch den Anwender selbst bestimmt und unterscheidet sich deshalb ebenfalls für jeden Anwender. Die Bearbeitung und Abwicklung eines Auftrags bis hin zum Versand kann also komplett manuell oder automatisiert erfolgen. Manuell bedeutet, dass jeder einzelne Vorgang explizit durch einen Benutzer angestoßen wird. Automatisiert bedeutet, dass plentymarkets anhand eigens durch den Anwender festgelegter Kriterien Aktionen ausführt, die zuvor ebenfalls durch den Anwender festgelegt und aktiviert wurden. Das System führt die Aktionen also bei Zutreffen der Kriterien lediglich aus.  +
Einige Aktionen erfolgen jedoch auch automatisch durch das System und können nicht durch den Anwender beeinflusst werden. Hierbei handelt es sich um sogenannte Systemautomatismen. Welche Systemautomatismen es gibt, wird später im Text erläutert.

Bei Bestellung eines plentymarkets Systems erhält der Anwender Login-Daten, mit denen er sich als Benutzer in sein System einloggen kann. Was Benutzer sind und was sie dürfen, wird zunächst beschrieben. Anschließend werden die Module einzeln genauer beschrieben.
