= Anhang: REST-Berechtigungen

Die folgenden Diagramme listen die verfügbaren REST-Berechtigungen für Benutzer mit dem Zugang *Nur API-Benutzer* auf. Die Berechtigungen können über das Menü *Einrichtung » Kontoverwaltung » Rollen » _Rolle öffnen_ » Erweiterter Modus* gewählt werden.

Die Berechtigungen sind in folgende Bereiche unterteilt:

[plantuml, format=png, opts="inline"]
----
!include styles/tree-style.iuml
legend
Berechtigungen
|_ Buchhaltung
|_ Authorisierung
|_ Automation
|_ Blog
|_ Zertifizierung
|_ Mandant
|_ CMS
|_ Kommentare
|_ CRM
|_ Daten
|_ Dokumente
|_ Artikel
|_ Listing
|_ Märkte
|_ Markierung
|_ Stammdaten
|_ plentyApp-Einstellungen
|_ Zahlenformat
|_ Aufträge
|_ plentyBI
|_ plentyWarehouse
|_ plentyBase-Einstellungen
|_ Plugins
|_ POS
|_ Prozesse (Veraltet)
|_ Service
|_ Service-Center
|_ Einrichtung
|_ Start
|_ Warenbestände
|_ plentymarkets Systeme
|_ Vorlage
|_ Benutzer
|_ Webhooks
end legend
----

<<<

== Buchhaltung

In diesem Abschnitt werden die Berechtigungen für den Bereich Buchhaltung aufgelistet.

[plantuml, format=png, opts="inline"]
----
!include styles/tree-style.iuml
legend
Buchhaltung
|_ Verrechnungskonto
  |_ Verechnete Buchungen
  |_ Buchungen
|_ Bearbeiten
|_ Standort
  |_ Debitorenkonten
  |_ Buchungsschlüssel
  |_ Erlöskonten
|_ Unternehmen
end legend
----

<<<

== Authorisierung

In diesem Abschnitt werden die Berechtigungen für den Bereich Authorisierung aufgelistet.

[plantuml, format=png, opts="inline"]
----
!include styles/tree-style.iuml
legend
Authorisierung
|_ Berechtigungen
  |_ Berechtigungen von Benutzern
    |_ Bearbeiten
|_ Rollen
  |_ Konfigurieren
  |_ Rollen eines Benutzers
    |_ Bearbeiten
end legend
----

<<<

== Automatisierung

In diesem Abschnitt werden die Berechtigungen für den Bereich Automatisierung aufgelistet.

[plantuml, format=png, opts="inline"]
----
!include styles/tree-style.iuml
legend
Automatisierung
|_ Flow
|_ Prozesse
end legend
----

<<<

== Blog

In diesem Abschnitt werden die Berechtigungen für den Bereich Blog aufgelistet.

[plantuml, format=png, opts="inline"]
----
!include styles/tree-style.iuml
legend
Blog
|_ Eigenschaft
end legend
----

<<<

== Zertifizierung

In diesem Abschnitt werden die Berechtigungen für den Bereich Zertifizierung aufgelistet.

[plantuml, format=png, opts="inline"]
----
!include styles/tree-style.iuml
legend
Zertifizierung
|_ Bearbeiten
end legend
----

<<<

== Mandant

In diesem Abschnitt werden die Berechtigungen für den Bereich Mandant aufgelistet.

[plantuml, format=png, opts="inline"]
----
!include styles/tree-style.iuml
legend
Mandant
|_ Gewinnspiele
|_ Domains
|_ Feedback
|_ FTP-Einstellungen
|_ Geschenkservice
|_ Sprachpakete
|_ Live-Shopping
|_ Dienste
|_ Einstellungen
|_ Mandantenspezifische Einstellungen
|_ SSL-Einstellungen
|_ Statistik
|_ Versionseinstellungen
end legend
----

<<<

=== Gewinnspiele

[plantuml, format=png, opts="inline"]
----
!include styles/tree-style.iuml
legend
Gewinnspiele
|_ Bearbeiten
end legend
----

<<<

=== Domains

[plantuml, format=png, opts="inline"]
----
!include styles/tree-style.iuml
legend
Domains
  |_ Bearbeiten
end legend
----

<<<

=== Feedback

[plantuml, format=png, opts="inline"]
----
!include styles/tree-style.iuml
legend
Feedback
  |_ Bearbeiten
end legend
----

<<<

=== FTP-Einstellungen

[plantuml, format=png, opts="inline"]
----
!include styles/tree-style.iuml
legend
FTP-Einstellungen
  |_ Bearbeiten
end legend
----

<<<

=== Geschenkservice

[plantuml, format=png, opts="inline"]
----
!include styles/tree-style.iuml
legend
Geschenkservice
  |_ Bearbeiten
end legend
----

<<<

=== Sprachpakete

[plantuml, format=png, opts="inline"]
----
!include styles/tree-style.iuml
legend
Sprachpakete
  |_ Bearbeiten
end legend
----

<<<

=== Live-Shopping

[plantuml, format=png, opts="inline"]
----
!include styles/tree-style.iuml
legend
Live-Shopping
  |_ Bearbeiten
end legend
----

<<<

=== Dienste

[plantuml, format=png, opts="inline"]
----
!include styles/tree-style.iuml
legend
Dienste
|_ bit.ly
  |_ Bearbeiten
|_ Cliplister
  |_ Bearbeiten
|_ Dropbox
  |_ Bearbeiten
|_ Facebook
  |_ Bearbeiten
|_ Facettensuche
  |_ Bearbeiten
|_ Familienkarte
  |_ Bearbeiten
|_ Lionbridge
  |_ Bearbeiten
|_ Picalike
  |_ Bearbeiten
|_ Testbericht.de
  |_ Bearbeiten
|_ Twitter
  |_ Bearbeiten
end legend
----

<<<

=== Einstellungen

[plantuml, format=png, opts="inline"]
----
!include styles/tree-style.iuml
legend
Einstellungen
|_ Bearbeiten
end legend
----

<<<

=== Mandantenspezifische Einstellungen

[plantuml, format=png, opts="inline"]
----
!include styles/tree-style.iuml
legend
Mandantenspezifische Einstellungen
|_ Affiliate
  |_ Bearbeiten
|_ Kategorieeinstellungen
  |_ Bearbeiten
|_ Bearbeiten
|_ ShopBooster
  |_ Bearbeiten
|_ Module
  |_ Bearbeiten
|_ Mein Konto
  |_ Bearbeiten
|_ Bestellvorgang
  |_ Bearbeiten
|_ SEO-Einstellungen
  |_ Bearbeiten
|_ Services
  |_ Bearbeiten
|_ Zolltarifnummern
  |_ Anzeigen
  |_ Bearbeiten
end legend
----

<<<

=== SSL-Einstellungen

[plantuml, format=png, opts="inline"]
----
!include styles/tree-style.iuml
legend
SSL-Einstellungen
|_ Bearbeiten
end legend
----

<<<

=== Statistik

[plantuml, format=png, opts="inline"]
----
!include styles/tree-style.iuml
legend
Statistik
|_ Bearbeiten
end legend
----

<<<

=== Versionseinstellungen

[plantuml, format=png, opts="inline"]
----
!include styles/tree-style.iuml
legend
Versionseinstellungen
|_ Bearbeiten
end legend
----

<<<

== CMS

In diesem Abschnitt werden die Berechtigungen für den Bereich CMS aufgelistet.

[plantuml, format=png, opts="inline"]
----
!include styles/tree-style.iuml
legend
CMS
|_ Container-Verknüpfungen
|_ Dokumente
|_ Feedbacks
|_ Formulare
|_ Artikelgalerie
|_ Rechtliche Angaben
|_ Mehrsprachigkeit
|_ Alt
|_ PWA
|_ RSS
|_ ShopBuilder
|_ Templates
|_ Webspace
end legend
----

<<<

=== Feedbacks

[plantuml, format=png, opts="inline"]
----
!include styles/tree-style.iuml
legend
Feedbacks
|_ Feedbacks
|_ Feedback-Kommentare
|_ Migrieren
|_ Feedback-Bewertungen
end legend
----

<<<

=== Formulare

[plantuml, format=png, opts="inline"]
----
!include styles/tree-style.iuml
legend
Formulare
|_ Bearbeiten
end legend
----

<<<

=== Artikelgalerie

[plantuml, format=png, opts="inline"]
----
!include styles/tree-style.iuml
legend
Artikelgalerie
|_ Bearbeiten
end legend
----

<<<

=== Alt

[plantuml, format=png, opts="inline"]
----
!include styles/tree-style.iuml
legend
Alt
|_ Termine
|_ Blog
|_ Konstanten
|_ Feedback
|_ Suchen und Ersetzen
|_ Webspace (alt)
end legend
----

<<<

=== RSS

[plantuml, format=png, opts="inline"]
----
!include styles/tree-style.iuml
legend
RSS
|_ Bearbeiten
end legend
----

<<<

=== Templates

[plantuml, format=png, opts="inline"]
----
!include styles/tree-style.iuml
legend
Templates
|_ Designs
  |_ Design-Einstellungen
    |_ Kopieren
end legend
----

<<<

== Kommentare

In diesem Abschnitt werden die Berechtigungen für den Bereich Kommentare aufgelistet.

[plantuml, format=png, opts="inline"]
----
!include styles/tree-style.iuml
legend
Kommentare
end legend
----

<<<

== CRM

In diesem Abschnitt werden die Berechtigungen für den Bereich CRM aufgelistet.

[plantuml, format=png, opts="inline"]
----
!include styles/tree-style.iuml
legend
CRM
|_ Firma
|_ Adresse
|_ Adress-Layout
|_ Bankdaten
|_ Kampagne
|_ Kontakt
|_ Kontaktklasse
|_ Schuldner
|_ E-Mail
|_ EmailBuilder
|_ Event
|_ Jobtitel
|_ Nachricht
|_ Messenger
|_ Newsletter
|_ Auftragszusammenfassung
|_ Passwort
|_ Eigenschaft
|_ Umsatzsteuereinheiten
|_ Serviceeinheiten
|_ Ticket
|_ Typ
end legend
----

<<<

=== Adresse

[plantuml, format=png, opts="inline"]
----
!include styles/tree-style.iuml
legend
Adresse
|_ Adresse
|_ Typ der Adressoption
|_ Adresstyp
end legend
----

<<<

=== Adress-Layout

[plantuml, format=png, opts="inline"]
----
!include styles/tree-style.iuml
legend
Adress-Layout
|_ Adress-Layout
|_ Bearbeiten
end legend
----

<<<

=== Bankdaten

[plantuml, format=png, opts="inline"]
----
!include styles/tree-style.iuml
legend
Bankdaten
|_ Bankdaten
|_ Bearbeiten
end legend
----

<<<

=== Kampagne

[plantuml, format=png, opts="inline"]
----
!include styles/tree-style.iuml
legend
Kampagne
|_ Kampagne
|_ Code
|_ Bearbeiten
end legend
----

<<<

=== Kontakt

[plantuml, format=png, opts="inline"]
----
!include styles/tree-style.iuml
legend
Kontakt
|_ Kontakt
|_ Anonymisieren
|_ Typ der Kontaktoption
|_ Eigner ändern
end legend
----

<<<

=== Kontaktklasse

[plantuml, format=png, opts="inline"]
----
!include styles/tree-style.iuml
legend
Kontaktklasse
|_ Bearbeiten
end legend
----

<<<

=== E-Mail

[plantuml, format=png, opts="inline"]
----
!include styles/tree-style.iuml
legend
E-Mail
|_ Zugangsdaten bearbeiten
|_ Automatischer Versand bearbeiten
|_ E-Mail-Einstellungen bearbeiten
|_ HTML-Design bearbeiten
|_ Infodienst bearbeiten
|_ Newsletter bearbeiten
|_ Signatur bearbeiten
|_ Vorlagen bearbeiten
end legend
----

<<<

=== Messenger

[plantuml, format=png, opts="inline"]
----
!include styles/tree-style.iuml
legend
Messenger
|_ Bearbeiten
|_ Konversationen
|_ Eignerschaft
end legend
----

<<<

=== Newsletter

[plantuml, format=png, opts="inline"]
----
!include styles/tree-style.iuml
legend
Newsletter
|_ Newsletter
|_ Bearbeiten
|_ Newsletter-Ordner
|_ Newsletter-Empfänger
end legend
----

<<<

=== Passwort

[plantuml, format=png, opts="inline"]
----
!include styles/tree-style.iuml
legend
Passwort
|_ Bearbeiten
end legend
----

<<<

=== Eigenschaft

[plantuml, format=png, opts="inline"]
----
!include styles/tree-style.iuml
legend
Eigenschaft
|_ Bearbeiten
end legend
----

<<<

=== Serviceeinheiten

[plantuml, format=png, opts="inline"]
----
!include styles/tree-style.iuml
legend
Serviceeinheiten
|_ Serviceeinheiten
|_ Bearbeiten
end legend
----

<<<

=== Umsatzsteuer-ID

[plantuml, format=png, opts="inline"]
----
!include styles/tree-style.iuml
legend
Umsatzsteuer-ID
|_ Bearbeiten
end legend
----

<<<

=== Ticket

[plantuml, format=png, opts="inline"]
----
!include styles/tree-style.iuml
legend
Ticket
|_ Ticket
|_ Bearbeiten
|_ Ticketnachricht
  |_ Interne Ticke-Nachricht
  |_ Öffentliche Ticket-Nachricht
|_ Eignerschaft
|_ Ticket-Rolle
|_ Ticket-Status
|_ Ticket-Typ
end legend
----

<<<

=== Typ

[plantuml, format=png, opts="inline"]
----
!include styles/tree-style.iuml
legend
Typ
|_ Bearbeiten
end legend
----

<<<

== Daten

In diesem Abschnitt werden die Berechtigungen für den Bereich Daten aufgelistet.

[plantuml, format=png, opts="inline"]
----
!include styles/tree-style.iuml
legend
Daten
|_ Änderungshistorie
|_ Backup
|_ Datenbereinigung
|_ Datenaustausch
|_ Gelöschte Logs
|_ Export
|_ Historie
|_ Import
|_ Log
|_ Migration
|_ Druckverlauf
|_ Report
|_ Status
|_ Sync
|_ Sync Daten-Log
end legend
----

<<<

=== Änderungshistorie

In diesem Abschnitt werden die Berechtigungen für den Bereich Änderungshistorie aufgelistet.

[plantuml, format=png, opts="inline"]
----
!include styles/tree-style.iuml
legend
Änderungshistorie
|_ Archiv
  |_ Archiv
  |_ Anfordern
|_ Suche
|_ Tagesänderungen
|_ Einstellungen
end legend
----

<<<

=== Backup

[plantuml, format=png, opts="inline"]
----
!include styles/tree-style.iuml
legend
Backup
|_ Bearbeiten
end legend
----

<<<

=== Datenbereinigung

[plantuml, format=png, opts="inline"]
----
!include styles/tree-style.iuml
legend
Datenbereinigung
|_ Datenbereinigung
|_ Bearbeiten
end legend
----

<<<

=== Datenaustausch

[plantuml, format=png, opts="inline"]
----
!include styles/tree-style.iuml
legend
Datenaustausch
|_ Export
  |_ Katalog
  |_ Dynamischer Export
  |_ Elastischer Export
  |_ Spezialexport
|_ Import
  |_ Dynamischer Import
end legend
----

<<<

=== Export

[plantuml, format=png, opts="inline"]
----
!include styles/tree-style.iuml
legend
Export
|_Elastischer Export
end legend
----

<<<

=== Import

[plantuml, format=png, opts="inline"]
----
!include styles/tree-style.iuml
legend
Import
|_ eBay-Listings
end legend
----

<<<

=== Log

[plantuml, format=png, opts="inline"]
----
!include styles/tree-style.iuml
legend
Log
|_ Log
|_ API-Log
  |_ API-Log
  |_ Bearbeiten
end legend
----

<<<

=== Migration

[plantuml, format=png, opts="inline"]
----
!include styles/tree-style.iuml
legend
Migration
|_ Bearbeiten
end legend
----

<<<

=== Report

[plantuml, format=png, opts="inline"]
----
!include styles/tree-style.iuml
legend
Report
|_ Kennzahlen
  |_ Kennzahlen
  |_ Bearbeiten
|_ Rohdaten
  |_ Rohdaten
  |_ Bearbeiten
end legend
----

<<<

=== Sync

[plantuml, format=png, opts="inline"]
----
!include styles/tree-style.iuml
legend
Sync
|_ Sync
|_ Zuordnung
end legend
----

<<<

== Dokumente

In diesem Abschnitt werden die Berechtigungen für den Bereich Dokumente aufgelistet.

[plantuml, format=png, opts="inline"]
----
!include styles/tree-style.iuml
legend
|_ DocumentBuilder
|_ Nummernkreise
|_ Einstellungen
end legend
----

<<<

=== DocumentBuilder

[plantuml, format=png, opts="inline"]
----
!include styles/tree-style.iuml
legend
|_ Dokumentvorlagen
  |_ Dokumentvorlagen
  |_ Aktivieren/Deaktvieren
|_ Nummernkreise
|_ Einstellungen  
end legend
----

<<<

== Editoren

In diesem Abschnitt werden die Berechtigungen für den Bereich Editoren aufgelistet.

[plantuml, format=png, opts="inline"]
----
!include styles/tree-style.iuml
legend
Editoren
|_ Bearbeiten
end legend
----

<<<

== Artikel

In diesem Abschnitt werden die Berechtigungen für den Bereich Artikel aufgelistet.

[plantuml, format=png, opts="inline"]
----
!include styles/tree-style.iuml
legend
Artikel
|_ Aktionen
|_ Attribut
|_ Verfügbarkeit
|_ Barcode
|_ Kategorie
|_ Digital
|_ Markierung
|_ Freitextfeld
|_ GTIN
|_ Bild
|_ Artikel
|_ Artikeletikett
|_ Lionbridge
|_ Hersteller
|_ Neue Artikel UI
|_ Packstück
|_ Preiskalkulation
|_ Merkmal
|_ Verkaufspreis
|_ Suche
|_ Artikelsets
|_ Einstellungen
|_ Einheit
|_ Inhalt
end legend
----

<<<

=== Aktionen

[plantuml, format=png, opts="inline"]
----
!include styles/tree-style.iuml
legend
Aktionen
|_ Bearbeiten
end legend
----

<<<

=== Attribut

[plantuml, format=png, opts="inline"]
----
!include styles/tree-style.iuml
legend
Attribut
|_ Attribut
|_ Bearbeiten
|_ Attributverknüpfung
|_ Attributname
|_ Attributwert
  |_Attributwert
  |_ Attributwertname
end legend
----

<<<

=== Verfügbarkeit

[plantuml, format=png, opts="inline"]
----
!include styles/tree-style.iuml
legend
Verfügbarkeit
|_ Verfügbarkeit bearbeiten
end legend
----

<<<

=== Barcode

[plantuml, format=png, opts="inline"]
----
!include styles/tree-style.iuml
legend
Barcode
|_ Barcode
|_ Bearbeiten
end legend
----

<<<

=== Digital

[plantuml, format=png, opts="inline"]
----
!include styles/tree-style.iuml
legend
Digital
|_ Bearbeiten
end legend
----

<<<

=== Markierung

[plantuml, format=png, opts="inline"]
----
!include styles/tree-style.iuml
legend
Markierung
|_ Bearbeiten
end legend
----

<<<

=== Freitextfeld

[plantuml, format=png, opts="inline"]
----
!include styles/tree-style.iuml
legend
Freitextfeld
|_ Bearbeiten
end legend
----

<<<

=== GTIN

[plantuml, format=png, opts="inline"]
----
!include styles/tree-style.iuml
legend
GTIN
|_ Bearbeiten
end legend
----

<<<

=== Bild

[plantuml, format=png, opts="inline"]
----
!include styles/tree-style.iuml
legend
Bild
|_ Einstellungen
  |_ Bearbeiten
|_ Größe
  |_ Bearbeiten
end legend
----

<<<

=== Artikel

[plantuml, format=png, opts="inline"]
----
!include styles/tree-style.iuml
legend
Artikel
|_ Artikel
|_ Cross-Selling
|_ Artikelbild
  |_ Artikelbild
  |_ Verfügbarkeit
  |_ Artikelbildname
|_ Seriennummer
|_ Set
|_ Variante
end legend
----

<<<

==== Variante

[plantuml, format=png, opts="inline"]
----
!include styles/tree-style.iuml
legend
Variante
|_ Variante
|_ Zusätzliche SKU
|_ Attribut
|_ Barcode
|_ Artikelpaket
|_ Kategorie
|_ Mandant
|_ Standardkategorie
|_ Artikeltext
|_ Marktplatz
|_ Merkmal
|_ Bestandskorrektur
|_ Einkaufspreis
|_ Preis
|_ Bestandskorrektur
|_ Lagerdaten
|_ Lieferantendaten  
end legend
----

<<<

===== Attribut

[plantuml, format=png, opts="inline"]
----
!include styles/tree-style.iuml
legend
Attribut
|_ Wert
end legend
----

<<<

===== Marktplatz

[plantuml, format=png, opts="inline"]
----
!include styles/tree-style.iuml
legend
Marktplatz
|_ Marktplatz
|_ ASIN/ePID
end legend
----

<<<

===== Merkmal

[plantuml, format=png, opts="inline"]
----
!include styles/tree-style.iuml
legend
Merkmal
|_ Merkmal
|_ Eigenschaftswerte
|_ Eigenschaftswerte
|_ Text
end legend
----

<<<

=== Artikeletikett

[plantuml, format=png, opts="inline"]
----
!include styles/tree-style.iuml
legend
Artikeletikett
|_ Artikeletikett
|_ Bearbeiten
end legend
----

<<<

=== Hersteller

[plantuml, format=png, opts="inline"]
----
!include styles/tree-style.iuml
legend
Hersteller
|_ Hersteller
|_ Herstellerprovision
|_ Bearbeiten
|_ Externer Hersteller
end legend
----

<<<

=== Preiskalkulation

[plantuml, format=png, opts="inline"]
----
!include styles/tree-style.iuml
legend
Preiskalkulation
|_ Preiskalkulation
|_ Bearbeiten ALT
|_ Bearbeiten
end legend
----

<<<

=== Merkmal

[plantuml, format=png, opts="inline"]
----
!include styles/tree-style.iuml
legend
Merkmal
|_ Merkmal
|_ Bearbeiten
|_  Merkmalgruppe
  |_ Merkmalgruppe
  |_ Merkmalgruppenname
|_ Marktplatzmerkmal
|_ Merkmalname
|_ Auswahl
end legend
----

<<<

=== Verkaufspreis

[plantuml, format=png, opts="inline"]
----
!include styles/tree-style.iuml
legend
Verkaufspreis
|_ Verkaufspreis
|_ Konto
|_ Bearbeiten
|_ Land
|_ Währung
|_ Kundenklasse
|_ Name
|_ Mandant
|_ Herkunft
end legend
----

<<<

=== Suche

[plantuml, format=png, opts="inline"]
----
!include styles/tree-style.iuml
legend
Suche
|_ Backend
  |_ Bearbeiten
|_ Frontend
  |_ Sprache
    |_ Bearbeiten
  |_ Einstellungen
    |_ Bearbeiten
end legend
----

<<<

=== Einstellungen

[plantuml, format=png, opts="inline"]
----
!include styles/tree-style.iuml
legend
Einstellungen
|_ Bearbeiten
end legend
----

=== Einheit

[plantuml, format=png, opts="inline"]
----
!include styles/tree-style.iuml
legend
Einheit
|_ Einheit
|_ Bearbeiten
|_ Einheitenname
end legend
----

<<<

== Listing

In diesem Abschnitt werden die Berechtigungen für den Bereich Listing aufgelistet.

[plantuml, format=png, opts="inline"]
----
!include styles/tree-style.iuml
legend
Listing
|_ Listing
|_ Verzeichnisse
|_ Zukünftige Listings
|_ Layouts
|_ Layout-Vorlage
|_ Market-Listing
|_ Optionenvorlage
|_ Kaufabwicklung
|_ Verkaufsplaner
|_ Einstellungen
|_ Versandprofil
|_ Warenbestand
|_ Bestandsabhängigkeit
|_ Listing-Typ
end legend
----

<<<

=== Verzeichnisse

[plantuml, format=png, opts="inline"]
----
!include styles/tree-style.iuml
legend
Verzeichnisse
|_ Bearbeiten
end legend
----

<<<

=== Layouts

[plantuml, format=png, opts="inline"]
----
!include styles/tree-style.iuml
legend
Layouts
|_ Bearbeiten
end legend
----

<<<

=== Market-Listing

[plantuml, format=png, opts="inline"]
----
!include styles/tree-style.iuml
legend
Market-Listing
|_ Market-Listing
|_ Aktive Listings
  |_ Aktive Listings
  |_ Beenden
  |_ Wiedereinstellen
|_ Informationen
|_ Merkmale
|_ Aktivieren 
|_ Text
end legend
----

<<<

=== Kaufabwicklung

[plantuml, format=png, opts="inline"]
----
!include styles/tree-style.iuml
legend
Kaufabwicklung
|_ Bearbeiten
end legend
----

<<<

=== Verkaufsplaner

[plantuml, format=png, opts="inline"]
----
!include styles/tree-style.iuml
legend
Verkaufsplaner
|_ Bearbeiten
end legend
----

<<<

=== Einstellungen

[plantuml, format=png, opts="inline"]
----
!include styles/tree-style.iuml
legend
Einstellungen
|_ Bearbeiten
end legend
----

<<<

=== Warenbestand

[plantuml, format=png, opts="inline"]
----
!include styles/tree-style.iuml
legend
Warenbestand
|_ Bearbeiten
end legend
----

<<<

== Märkte

In diesem Abschnitt werden die Berechtigungen für den Bereich Märkte aufgelistet.

[plantuml, format=png, opts="inline"]
----
!include styles/tree-style.iuml
legend
Märkte
|_ Konten
|_ Amazon
|_ bol.com
|_ Cdiscount
|_ Check24
|_ Conrad
|_ Zugangsdaten
|_ Decathlon
|_ eBay
|_ eMAG
|_ Flubit
|_ Fruugo
|_ Google Shopping DE
|_ Google Shopping Int.
|_ grosshandel.eu
|_ Hood
|_ idealo
|_ Kauflux
|_ La Redoute
|_ Mercateo
|_ Neckermann Österreich Enterprise
|_ Netto eStores
|_ Otto
|_ PIXmania
|_ Rakuten.de
|_ Kaufland.de
|_ Restposten
|_ ricardo
|_ Shopgate
|_ Shopify App
|_ Völkner
|_ Yatego
|_ Zalando
end legend
----

<<<

=== Amazon

[plantuml, format=png, opts="inline"]
----
!include styles/tree-style.iuml
legend
Amazon
|_ Kategorieverknüpfung
  |_ Bearbeiten
|_ Datenaustausch
  |_ Datenexport
    |_ Bearbeiten
  |_ FBA Warenbestand
    |_ Bearbeiten
  |_ Auftragsimport
    |_ Bearbeiten
  |_ Berichte
    |_ Bearbeiten
  |_ Versandbestätigung
    |_ Bearbeiten
|_ ASIN-Verknüpfung
  |_ Bearbeiten  
|_ Frei definierbare Felder
  |_ Bearbeiten
|_ Berichte
  |_ Verarbeitungsstatus
    |_ Verarbeitungsstatus
    |_ Herunterladen 
|_ Einstellungen
  |_ Bearbeiten
end legend
----

<<<

=== bol.com

[plantuml, format=png, opts="inline"]
----
!include styles/tree-style.iuml
legend
bol.com
|_ bol.com Konfiguration
end legend
----

<<<

=== Cdisount

[plantuml, format=png, opts="inline"]
----
!include styles/tree-style.iuml
legend
Cdiscount
|_ Bearbeiten
end legend
----

<<<

=== Check24

[plantuml, format=png, opts="inline"]
----
!include styles/tree-style.iuml
legend
Check24
|_ Bearbeiten
end legend
----

<<<

=== Conrad

[plantuml, format=png, opts="inline"]
----
!include styles/tree-style.iuml
legend
Conrad
|_ Datenaustausch
  |_ Datenexport
    |_ Bearbeiten
  |_ Auftragsimport
    |_ Bearbeiten
|_ Berichte
  |_ Bearbeiten
|_ Einstellungen
|_ Katalog-Vorlagen
  |_ Bearbeiten
end legend
----

<<<

=== Decathlon

[plantuml, format=png, opts="inline"]
----
!include styles/tree-style.iuml
legend
Decathlon
|_ Datenaustausch
  |_ Datenexport
    |_ Bearbeiten
  |_ Auftragsimport
    |_ Bearbeiten
|_ Einstellungen
|_ Katalog-Vorlagen
  |_ Bearbeiten
end legend
----

<<<

=== eBay

[plantuml, format=png, opts="inline"]
----
!include styles/tree-style.iuml
legend
eBay
|_ Rahmenbedingungen
  |_ Bearbeiten
|_ eBay-Kategorie
|_ Konten
  |_ Bearbeiten 
|_ Datenaustausch
  |_ Bearbeiten
|_ Fahrzeugverwendungsliste
  |_ Fahrzeugwendungsliste
  |_ Bearbeiten
|_ Versandbedingungen
|_ eBay-Merkmal
|_ Marktplatz
|_ eBay-Zahlungsbedingungen
|_ ePID-Verknüpfung
  |_ ePID-Verknüpfung
  |_ Bearbeiten
  |_ eBay-Produkt
|_ Product Compliance
|_ Rücknahmebedingungen
|_ Second Chance Offer
  |_ Bearbeiten
|_ Einstellungen
  |_ Bearbeiten
|_ Rücknahmebedingungen nach ElektroG
end legend
----

<<<

=== eMAG

[plantuml, format=png, opts="inline"]
----
!include styles/tree-style.iuml
legend
eMAG
|_ Einstellungen
  |_ Bearbeiten
|_ Datenaustausch
  |_ Artikelexport
    |_ Bearbeiten
  |_ Angebotsaktualisierung
    |_ Bearbeiten
  |_ Auftragsimport
    |_ Bearbeiten
----

<<<

=== Flubit

[plantuml, format=png, opts="inline"]
----
!include styles/tree-style.iuml
legend
Märkte
|_ Flubit
  |_ Bearbeiten
end legend
----

<<<

=== Fruugo

[plantuml, format=png, opts="inline"]
----
!include styles/tree-style.iuml
legend
Fruugo
|_ Bearbeiten
end legend
----

<<<

=== Google Shopping DE

[plantuml, format=png, opts="inline"]
----
!include styles/tree-style.iuml
legend
Google Shopping DE
|_ Bearbeiten
end legend
----

<<<

=== Google Shopping Int.

[plantuml, format=png, opts="inline"]
----
!include styles/tree-style.iuml
legend
Google Shopping Int.
|_ Bearbeiten
end legend
----

<<<

=== grosshandel.eu

[plantuml, format=png, opts="inline"]
----
!include styles/tree-style.iuml
legend
grosshandel.eu
|_ Bearbeiten
end legend
----

<<<

=== Hood

[plantuml, format=png, opts="inline"]
----
!include styles/tree-style.iuml
legend
Hood
|_ Bearbeiten
end legend
----

<<<

=== idealo

[plantuml, format=png, opts="inline"]
----
!include styles/tree-style.iuml
legend
idealo
|_ Bearbeiten
end legend
----

<<<

=== Kauflux

[plantuml, format=png, opts="inline"]
----
!include styles/tree-style.iuml
legend
Kauflux
|_ Kategorieverknüpfung
  |_ Bearbeiten
|_ Einstellungen
  |_ Bearbeiten
end legend
----

<<<

=== La Redoute

[plantuml, format=png, opts="inline"]
----
!include styles/tree-style.iuml
legend
La Redoute
|_ Kategorieverknüpfung
  |_ Bearbeiten
|_ Import
  |_ Bearbeiten
|_ Einstellungen
  |_ Bearbeiten
end legend
----

<<<

=== Mercateo

[plantuml, format=png, opts="inline"]
----
!include styles/tree-style.iuml
legend
Mercateo
|_ Datenexport
  |_ Bearbeiten
|_ Export-Verlauf
  |_ Bearbeiten
|_ Einstellungen
  |_ Bearbeiten
end legend
----

<<<

=== Neckermann Österreich Enterprise

[plantuml, format=png, opts="inline"]
----
!include styles/tree-style.iuml
legend
Neckermann Österreich Enterprise
|_ Bearbeiten
end legend
----

<<<

=== Netto eStores

[plantuml, format=png, opts="inline"]
----
!include styles/tree-style.iuml
legend
Netto eStores
|_ Bearbeiten
end legend
----

<<<

=== Otto

[plantuml, format=png, opts="inline"]
----
!include styles/tree-style.iuml
legend
Otto
|_ Otto Cooperation
  |_ Bearbeiten
|_ Otto Direktversand
  |_ Bearbeiten
|_ Otto Integration
  |_ Bearbeiten
|_ OTTO PreDropshipment
  |_ Bearbeiten
end legend
----

<<<

=== PIXmania

[plantuml, format=png, opts="inline"]
----
!include styles/tree-style.iuml
legend
PIXmania
|_ Kategorieverknüpfung
  |_ Bearbeiten
|_ Export-Verlauf
  |_ Bearbeiten
|_ Einstellungen
  |_ Bearbeiten
end legend
----

<<<

=== Rakuten.de

[plantuml, format=png, opts="inline"]
----
!include styles/tree-style.iuml
legend
Rakuten.de
|_ Bearbeiten
end legend
----

<<<

=== Kaufland.de

[plantuml, format=png, opts="inline"]
----
!include styles/tree-style.iuml
legend
|_ Kategorieverknüpfung
  |_ Bearbeiten
|_ Einstellungen
  |_ Bearbeiten
end legend
----

<<< 

=== Restposten

[plantuml, format=png, opts="inline"]
----
!include styles/tree-style.iuml
legend
Restposten
|_ Bearbeiten
end legend
----

<<<

=== ricardo

[plantuml, format=png, opts="inline"]
----
!include styles/tree-style.iuml
legend
ricardo
|_ Konten
  |_ Bearbeiten
|_ Einstellungen
  |_ Bearbeiten
end legend
----

<<<

=== Shopgate

[plantuml, format=png, opts="inline"]
----
!include styles/tree-style.iuml
legend
Shopgate
|_ Bearbeiten
end legend
----

<<<

=== Shopify App

[plantuml, format=png, opts="inline"]
----
!include styles/tree-style.iuml
legend
|_ Migrationsassistent
|_ Hilfe
  |_ Bereitschaft prüfen
    |_ Bearbeiten
  |_ Exportbedingungen
    |_ Bearbeiten
  |_ Auftrags-ID finden
    |_ Bearbeiten
  |_ Artikelbereinigung
    |_ Bearbeiten
  |_ Artikelexport
    |_ Bearbeiten
  |_ Auftragsimport
    |_ Bearbeiten
  |_ Bestandsexport
    |_ Bearbeiten
----

<<<

=== Völkner

[plantuml, format=png, opts="inline"]
----
!include styles/tree-style.iuml
legend
|_ Datenaustausch
  |_ Datenexport
    |_ Bearbeiten
  |_ Auftragsimport
    |_ Bearbeiten
|_ Berichte
  |_  Bearbeiten
|_ Einstellungen
|_ Katalog-Vorlagen
  |_ Bearbeiten
----

<<<

=== Yatego

[plantuml, format=png, opts="inline"]
----
!include styles/tree-style.iuml
legend
Yatego
|_ Kategorieverknüpfung
  |_ Bearbeiten
|_ Einstellungen
  |_ Bearbeiten
end legend
----

<<<

=== Zalando

[plantuml, format=png, opts="inline"]
----
!include styles/tree-style.iuml
legend
Zalando
|_ Kategorieverknüpfung
  |_ Bearbeiten
|_ Einstellungen
  |_ Bearbeiten
end legend
----

<<<

== Stammdaten

In diesem Abschnitt werden die Berechtigungen für den Bereich Stammdaten aufgelistet.

[plantuml, format=png, opts="inline"]
----
!include styles/tree-style.iuml
legend
Stammdaten
|_ Bearbeiten
end legend
----

<<<

== plentyApp-Einstellungen

In diesem Abschnitt werden die Berechtigungen für den Bereich plentyApp-Einstellungen aufgelistet.

[plantuml, format=png, opts="inline"]
----
!include styles/tree-style.iuml
legend
plentyApp-Einstellungen
|_ Bearbeiten
end legend
----

<<<

== Zahlenformat

In diesem Abschnitt werden die Berechtigungen für den Bereich Zahlenformat aufgelistet.

[plantuml, format=png, opts="inline"]
----
!include styles/tree-style.iuml
legend
Zahlenformat
|_ Bearbeiten
end legend
----

<<<

== Aufträge

In diesem Abaschnitt werden die Berechtigungen für den Bereich Aufträge aufgelistet.

[plantuml, format=png, opts="inline"]
----
!include styles/tree-style.iuml
legend
Aufträge
|_ Aufträge
|_ Auftragsadressen
|_ Warenausgang buchen
|_ Buchung
|_ Auftragseinstellungen
|_ Dokumente
|_ Inkasso-Übergabe
|_ Ereignisse
|_ Fulfillment
|_ Gruppenfunktion (neue Auftrags-UI)
|_ Auftragspositionen
|_ Sammelauftrag
|_ Eignerschaft
|_ Zahlung
|_ Auftragseigenschaften
|_ Bestellungen
|_ Referenzen für Auftragsrelationen
|_ Auftrag wiederherstellen
|_ Warenausgang zurücksetzen
|_ Warenausgang der Auftragsposition zurücksetzen
|_ Scheduler
|_ Seriennummern im Auftrag
|_ Versand
|_ Auftragsstatus
end legend
----

<<<

=== Dokumente

[plantuml, format=png, opts="inline"]
----
!include styles/tree-style.iuml
legend
Dokumente
|_ Dokumente
|_ Dokumenteinstellungen
|_ Dokumente zusammenfügen
end legend
----

<<<

=== Ereignisse

[plantuml, format=png, opts="inline"]
----
!include styles/tree-style.iuml
legend
Ereignisse
|_ Ereigniseinstellungen
end legend
----

<<<

=== Fulfillment

[plantuml, format=png, opts="inline"]
----
!include styles/tree-style.iuml
legend
Fulfillment
|_ Fulfillment
|_ Pickliste
end legend
----

<<<

=== Gruppenfunktion (neue Auftrags-UI)

[plantuml, format=png, opts="inline"]
----
!include styles/tree-style.iuml
legend
Gruppenfunktion (neue Auftrags-UI)
|_ Gruppenfunktion (neue Auftrags-UI)
|_ Warenausgang buchen
|_ Warenausgang zurücksetzen
|_ Lieferdatum
|_ Versanddatum
|_ Eigner
|_ Versandkosten
|_ Versandprofil
|_ Status
|_ Tags
|_ Dokumente
  |_ Korrektubeleg
  |_ Gutschrift
  |_ Lieferschein
  |_ Mahnung
  |_ Gelangensbestätigung
  |_ Rechnung
  |_ Auftragsbestätigung
  |_ Proformarechnung
  |_ Reparaturschein
  |_ Rücksendeschein
  |_ Stornobeleg Rechnung
  |_ Stornobeleg Mahnung
  |_ Stornobeleg Gutschrift
|_ Aufträge gruppieren
|_ Dokumente zusammenfügen
|_ E-Mail
end legend
----

<<<

=== Auftragsposition

[plantuml, format=png, opts="inline"]
----
!include styles/tree-style.iuml
legend
Auftragspositionen
|_ Datumsangaben
|_ Deckungsbeitrag
|_ Eigenschaften
|_ Transaktionen
end legend
----

<<<

=== Zahlung

[plantuml, format=png, opts="inline"]
----
!include styles/tree-style.iuml
legend
Zahlung
|_ Zahlung
|_ Zahlungseinstellungen
end legend
----

<<<

=== Auftragseigenschaften

[plantuml, format=png, opts="inline"]
----
!include styles/tree-style.iuml
legend
Auftragseigenschaften
|_ Auftragseigenschaften
|_ Typen für Auftragseigenschaften
end legend
----

<<<

=== Bestellungen

[plantuml, format=png, opts="inline"]
----
!include styles/tree-style.iuml
legend
Bestellungen
|_ Bestellungen
|_ Gruppenfunktion
  |_ Gruppenfunktion
  |_ Lieferdatum
  |_ Abschlussdatum
  |_ Bestelldatum
  |_ Status
  |_ Löschen
  |_ E-Mail
|_ Bestellungseinstellungen
end legend
----

<<<

=== Scheduler

[plantuml, format=png, opts="inline"]
----
!include styles/tree-style.iuml
legend
Scheduler
|_ Scheduler
|_ Schedulereinstellungen
|_ Eignerschaft
end legend
----

<<<

=== Versand

[plantuml, format=png, opts="inline"]
----
!include styles/tree-style.iuml
legend
Versand
|_ Versandeinstellungen
|_ Versandpaket
  |_ Versandpaket
  |_ Artikel im Versandpaket
|_ Pakettyp
|_ Versandpaletten
|_ Retourenlabel
  |_ Retourenlabel
  |_ Retourendienstleister
end legend
----

<<<

== plentyBI

In diesem Abschnitt werden die Berechtigungen für den Bereich plentyBI aufgelistet.

[plantuml, format=png, opts="inline"]
----
!include styles/tree-style.iuml
legend
plentyBI
|_ Kennzahlen
  |_ Arithmetik
    |_ Konfigurieren
    |_ Rohdaten anzeigen
  |_ plentyBI
  |_ CRM
  |_ Artikel
  |_ Messenger
  |_ Omni-Channel
  |_ Aufträge
  |_ Zahlungen
  |_ Plugins
  |_ Verbrauch
end legend
----

<<<

=== plentyBI

[plantuml, format=png, opts="inline"]
----
!include styles/tree-style.iuml
legend
plentyBI
|_ Global
  |_ Konfigurieren
  |_ Rohdaten anzeigen
end legend
----

<<<

=== CRM

[plantuml, format=png, opts="inline"]
----
!include styles/tree-style.iuml
legend
CRM
|_ Kontakte
  |_ Konfigurieren
  |_ Rohdaten anzeigen
end legend
----

<<<

=== Artikel

[plantuml, format=png, opts="inline"]
----
!include styles/tree-style.iuml
legend
Artikel
|_ Wareneingänge
  |_ Konfigurieren
  |_ Rohdaten anzeigen
|_ Artikel unter Meldebestand (Live)
  |_ Konfigurieren
  |_ Rohdaten anzeigen
|_ Listings (Live)
  |_ Konfigurieren
  |_ Rohdaten anzeigen
----

<<<

=== Messenger

[plantuml, format=png, opts="inline"]
----
!include styles/tree-style.iuml
legend
Messenger
|_ Nachrichten
  |_ Konfigurieren
  |_ Rohdaten anzeigen
end legend
----

<<<

=== Omni-Channel

[plantuml, format=png, opts="inline"]
----
!include styles/tree-style.iuml
legend
Omni-Channel
|_ Marktplatz-Variantenvalidierung
  |_ Konfigurieren
  |_ Rohdaten anzeigen
----

<<<

=== Aufträge

[plantuml, format=png, opts="inline"]
----
!include styles/tree-style.iuml
legend
Aufträge
|_ Ø Anzahl an Auftragspositionen
  |_ Konfigurieren
  |_ Rohdaten anzeigen
|_ Ø Bestellwert
  |_ Konfigurieren
  |_ Rohdaten anzeigen
|_ Global
  |_ Konfigurieren
  |_ Rohdaten anzeigen
|_ Global pro System
  |_ Konfigurieren
  |_ Rohdaten anzeigen
|_ Rohertrag
  |_ Konfigurieren
  |_ Rohdaten anzeigen
|_ Aufträge
  |_ Konfigurieren
  |_ Rohdaten anzeigen
|_ Aufträge (Live)
  |_ Konfigurieren
  |_ Rohdaten anzeigen
|_ Retourenquote
  |_ Konfigurieren
  |_ Rohdaten anzeigen
|_ Umsatz
  |_ Konfigurieren
  |_ Rohdaten anzeigen
|_ Absatz
  |_ Konfigurieren
  |_ Rohdaten anzeigen
|_ Versandumsatz
  |_ Konfigurieren
  |_ Rohdaten anzeigen
|_ Abonnement
  |_ Konfigurieren
  |_ Rohdaten anzeigen
|_ Umsatzsteuer gesamt
  |_ Konfigurieren
  |_ Rohdaten anzeigen

end legend
----

<<<

=== Zahlungen

[plantuml, format=png, opts="inline"]
----
!include styles/tree-style.iuml
legend
Zahlungen
|_ Zahlungen (Live)
  |_ Konfigurieren
  |_ Rohdaten anzeigen
----

<<<

=== Plugins

[plantuml, format=png, opts="inline"]
----
!include styles/tree-style.iuml
legend
Plugins
|_ Installierte Plugins
  |_ Konfigurieren
  |_ Rohdaten anzeigen
|_ Veröffentlichte Plugins
  |_ Konfigurieren
  |_ Rohdaten anzeigen
|_ Veröffentlichte Plugins pro Autor
  |_ Konfigurieren
  |_ Rohdaten anzeigen
end legend
----

<<<

=== Verbrauch

[plantuml, format=png, opts="inline"]
----
!include styles/tree-style.iuml
legend
Verbrauch
|_ Service-Verbrauch
  |_ Rohdaten anzeigen
|_ Verbrauch
  |_ Konfigurieren
  |_ Rohdaten anzeigen
end legend
----

<<<

== plentyWarehouse

[plantuml, format=png, opts="inline"]
----
!include styles/tree-style.iuml
legend
plentyWarehouse
|_ Rollende Kommisionierung
|_ Wareneingang
  |_ Warenbezugskosten
  |_ Einkaufspreis
|_ Lagerort inspizieren
  |_ Box lösen
|_ Artikelsuche
  |_ Barcode hinzufügen
|_ Auftragsinformationen
|_ Picklisten
|_ Drucken
  |_ Artikeletikett
  |_ Lagerort-Barcode
|_ Umbuchen
|_ Verräumen
|_ Einstellungen
|_ Einzelkommissionierung
|_ Bestandskorrektur
|_ Inventur
----

<<<<

== plentyBase-Einstellungen

In diesem Abschnitt werden die Berechtigungen für den Bereich plentyBase-Einstellungen aufgelistet.

[plantuml, format=png, opts="inline"]
----
!include styles/tree-style.iuml
legend
plentyBase-Einstellungen
|_ Bearbeiten
end legend
----

<<<

== Plugins

In diesem Abschnitt werden die Berechtigungen für den Bereich Plugins aufgelistet.

[plantuml, format=png, opts="inline"]
----
!include styles/tree-style.iuml
legend
Plugins
|_ Plugins
|_ Bereitstellen
|_ Konfigurationen
|_ Plugin-Dateien
|_ plentyMarketplace
|_ Versionierung
end legend
----

<<<

=== Bereitstellen
[plantuml, format=png, opts="inline"]
----
!include styles/tree-style.iuml
legend
Bereitstellen
|_ In Productive bereitstellen
|_ In Stage bereitstellen
end legend
----

<<<

=== Plugin-Dateien
[plantuml, format=png, opts="inline"]
----
!include styles/tree-style.iuml
legend
Plugin-Dateien
|_ Plugin-Dateien
|_ Hochladen
end legend
----

<<<

=== Versionierung
[plantuml, format=png, opts="inline"]
----
!include styles/tree-style.iuml
legend
Versionierung
  |_ Git
    |_ Repositories
      |_ Repositories
      |_ Branches
      |_ Repository-Einstellungen
        |_ Anzeigen
end legend
----

<<<

==== Branches
[plantuml, format=png, opts="inline"]
----
!include styles/tree-style.iuml
legend
Branches
  |_ Branches
  |_ Commits
    |_ Commits
    |_ Unterschiede  
  |_ Anfordern
  |_ Pullen
  |_ Pushen
  |_ Konflikte beheben
end legend
----

<<<

== POS

In diesem Abschnitt werden die Berechtigungen für den Bereich POS aufgelistet.

[plantuml, format=png, opts="inline"]
----
!include styles/tree-style.iuml
legend
POS
|_ POS
|_ Einstellungen bearbeiten
|_ Favoriten
end legend
----

<<<

== Prozesse (Veraltet)

In diesem Abschnitt werden die Berechtigungen für den Bereich Prozesse aufgelistet.

[plantuml, format=png, opts="inline"]
----
!include styles/tree-style.iuml
legend
Prozesse
|_ Prozesse (Veraltet)
|_ Bearbeiten (Veraltet)
end legend
----

<<<

== Service

In diesem Abschnitt werden die Berechtigungen für den Bereich Service aufgelistet.

[plantuml, format=png, opts="inline"]
----
!include styles/tree-style.iuml
legend
Service
|_ Hotline
end legend
----

<<<

== Service-Center

In diesem Abschnitt werden die Berechtigungen für den Bereich Service-Center aufgelistet.

[plantuml, format=png, opts="inline"]
----
!include styles/tree-style.iuml
legend
Service-Center
end legend
----

<<<

== Einrichtung

In diesem Abaschnitt werden die Berechtigungen für den Bereich Einrichtung aufgelistet.

[plantuml, format=png, opts="inline"]
----
!include styles/tree-style.iuml
legend
Einrichtung
|_ Assistenten
|_ Sprache
|_ Eigenschaft
|_ Tag
  |_ Tag
  |_ Tag-Verknüpfung
end legend
----

<<<

=== Assistenten

[plantuml, format=png, opts="inline"]
----
!include styles/tree-style.iuml
legend
Assistenten
|_ Assistenten
|_ Datensatz
  |_ Datensatz
  |_ Abschließen
end legend
----

<<<

=== Sprache

[plantuml, format=png, opts="inline"]
----
!include styles/tree-style.iuml
legend
Sprache
|_ Sprachumgebung
  |_ Konfigurieren
end legend
----

<<<

=== Eignerschaft

[plantuml, format=png, opts="inline"]
----
!include styles/tree-style.iuml
legend
Eignerschaft
|_ Eignerschaft
|_ Amazon-Eigenschaftsverknüpfung
|_ Verfügbarkeit
|_ Gruppe
  |_ Gruppe
  |_ Gruppenoptionen
|_ Markt
|_ Name
|_ Optionen
|_ Verknüpfung
  |_ Verknüpfung
  |_ Verknüpfungswert
|_ Auswahl
end legend
----

<<<

== Start

In diesem Abschnitt werden die Berechtigungen für den Bereich Start aufgelistet.

[plantuml, format=png, opts="inline"]
----
!include styles/tree-style.iuml
legend
Start
|_ Boards
|_ Kalender
|_ Dashboard
|_ Aufgaben
end legend
----

<<<

== Warenbestände

In diesem Abschnitt werden die Berechtigungen für den Bereich Warenbestände aufgelistet.

[plantuml, format=png, opts="inline"]
----
!include styles/tree-style.iuml
legend
Warenbestände
|_ Warenbestände
|_ Rückstandsliste
|_ Bearbeiten
|_ Externe Warenwirtschaft
|_ Wareneingänge
|_ Neuer Wareneingang
|_ Nachbestellung
|_ Auftragsbezogene Rückstandsliste
|_ Retoure
|_ Lager
|_ Lagerort-Verwaltung
end legend
----

<<<

=== Externe Warenwirtschaft

[plantuml, format=png, opts="inline"]
----
!include styles/tree-style.iuml
legend
Externe Warenwirtschaft
|_ Mention
  |_ Bearbeiten
end legend
----

<<<

=== Wareneingänge

[plantuml, format=png, opts="inline"]
----
!include styles/tree-style.iuml
legend
Wareneingänge
|_ Wareneingänge
|_ Eignerschaft
end legend
----

<<<

=== Nachbestellung

[plantuml, format=png, opts="inline"]
----
!include styles/tree-style.iuml
legend
Nachbestellung
|_ Nachbestellung
|_ Bearbeiten
end legend
----

<<<

=== Lager

[plantuml, format=png, opts="inline"]
----
!include styles/tree-style.iuml
legend
Lager
|_ Lageradresse
|_ Bearbeiten
|_ Lagerort
  |_ Lagerort
  |_ Lagerortdimension
  |_ Inventur
    |_ Inventur
    |_ Zählprotokoll
  |_ Lagerortebene
end legend
----

<<<

== plentymarkets Systeme

In diesem Abschnitt werden die Berechtigungen für den Bereich plentymarkets Systeme aufgelistet.

[plantuml, format=png, opts="inline"]
----
!include styles/tree-style.iuml
legend
plentymarkets Systeme
|_ plentymarkets Systeme
|_ Vertrag
|_ Customer crawler
|_ Domain
|_ Sprache
|_ Server
|_ Server-Update
|_ Einstellungen
|_ plentymarkets Status
|_ Mandant
end legend
----

<<<

=== Sprache

[plantuml, format=png, opts="inline"]
----
!include styles/tree-style.iuml
legend
Sprache
|_ Bearbeiten
end legend
----

<<<

=== Server

[plantuml, format=png, opts="inline"]
----
!include styles/tree-style.iuml
legend
Server
|_ Server
|_ Ändern
end legend
----

<<<

=== Einstellungen

[plantuml, format=png, opts="inline"]
----
!include styles/tree-style.iuml
legend
Einstellungen
|_ Bearbeiten
end legend
----

<<<

== Vorlage

In diesem Abschnitt werden die Berechtigungen für den Bereich Vorlage aufgelistet.

[plantuml, format=png, opts="inline"]
----
!include styles/tree-style.iuml
legend
Vorlage
|_ Design
  |_ Bearbeiten
end legend
----

<<<

== Benutzer

In diesem Abschnitt werden die Berechtigungen für den Bereich Benutzer aufgelistet.

[plantuml, format=png, opts="inline"]
----
!include styles/tree-style.iuml
legend
Benutzer
|_ Konfigurieren
end legend
----

<<<