= Editionsübersicht

Aktuell ist PlentyONE in den Editionen *CLASSIC* und *ENTERPRISE* verfügbar. Diese Editionen werden im Folgenden detailliert aufgeschlüsselt.

In allen Editionen stehen integrale und optionale Module zur Verfügung. Integrale Module sind Module, die von Anfang an im Funktionsumfang des jeweiligen Systems enthalten sind. Optionale Module können zusätzlich gewählt werden und gehören dann ebenfalls zum Funktionsumfang des Systems. Die integralen und optionalen Module unterscheiden sich je nach Tarif. Das Modul *POS* ist immer optional und muss bei beiden Tarifen separat hinzugebucht werden.

== CLASSIC

In der Edition *CLASSIC* sind die folgenden Module integral:

* plentyChannel (Vertrieb auf Online-Marktplätzen und Preisvergleichsseiten)
* Webshop
* Auftragsabwicklung
* Warenwirtschaft
* CRM
* Payment
* Fulfillment
* Prozesse
* Cloud-Hosting (SaaS)

Zusätzlich ist die Nutzung folgender Leistungen inklusive:

* ShopBuilder
* ShopBooster
* Facettensuche
* Rest-API
* Forensupport
* Software-Updates

Benutzerlizenzen, Vertriebslager, Mandanten und Kassen können bis zu den in Tabelle 1 aufgeführten maximalen Anzahlen hinzugebucht werden.

.Optionen in der Edition CLASSIC
[cols="1,3"]
|====
|Option |CLASSIC

|Laufzeit
|1-12 Monate

|Benutzerlizenzen
|20 inklusive / maximal 50

|Vertriebslager
|3 inklusive / maximal 25

|Mandanten
|1 inklusive / maximal 15

|POS / Kassen
|bis zu 25 Kassen zubuchbar

|plentyBI
|XS kostenlos inkludiert; plentyBI S, M oder L separat buchbar

|====

== ENTERPRISE

Die Edition *ENTERPRISE* wird auf Anfrage von Anwendern auf die individuellen Bedürfnisse des Betriebs abgestimmt. Somit ist es nicht möglich, allgemeingültige Aussagen zu maximal verfügbaren Mandanten, Vertriebslagern und weiteren Ressourcen zu treffen. Die Edition *ENTERPRISE* kann nur über vorherige link:https://www.plentyone.com/de/kontakt/[Kontaktaufnahme zu PlentyONE] gebucht werden und beinhaltet typischerweise umfangreiche, individuell auf Anwender zugeschnittene Services und diverse Zusatzleistungen. Es liegt in der Pflicht des Anwenders, inkludierte Leistungen an Beispiel von Tabelle 1 für die Edition *ENTERPRISE* aufzulisten.

== plentyBI

Das Produkt *plentyBI* muss unter Umständen separat gebucht werden. Das Produkt *plentyBI XS* ist in allen PlentyONE Editionen verfügbar und bei Buchung eines PlentyONE Systems automatisch inkludiert. Desweiteren stehen folgende plentyBI Editionen zur Verfügung:

* *plentyBI S*
* *plentyBI M*
* *plentyBI L*

Die Editionen unterscheiden sich anhand folgender Werte:

* Maximale Anzahl an Kennzahlkonfigurationen, die von Anwendern erstellt werden können
* Verfügbare Kennzahlen
* Verfügbare Dimensionen für Kennzahlkonfigurationen
* Alter der verfügbaren Rohdaten
* Speicherdauer der berechneten Ergebnisse

Das Alter der verfügbaren Rohdaten, die Speicherdauer der berechneten Ergebnisse und die maximale Anzahl an erstellbaren Kennzahlkonfigurationen der verschiedenen Editionen können folgender Tabelle entnommen werden:

.Informationen zur Datenspeicherung
[cols="1,3,3,3"]
|===
|plentyBI
|Alter verfügbarer Rohdaten (Monate)
|Speicherdauer der Ergebnisse (Monate)
|Maximale Anzahl an Kennzahlkonfigurationen (Stück)

|XS
|6
|12
|2

|S
|12
|24
|15

|M
|24
|36
|30

|L
|48
|120
|100

|===

== Hosting-Optionen

Bei der Buchung von PlentyONE muss _eine_ der von PlentyONE angebotenen Hosting-Optionen ausgewählt werden. Die folgenden Hosting-Optionen in Form von Server-Standorten stehen hierbei zur Verfügung:

 * AWS Dublin
 * AWS Frankfurt

Die Speicherung und Sicherung von Daten findet ausschließlich am ausgewählten Server-Standort statt. Die Sicherung von Daten in Form von Backups findet ausdrücklich _nur_ am gewählten Server-Standort und niemals an weiteren Standorten statt.

Weitere Informationen zu den einzelnen Hosting-Optionen werden im Kapitel <<#_aws_cloud_aufbau_sicherheitsarchitektur_speicherkonzept_löschkonzept>> beschrieben.
