= Editionsübersicht

Aktuell ist plentysystems in den Editionen *BASIC*, *CLASSIC* und *PLUS*, *FLEX* und *ENTERPRISE* verfügbar. Diese Editionen werden im Folgenden detailliert aufgeschlüsselt.

In allen Editionen stehen integrale und optionale Module zur Verfügung. Integrale Module sind Module, die von Anfang an im Funktionsumfang des jeweiligen Systems enthalten sind. Optionale Module können zusätzlich gewählt werden und gehören dann ebenfalls zum Funktionsumfang des Systems. Die integralen und optionalen Module unterscheiden sich je nach Tarif.

== plentysystems BASIC

In der Edition *plentysystems BASIC* sind die folgenden Module integral:

* plentyChannel (Vertrieb auf Online-Marktplätzen und Preisvergleichsseiten)
* Webshop
* Auftragsabwicklung
* Warenwirtschaft
* CRM
* Payment
* Fulfillment
* Prozesse
* Cloud-Hosting (SaaS)

Zusätzlich ist die Nutzung folgender Leistungen inklusive:

* ShopBuilder
* ShopBooster
* Facettensuche
* Rest-API
* Forensupport
* Software-Updates

Das Modul *POS* ist immer optional und muss separat hinzugebucht werden. +
Benutzerlizenzen, Vertriebslager, Mandanten und Kassen können bis zu den in Tabelle 1 aufgeführten maximalen Anzahlen hinzugebucht werden.

.Optionen in der Edition plentysystems BASIC
[cols="1,3"]
|====
|Option |BASIC

|Laufzeit
|1 Monat

|Benutzerlizenzen
|5 inklusive / maximal 5

|Vertriebslager
|3 inklusive / maximal 3

|Mandanten
|1 inklusive / maximal 3

|POS / Kassen
|bis zu 5 Kassen zubuchbar

|plentyBI
|XS verfügbar / maximal S

|====

== plentysystems CLASSIC

In der Edition *plentysystems CLASSIC* sind die folgenden Module integral:

* plentyChannel (Vertrieb auf Online-Marktplätzen und Preisvergleichsseiten)
* Webshop
* Auftragsabwicklung
* Warenwirtschaft
* CRM
* Payment
* Fulfillment
* Prozesse
* Cloud-Hosting (SaaS)

Zusätzlich ist die Nutzung folgender Leistungen inklusive:

* ShopBuilder
* ShopBooster
* Facettensuche
* Rest-API
* Forensupport
* Software-Updates

Das Modul *POS* ist immer optional und muss bei beiden Tarifen separat hinzugebucht werden. +
Benutzerlizenzen, Vertriebslager, Mandanten und Kassen können bis zu den in Tabelle 2 aufgeführten maximalen Anzahlen hinzugebucht werden.

.Optionen in der Edition plentysystems CLASSIC
[cols="1,3"]
|====
|Option |CLASSIC

|Laufzeit
|1-12 Monate

|Benutzerlizenzen
|20 inklusive / maximal 50

|Vertriebslager
|3 inklusive / maximal 25

|Mandanten
|1 inklusive / maximal 15

|POS / Kassen
|bis zu 25 Kassen zubuchbar

|plentyBI
|XS verfügbar / maximal L

|====

In der Tarifgruppe Classic können zusätzlich Auftragspakete gebucht werden. Folgende Auftragspakete stehen zu Verfügung:

* 500 Aufträge
* 5.000 Aufträge
* 10.000 Aufträge
* 50.000 Aufträge

Auftragspakete können für einen Zeitraum von 3 Monaten, 6 Monaten oder 12 Monaten gebucht und beliebig kombiniert werden.

== plentysystems FLEX

In der Edition *plentysystems FLEX* sind die folgenden Module integral:

* plentyChannel (Vertrieb auf Online-Marktplätzen und Preisvergleichsseiten)
* Webshop
* Auftragsabwicklung
* Warenwirtschaft
* CRM
* Payment
* Fulfillment
* Prozesse
* Cloud-Hosting (SaaS)

Zusätzlich ist die Nutzung folgender Leistungen inklusive:

* ShopBuilder
* ShopBooster
* Facettensuche
* Rest-API
* Forensupport
* Software-Updates

Das Modul *POS* ist immer optional und muss bei beiden Tarifen separat hinzugebucht werden. +
Benutzerlizenzen, Vertriebslager, Mandanten und Kassen können bis zu den in Tabelle 2 aufgeführten maximalen Anzahlen hinzugebucht werden.

.Optionen in der Edition plentysystems FLEX
[cols="1,3"]
|====
|Option |FLEX

|Laufzeit
|6 Monate

|Benutzerlizenzen
|30 inklusive / maximal 100

|Vertriebslager
|5 inklusive / maximal 40

|Mandanten
|1 inklusive / maximal 30

|POS / Kassen
|bis zu 99 Kassen zubuchbar

|plentyBI
|XS verfügbar / maximal L

|====

== plentysystems PLUS

In der Edition *plentysystems PLUS* sind folgenden Module integral:

* plentyChannel (Vertrieb auf Online-Marktplätzen und Preisvergleichsseiten)
* Webshop
* Auftragsabwicklung
* Warenwirtschaft
* CRM
* Payment
* Fulfillment
* Prozesse
* Cloud-Hosting (SaaS)

Zusätzlich ist die Nutzung folgender Leistungen inklusive:

* ShopBuilder
* ShopBooster
* Facettensuche
* Rest-API
* Forensupport
* Software-Updates

Das Modul *POS* ist immer optional und muss bei beiden Tarifen separat hinzugebucht werden. +
Benutzerlizenzen, Vertriebslager, Mandanten und Kassen können bis zu den in Tabelle 3 aufgeführten maximalen Anzahlen hinzugebucht werden.

.Optionen in der Edition plentysystems PLUS
[cols="1,3"]
|====
|Option |PLUS

|Laufzeit
|12 Monate

|Benutzerlizenzen
|60 inklusive / maximal 200

|Vertriebslager
|10 inklusive / maximal 60

|Mandanten
|3 inklusive / maximal 50

|POS / Kassen
|bis zu 99 Kassen zubuchbar

|plentyBI
|XS verfügbar / maximal L

|====

== plentysystems ENTERPRISE

In der Edition *plentysystems ENTERPRISE* sind folgenden Module integral:

* plentyChannel (Vertrieb auf Online-Marktplätzen und Preisvergleichsseiten)
* Webshop
* Auftragsabwicklung
* Warenwirtschaft
* CRM
* Payment
* Fulfillment
* Prozesse
* Cloud-Hosting (PaaS)

Zusätzlich ist die Nutzung folgender Leistungen inklusive:

* ShopBuilder
* ShopBooster
* Facettensuche
* Rest-API
* Forensupport
* Software-Updates

Das Modul *POS* ist immer optional und muss bei beiden Tarifen separat hinzugebucht werden. +
Benutzerlizenzen, Vertriebslager, Mandanten und Kassen können bis zu den in Tabelle 3 aufgeführten maximalen Anzahlen hinzugebucht werden.

.Optionen in der Edition plentysystems ENTERPRISE
[cols="1,3"]
|====
|Option |ENTERPRISE

|Laufzeit
|24 Monate

|Benutzerlizenzen
|60 inklusive / maximal 200

|Vertriebslager
|10 inklusive / maximal 60

|Mandanten
|3 inklusive / maximal 50

|POS / Kassen
|bis zu 99 Kassen zubuchbar

|plentyBI
|XS verfügbar / maximal L

|====

== plentyBI

Das Produkt *plentyBI* muss separat gebucht werden. Das Produkt *plentyBI XS* ist in allen Tarifen verfügbar. Je nach Tarif, können folgende Produkte gebucht werden:

* *plentyBI S*
* *plentyBI M*
* *plentyBI L*

Die Produkte unterscheiden sich anhand folgender Werte:

* Maximale Anzahl an Kennzahlenkonfigurationen, die gleichzeitig ausgelesen werden können
* Verfügbare Kennzahlen
* Alter der verfügbaren Rohdaten
* Speicherdauer der berechneten Ergebnisse

Um eine bestimmte Kennzahl auszulesen, werden Rohdaten benötigt. Weitere Informationen sind auf der Handbuchseite link:https://knowledge.plentymarkets.com/business-entscheidungen/business-intelligence/reports/reports-verwalten#_datenformat_creator[Reports verwalten^] zu finden.

Das Alter der verfügbaren Rohdaten und die Speicherdauer der berechneten Ergebnisse in den verschiedenen Produkten können folgender Tabelle entnommen werden:

.Informationen zur Datenspeicherung
[cols="1,3,3"]
|===
|plentyBI
|Alter Rohdaten (Monate)
|Speicherdauer Ergebnisse (Monate)

|XS
|6
|12

|S
|12
|24

|M
|24
|36

|L
|48
|120

|===

== plentysystems PARTNER

Die Edition *plentysystems PARTNER* kann nur von zertifizierten plentysystems Partnern gebucht werden. Die folgenden Module sind in der Edition integral:

* plentyChannel (Vertrieb auf Online-Marktplätzen und Preisvergleichsseiten)
* Webshop
* Auftragsabwicklung
* Warenwirtschaft
* CRM
* Payment
* Fulfillment
* Prozesse
* Cloud-Hosting (SaaS)

Zusätzlich ist die Nutzung folgender Leistungen inklusive:

* ShopBuilder
* ShopBooster
* Facettensuche
* Rest-API
* Forensupport
* Software-Updates

Benutzerlizenzen, Vertriebslager, Mandanten und Kassen können bis zu den in Tabelle 4 aufgeführten maximalen Anzahlen hinzugebucht werden.

.Optionen in der Edition *plentysystems PARTNER*
[cols="1,3"]
|====
|Option *plentysystems PARTNER*

|Benutzerlizenzen
|6 inklusive

|Vertriebslager
|5 inklusive

|Mandanten
|1 inklusive

|POS / Kassen
|maximal 5

|====

Partner können außerdem Plugins und Dienstleistungen auf plentyMarketplace anbieten.

== Hosting-Optionen

Jeder Anwender muss _eine_ der von plentysystems angebotenen Hosting-Optionen wählen. Die folgenden Hosting-Optionen in Form von Server-Standorten stehen hierbei zur Verfügung:

 * AWS Dublin
 * AWS Frankfurt

Die Speicherung und Sicherung von Daten findet ausschließlich am ausgewählten Server-Standort statt. Die Sicherung von Daten in Form von Backups findet ausdrücklich _nur_ am gewählten Server-Standort und niemals an weiteren Standorten statt.

Weitere Informationen zu den einzelnen Hosting-Optionen werden im Kapitel <<#_aws_cloud_aufbau_sicherheitsarchitektur_speicherkonzept_löschkonzept>> beschrieben.
