
== Allgemeine fachliche Beschreibung der Software plentymarkets

plentymarkets dient insbesondere der Verwaltung und Abwicklung von Daten und Arbeitsabläufen, die im Zusammenhang mit dem Handel von Sachgütern, digitalen Gütern und immateriellen Gütern stehen. Hierbei kommen die genannten Module zum Einsatz. Die Vorteile beim Einsatz von plentymarkets liegen insbesondere darin, dass Artikelinformationen zentral in plentymarkets erfasst und verwaltet werden und von hier aus an verschiedene Kanäle für den Verkauf übermittelt werden. Des Weiteren liegen Vorteile darin, dass egal über welchen Kanal ein Artikel verkauft wurde, nach dem Verkauf eine Übermittlung der Auftrags- und Kundendaten an das plentymarkets System des Anwenders erfolgt, sodass die anschließende Abwicklung wieder zentral im plentymarkets System des Anwenders erfolgt. Ein weiterer Vorteil liegt in der Möglichkeit diese Abwicklung bis zu einem hohen Grad zu automatisieren. +
Als Verkaufskanäle kommen Marktplätze oder Vergleichsportale aus dem Modul Multi-Channel, Kassen aus dem Modul POS, eigene Online-Shops sowie über Plugins angebundene Kanäle infrage. Der Anwender entscheidet, welche Verkaufskanäle genutzt werden, sodass sich die verwendeten Kanäle für jeden Anwender unterscheiden.  +
Der Grad der Automatisierung wird durch den Anwender selbst bestimmt und unterscheidet sich deshalb ebenfalls für jeden Anwender. Die Bearbeitung und Abwicklung eines Auftrags bis hin zum Versand kann also komplett manuell oder automatisiert erfolgen. Manuell bedeutet, dass jeder einzelne Vorgang explizit durch einen Benutzer angestoßen wird. Automatisiert bedeutet, dass plentymarkets anhand eigens durch den Anwender festgelegter Kriterien Aktionen ausführt, die zuvor ebenfalls durch den Anwender festgelegt und aktiviert wurden. Das System führt die Aktionen also bei Zutreffen der Kriterien lediglich aus.  +
Einige Aktionen erfolgen jedoch auch automatisch durch das System und können nicht durch den Anwender beeinflusst werden. Hierbei handelt es sich um sogenannte Systemautomatismen. Welche Systemautomatismen es gibt, wird später im Text erläutert.

Bei Bestellung eines plentymarkets Systems erhält der Anwender Login-Daten, mit denen er sich als Benutzer in sein System einloggen kann. Was Benutzer sind und was sie dürfen, wird zunächst beschrieben.
Anschließend werden die Module einzeln genauer beschrieben.

=== Fachliche und technische Beschreibung Benutzer und Benutzerrechte

Benutzer sind die Personen, die die Software plentymarkets bedienen. Die Benutzerrechte dienen dazu einem Benutzer den Zugriff zu Bereichen oder Menüs der Software zu ermöglichen, zu beschränken oder zu verwehren. +
Die Benutzerrechte eines Benutzer in plentymarkets hängen zunächst von seiner Benutzerklasse ab. Jedem Benutzer muss eine Benutzerklasse zugeordnet werden. Die Benutzerklassen sind systemseitig vorgegeben und können durch die Anwender nicht geändert werden. +
Folgende Benutzerklassen gibt es in plentymarkets:

 * Admin
 * Variabel
 * Callcenter
 * API
 * Logistik
 * Blog
 * Newsletter2Go

Jede Benutzerklasse ist mit unterschiedlichen Rechten versehen, die in den folgenden Kapiteln näher beschrieben werden. Die Vergabe von Rechten wird detailliert im Handbuch beschrieben: https://knowledge.plentymarkets.com/basics/arbeiten-mit-plentymarkets/benutzer-verwalten#90[https://knowledge.plentymarkets.com/basics/arbeiten-mit-plentymarkets/benutzer-verwalten#90] +
Außerdem können optional Benutzerrollen angelegt werden. Mithilfe von Benutzerrollen lassen sich Rechte für mehrere Benutzer gleichzeitig vergeben. Die Benutzer müssen dafür der Rolle zugeordnet werden.

==== Benutzerklasse Admin

Die Benutzerklasse Admin verfügt über alle Rechte und dient zur Verwaltung des Systems. Benutzern dieser Klasse können keine Rechte zusätzlich gewährt oder verwehrt werden. Sie verfügen pauschal über alle Rechte.

==== Benutzerklasse Variabel

Die Benutzerklasse Variabel verfügt standardmäßig über keine Rechte und bietet die größte Möglichkeit der individuellen Zuordnung von Rechten. Die 

==== Benutzerklasse Callcenter

Die Benutzerklasse Callcenter ist eine stark eingeschränkte Klasse. Sie hat standardmäßig Zugriffsrechte auf nur wenige Menüpunkte der Softwareoberflächer und Benutzern dieser Klasse können auch keine weiteren Menüpunkte freigegeben werden. Der Zugriff auf folgende Menübereiche ist freigegeben:
 * Dashboard des Anwendersystems
 * Kalender
 * Auftragsbearbeitung
 * Kundenbearbeitung inkl. Ticketsystem
Im Menübereich Kalender kann ein Benutzer der Klasse Callcenter lediglich seinen eigenen Kalender pflegen. Kalender von anderen Benutzer kann er nur sehen sowie bearbeiten, wenn diese es ihm erlauben. +
Standardmäßig ist kein Mandant freigegeben, so dass in keinem der weiteren Menübereiche tatsächlich Daten angezeigt werden. Des Weiteren sind standardmäßig keine Auftragsstatus sichtbar oder setzbar. Erst die Freigabe eines Mandanten für einen Benutzer der Klasse Callcenter erlaubt den tatsächlichen Zugriff auf Kundendaten und das Ticketsystem. Für den Zugriff auf Auftragsdaten muss zusätzlich zu einem Mandanten mindestens die Freigabe der Sichtbarkeit eines Auftragsstatus erfolgen.

==== Benutzerklasse API

Die Benutzerklasse API dient dem Datenaustausch über eine von plentymarkets zur Verfügung gestellte API-Technologie. Folgende API-Technologien stehen zur Verfügung:

 * SOAP
 * REST

Standardmäßig sind jedoch keine Zugriffsrechte für SOAP oder REST aktiviert. Es besteht lediglich die Möglichkeit einem Benutzer der Klasse API Zugriff per SOAP oder REST auf Daten des Systems zu gewähren. Ein API-Benutzer hat keinen Zugriff auf Daten über die Softwareoberfläche. +
Die SOAP API wird seit einiger Zeit nicht mehr weiterentwickelt, so dass sie technisch nicht mehr in allen Bereichen kompatibel ist mit der Datenstruktur von plentymarkets. Die REST API löst die SOAP API ab und stellt die neuere Technologie dar.  +
Eine detaillierte Beschreibung der SOAP-Schnittstelle findet sich unter folgendem Link: +
https://cdn02.plentymarkets.com/pmsbpnokwu6a/plugin/production/plentymanual/images/basics/assets/SOAP-Version-200-Documentation-2016-07-14.zip[https://cdn02.plentymarkets.com/pmsbpnokwu6a/plugin/production/plentymanual/images/basics/assets/SOAP-Version-200-Documentation-2016-07-14.zip] +
Eine detaillierte Beschreibung der REST-Schnittstelle findet sich unter folgender Adresse: +
https://developers.plentymarkets.com/[https://developers.plentymarkets.com/]

==== Benutzerklasse Logistik

Die Benutzerklasse Logistik hat über die Softwareoberfläche Zugriff auf folgende Bereiche:

 * Startseite
 * Kalender
 * Warenbestände suchen und bearbeiten
 * Wareneingänge suchen und bearbeiten
 * Warenberechnung
 * Datenimport und -export
 * Lagerort-Verwaltung
 * Aufträge suchen und bearbeiten
 * Fulfillment

==== Benutzerklasse Blog

Die Benutzerklasse Blog dient dazu einem Benutzer zu ermöglichen Blogbeiträge zu erstellen. Die Klasse hat Berechtigungen für folgende Bereiche:
 * Startseite
 * Kalender
 * Blog
Der Zugriff auf den Kalender bezieht sich lediglich auf den benutzereigenen Kalender. Kalender anderer Benutzer müssen durch diese zur Ansicht oder Bearbeitung freigegeben werden.

==== Benutzerklasse Newsletter2Go

Benutzerklasse, die automatisch für die Einrichtung einer link:https://knowledge.plentymarkets.com/crm/newsletter-versenden#2100[*Newsletter2Go*]-Schnittstelle verwendet wird.