
== Allgemeine fachliche Beschreibung der Software plentymarkets

plentymarkets dient insbesondere der Verwaltung und Abwicklung von Daten und Arbeitsabläufen, die im Zusammenhang mit dem Handel von Sachgütern, digitalen Gütern und immateriellen Gütern stehen. Hierbei kommen die genannten Module zum Einsatz. Die Vorteile beim Einsatz von plentymarkets liegen insbesondere darin, dass Artikelinformationen zentral in plentymarkets erfasst und verwaltet werden und von hier aus an verschiedene Kanäle für den Verkauf übermittelt werden. Des Weiteren liegen Vorteile darin, dass egal über welchen Kanal ein Artikel verkauft wurde, nach dem Verkauf eine Übermittlung der Auftrags- und Kundendaten an das plentymarkets System des Anwenders erfolgt, sodass die anschließende Abwicklung wieder zentral im plentymarkets System des Anwenders erfolgt. Ein weiterer Vorteil liegt in der Möglichkeit, diese Abwicklung bis zu einem hohen Grad zu automatisieren. +
Als Verkaufskanäle kommen Marktplätze oder Vergleichsportale aus dem Modul Multi-Channel, Kassen aus dem Modul POS, eigene Online-Shops sowie über Plugins angebundene Kanäle infrage. Der Anwender entscheidet, welche Verkaufskanäle genutzt werden, sodass sich die verwendeten Kanäle für jeden Anwender unterscheiden.  +
Der Grad der Automatisierung wird durch den Anwender selbst bestimmt und unterscheidet sich deshalb ebenfalls für jeden Anwender. Die Bearbeitung und Abwicklung eines Auftrags bis hin zum Versand kann also komplett manuell oder automatisiert erfolgen. Manuell bedeutet, dass jeder einzelne Vorgang explizit durch einen Benutzer angestoßen wird. Automatisiert bedeutet, dass plentymarkets anhand eigens durch den Anwender festgelegter Kriterien Aktionen ausführt, die zuvor ebenfalls durch den Anwender festgelegt und aktiviert wurden. Das System führt die Aktionen also bei Zutreffen der Kriterien lediglich aus.  +
Einige Aktionen erfolgen jedoch auch automatisch durch das System und können nicht durch den Anwender beeinflusst werden. Hierbei handelt es sich um sogenannte Systemautomatismen. Welche Systemautomatismen es gibt, wird später im Text erläutert.

Bei Bestellung eines plentymarkets Systems erhält der Anwender Login-Daten, mit denen er sich als Benutzer in sein System einloggen kann. Was Benutzer sind und was sie dürfen, wird zunächst beschrieben.
Anschließend werden die Module einzeln genauer beschrieben.

=== Fachliche und technische Beschreibung Benutzer und Benutzerrechte

Benutzer sind die Personen, die die Software plentymarkets bedienen. Die Benutzerrechte dienen dazu, einem Benutzer den Zugriff zu Bereichen oder Menüs der Software zu ermöglichen, zu beschränken oder zu verwehren. Benutzerrechte heißen in plentymarkets Berechtigungen. +
Die Benutzerrechte eines Benutzer in plentymarkets hängen zunächst von seinem Benutzerzugang ab. Jedem Benutzer muss ein Benutzerzugang zugeordnet werden. Die Benutzerzugänge sind systemseitig vorgegeben und können durch die Anwender nicht geändert werden. +

==== Benutzerzugänge

Folgende Benutzerzugänge gibt es in plentymarkets:

 * Admin
 * Backend
 * REST-API

Jeder Benutzerzugang ist mit unterschiedlichen Rechten versehen, die in den folgenden Kapiteln näher beschrieben werden. Die Vergabe von Rechten wird detailliert im Handbuch beschrieben: https://knowledge.plentymarkets.com/basics/arbeiten-mit-plentymarkets/benutzer-verwalten#90[https://knowledge.plentymarkets.com/basics/arbeiten-mit-plentymarkets/benutzer-verwalten#90] +
Außerdem können optional Benutzerrollen angelegt werden. Mithilfe von Benutzerrollen lassen sich Rechte für mehrere Benutzer gleichzeitig vergeben. Die Benutzer müssen dafür der Rolle zugeordnet werden.

===== Benutzerzugang Admin

Der Benutzerzugang Admin verfügt über alle Rechte und dient zur Verwaltung des Systems. Benutzern dieses Zugangs können keine Rechte zusätzlich gewährt oder verwehrt werden. Sie verfügen pauschal über alle Rechte.

===== Benutzerzugang Backend

Der Benutzerzugang Backend verfügt standardmäßig über keine Rechte und bietet die größte Möglichkeit der individuellen Zuordnung von Rechten, die im Tab Berechtigung freitgeschaltet werden können.

===== Benutzerzugang REST-API

Für den Benutzerzugang REST-API können im Benutzerkonto REST-Calls freigeschaltet werden. Diese werden einzeln aktiviert. *Achtung*: Nutzern mit diesem Benutzerzugang wird der Zugriff auf das Backend verweigert.

Standardmäßig sind jedoch keine Zugriffsrechte für REST aktiviert. Es besteht lediglich die Möglichkeit, einem Benutzer des Zugangs REST-API per REST Zugriff auf Daten des Systems zu gewähren. Ein REST-API-Benutzer hat keinen Zugriff auf Daten über die Softwareoberfläche. +
Eine detaillierte Beschreibung der REST-Schnittstelle findet sich unter folgender Adresse: +
https://developers.plentymarkets.com/[https://developers.plentymarkets.com/]

==== Rechte vergeben

Die Benutzerrechte in plentymarkets sind in die folgenden Bereiche unterteilt:

* Berechtigungen
* Menü-Sichtbarkeiten
* Plugins

Die Bereiche Berechtigungen und Menü-Sichtbarkeiten sind verknüpft, wodurch die gewählten Rechte für den jeweils anderen Bereich automatisch mit aktiviert werden.

Beim Vergeben von Berechtigungen gilt generell, dass das Aktivieren einer Berechtigung einer übergeordneten Ebene alle darunter liegenden Berechtigungen aktiviert. Das Entfernen einer Berechtigung einer übergeordneten Ebene entfernt analog alle darunter einsortieren Berechtigungen.

==== Liste der Admin- und Backend-Benutzer

Ergänzen Sie in der folgenden Tabelle, welche Personen über welchen Zugriff verfügen.

Folgende Personen sind Admin-Benutzer und verfügen über uneingeschränkten Zugriff auf das plentymarkets System

Person 1: (_Name, Vorname; ggf. Personalnummer, Organisationseinheit, Funktion im Unternehmen_) +
Person 2: (_Name, Vorname; ggf. Personalnummer, Organisationseinheit, Funktion im Unternehmen_) +
Person 3: (_Name, Vorname; ggf. Personalnummer, Organisationseinheit, Funktion im Unternehmen_)

Folgende Personen sind Backend-Benutzer und verfügen über eingeschränkten Zugriff auf das plentymarkets System:

Person 1: (_Name, Vorname; ggf. Personalnummer, Organisationseinheit, Funktion im Unternehmen_) +
Person 2: (_Name, Vorname; ggf. Personalnummer, Organisationseinheit, Funktion im Unternehmen_) +
Person 3: (_Name, Vorname; ggf. Personalnummer, Organisationseinheit, Funktion im Unternehmen_)

===== Berechtigungen

Mithilfe der Berechtigungen wird festgelegt welche tatsächlichen Daten ein Benutzer sieht. +
Die Sichtbarkeiten sind in 5 Abschnitte unterteilt, die in der folgenden Tabelle aufgeführt und erläutert sind.


[[tabelle-sichtbarkeiten]]
.Sichtbarkeiten in plentymarkets
|====
|*Sichtbarkeiten* |*Erläuterung*

|*Lager*
|Die Lager sind einzeln wählbar unterteilt nach Lagertypen.

|*Sichtbare Auftragsstatus*
|Die Auftragsstatus sind einzeln wählbar. Zur Auswahl stehen alle 29 Standard-Auftragsstatus sowie alle eigenen.

|*Setzbare Auftragsstatus*
|Die Auftragsstatus sind einzeln wählbar. Zur Auswahl stehen alle 29 Standard-Auftragsstatus sowie alle durch den Anwender eingetragenen Status.

|*Mandanten*
|Die Mandanten sind einzeln wählbar.

|*Ticketstatus*
|Die Ticketstatus sind einzeln wählbar. Zur Auswahl stehen alle durch den Anwender angelegten Ticketstatus.
|====

*_Hinweis_*: Die dort aufgeführten Sichtbarkeiten werden bald in das Menü *Einrichtung » Einstellungen » Benutzer » Rechte » Benutzer » Tab: Ressourcen* umgezogen.

===== Menü

Mit Berechtigungen für Menüs wird festgelegt, welche Menüs ein Benutzer sehen und öffnen kann. Außerdem lässt sich zum Teil festlegen, welche Bearbeitungsmöglichkeiten der Benutzer im Menü hat. +
Eine Tabelle mit allen Menüberechtigungen befindet sich im Anhang.

===== REST-API-Berechtigungen

Mithilfe der Berechtigungen für die REST-API wird festgelegt, welche Daten ein Benutzer per REST abrufen, bearbeiten, hinzufügen oder löschen kann. Neben den Berechtigungen ist auch eine Authentifizierung für die Arbeit mit REST notwendig. Eine Tabelle mit allen REST-Berechtigungen befindet sich im Anhang.


===== SOAP-Berechtigungen

Mithilfe der Berechtigungen für die SOAP-API wird festgelegt, welche Abrufe, auch Calls genannt, ein Benutzer ausführen kann. Was die Calls bewirken, ist in der SOAP-Dokumentation beschrieben. Neben den Berechtigungen ist auch eine Authentifizierung für die Arbeit mit SOAP notwendig. Eine Tabelle mit allen SOAP-Berechtigungen befindet sich im Anhang.

===== Mobile-Berechtigungen

Mithilfe der Mobile-Berechtigungen wird festgelegt, was ein Benutzer in der plentymarkets-App sieht und worauf er zugreifen kann. Die Berechtigungen für Mobile sind in die folgenden 3 Abschnitte unterteilt: +

* Sichtbare Funktionen
* POS-Funktionen
* Sichtbare Kennzahlen

====== Sichtbare Funktionen

Mit den Berechtigungen für sichtbare Funktionen wird festgelegt, welche Funktionen der Benutzer sieht. Folgende Berechtigungen können in diesem Abschnitt gewählt werden:

* Artikelsuche
* Aufträge
* Picklisten
* Umbuchung
* Konten
* POS
* Kundensuche

====== POS-Funktionen

Mit den Berechtigungen für POS-Funktionen wird festgelegt, welche Kassen-Funktionen der Benutzer ausführen darf. Folgende Berechtigungen können in diesem Abschnitt gewählt werden:

* Preis bearbeiten
* Artikelposition umbenennen
* Rabatt gewähren
* Kassieren
* Kasse sperren
* Zwischenbericht
* Tagesabschluss
* Artikel Synchronisation
* Aufträge hochladen
* Retoure anlegen
* Kunde auswählen
* Stornierung

====== Sichtbare Kennzahlen

Mit den Berechtigungen für sichtbare Kennzahlen wird festgelegt, welche Kennzahlen der Benutzer sieht. Folgende Berechtigungen können in diesem Abschnitt gewählt werden:

* Aufträge
* Durchschnittliche Aufträge
* Neue Kunden
* Unbezahlte Aufträge
* Unzugeordnete Zahlungen
* Neue Artikel
* Umsatz
* Durchschnittlicher Umsatz
* Verkaufte Artikel
* Durchschnittlich verkaufte Artikel
* Artikel pro Auftrag
* Aktive Listings
* Gestartete Listings
* Wareneingänge
* Meldebestand
