= Kopfdokument: Vorlage zur Verfahrensdokumentation für plentymarkets Anwender
:lang: de
:position: 10

Dieses Dokument unterliegt Änderungen, die durch Versionierung gekennzeichnet werden.

== Zweck dieses Dokuments

Die Beschreibungen in diesem Dokument dienen den Anwendern der Software plentymarkets lediglich als Grundlage zur Erstellung ihrer Verfahrensdokumentation. Die konkrete Vorgehensweise bei der täglichen Arbeit liegt im Ermessen des Anwenders und muss durch ihn genau beschrieben werden.

== Definition plentymarkets

plentymarkets ist eine modular aufgebaute und Plugin-fähige Software für den Handel mit Sachgütern, digitalen Gütern und immateriellen Gütern. plentymarkets ist ein Produkt der plentymarkets GmbH und wird ausschließlich im SaaSA-Modell angeboten. Die Software verfügt über integrale und optionale Module. plentymarkets wird in verschiedenen Tarifen angeboten. Je nach Tarif unterscheiden sich die integralen und optionalen Module. +
Folgende Module sind verfügbar: Artikel, Auftragsabwicklung, CRM (Kundenkontakt / Beziehungsmanagement), Payment (Zahlungsanbindungen / Zahlungszuordnung), Fulfillment (Versandanbindungen), Online-Shop, Multi-Channel (Online-Marktplatz- und Vergleichsportalanbindungen), Warenwirtschaft und POS (Kassensystem für stationären Handel).

== Tarifstruktur

Aktuell ist plentymarkets in den Tarifen Classic und Zero verfügbar. In beiden Tarifen stehen integrale und optionale Module zur Verfügung. Integrale Module sind Module, die von Anfang an im Funktionsumfang des Systems enthalten sind. Optionale Module können zusätzlich gewählt werden und gehören dann ebenfalls zum Funktionsumfang des Systems.  Die integralen und optionalen Module unterscheiden sich je nach Tarif.

=== Tarif Classic

Folgende Module sind integral im Tarif Classic: Online-Shop, Auftragsabwicklung, CRM, Payment und Fulfillment. Optionale Module im Tarif Classic sind: Multi-Channel, POS und Warenwirtschaft.

=== Tarif Zero

Für den Tarif Zero sind integral: Online-Shop, Auftragsabwicklung, CRM, Payment, Fulfillment, Multi-Channel und Warenwirtschaft. Optional in diesem Tarif ist das Modul POS.

=== Hosting-Optionen

Jeder Anwender muss eine der von plentymarkets angebotenen Hosting-Optionen wählen. Die folgenden Hosting-Optionen stehen ihm hierbei zur Verfügung:
 * AWS Dublin
 * AWS Frankfurt
 * Cluster Frankfurt
Nähere Erläuterungen zu den einzelnen Hosting-Optionen finden sich im Dokument Data Security.

== Fachliche und technische Beschreibung der Software plentymarkets

plentymarkets dient insbesondere der Verwaltung und Abwicklung von Daten und Arbeitsabläufen, die im Zusammenhang mit dem Handel von Sachgütern, digitalen Gütern und immateriellen Gütern stehen. Hierbei kommen die genannten Module zum Einsatz. Die Vorteile beim Einsatz von plentymarkets liegen insbesondere darin, dass Artikelinformationen zentral in plentymarkets erfasst und verwaltet werden und von hier aus an verschiedene Kanäle für den Verkauf übermittelt werden. Des Weiteren liegen Vorteile darin, dass egal über welchen Kanal ein Artikel verkauft wurde, nach dem Verkauf eine Übermittlung der Auftrags- und Kundendaten an das plentymarkets System des Anwenders erfolgt, sodass die anschließende Abwicklung wieder zentral im plentymarkets System des Anwenders erfolgt. Ein weiterer Vorteil liegt in der Möglichkeit diese Abwicklung bis zu einem hohen Grad zu automatisieren. +
Als Verkaufskanäle kommen Marktplätze oder Vergleichsportale aus dem Modul Multi-Channel, Kassen aus dem Modul POS, eigene Online-Shops sowie über Plugins angebundene Kanäle infrage. Der Anwender entscheidet, welche Verkaufskanäle genutzt werden, sodass sich die verwendeten Kanäle für jeden Anwender unterscheiden.  +
Der Grad der Automatisierung wird durch den Anwender selbst bestimmt und unterscheidet sich deshalb ebenfalls für jeden Anwender. Die Bearbeitung und Abwicklung eines Auftrags bis hin zum Versand kann also komplett manuell oder automatisiert erfolgen. Manuell bedeutet, dass jeder einzelne Vorgang explizit durch einen Benutzer angestoßen wird. Automatisiert bedeutet, dass plentymarkets anhand eigens durch den Anwender festgelegter Kriterien Aktionen ausführt, die zuvor ebenfalls durch den Anwender festgelegt und aktiviert wurden. Das System führt die Aktionen also bei Zutreffen der Kriterien lediglich aus.  +
Einige Aktionen erfolgen jedoch auch automatisch durch das System und können nicht durch den Anwender beeinflusst werden. Hierbei handelt es sich um sogenannte Systemautomatismen. Welche Systemautomatismen es gibt, wird später im Text erläutert.

Bei Bestellung eines plentymarkets Systems erhält der Anwender Login-Daten, mit denen er sich in sein System einloggen kann.

Die einzelnen Module werden einzeln genauer beschrieben.

=== Fachliche und technische Beschreibung Benutzer und Benutzerrechte

Benutzer sind die Personen, die die Software plentymarkets bedienen. Die Benutzerrechte dienen dazu einem Benutzer den Zugriff zu Bereichen oder Menüs der Software zu ermöglichen, zu beschränken oder zu verwehren. +
Die Benutzerrechte eines Benutzer in plentymarkets hängen zunächst von seiner Benutzerklasse ab. Jedem Benutzer muss eine Benutzerklasse zugeordnet werden. Die Benutzerklassen sind systemseitig vorgegeben und können durch die Anwender nicht geändert werden. +
Folgende Benutzerklassen gibt es in plentymarkets:
 * Admin
 * Variabel
 * Callcenter
 * API
 * Logistik
 * Blog
 * Newsletter2Go

Jede Benutzerklasse ist mit unterschiedlichen Rechten versehen, die in den folgenden Kapiteln näher beschrieben werden. Die Vergabe von Rechten wird detailliert im Handbuch beschrieben: https://knowledge.plentymarkets.com/basics/arbeiten-mit-plentymarkets/benutzer-verwalten#90[https://knowledge.plentymarkets.com/basics/arbeiten-mit-plentymarkets/benutzer-verwalten#90] +
Außerdem können optional Benutzerrollen angelegt werden. Mithilfe von Benutzerrollen lassen sich Rechte für mehrere Benutzer gleichzeitig vergeben. Die Benutzer müssen dafür der Rolle zugeordnet werden.

==== Benutzerklasse Admin

Die Benutzerklasse Admin verfügt über alle Rechte und dient zur Verwaltung des Systems. Benutzern dieser Klasse können keine Rechte zusätzlich gewährt oder verwehrt werden. Sie verfügen pauschal über alle Rechte.

==== Benutzerklasse Variabel

Die Benutzerklasse Variabel verfügt standardmäßig über keine Rechte und bietet die größte Möglichkeit der individuellen Zuordnung von Rechten. Die 

==== Benutzerklasse Callcenter

Die Benutzerklasse Callcenter ist eine stark eingeschränkte Klasse. Sie hat standardmäßig Zugriffsrechte auf nur wenige Menüpunkte der Softwareoberflächer und Benutzern dieser Klasse können auch keine weiteren Menüpunkte freigegeben werden. Der Zugriff auf folgende Menübereiche ist freigegeben:
 * Dashboard des Anwendersystems
 * Kalender
 * Auftragsbearbeitung
 * Kundenbearbeitung inkl. Ticketsystem
Im Menübereich Kalender kann ein Benutzer der Klasse Callcenter lediglich seinen eigenen Kalender pflegen. Kalender von anderen Benutzer kann er nur sehen sowie bearbeiten, wenn diese es ihm erlauben. +
Standardmäßig ist kein Mandant freigegeben, so dass in keinem der weiteren Menübereiche tatsächlich Daten angezeigt werden. Des Weiteren sind standardmäßig keine Auftragsstatus sichtbar oder setzbar. Erst die Freigabe eines Mandanten für einen Benutzer der Klasse Callcenter erlaubt den tatsächlichen Zugriff auf Kundendaten und das Ticketsystem. Für den Zugriff auf Auftragsdaten muss zusätzlich zu einem Mandanten mindestens die Freigabe der Sichtbarkeit eines Auftragsstatus erfolgen.

==== Benutzerklasse API

Die Benutzerklasse API dient dem Datenaustausch über eine von plentymarkets zur Verfügung gestellte API-Technologie. Folgende API-Technologien stehen zur Verfügung:
 * SOAP
 * REST
Standardmäßig sind jedoch keine Zugriffsrechte für SOAP oder REST aktiviert. Es besteht lediglich die Möglichkeit einem Benutzer der Klasse API Zugriff per SOAP oder REST auf Daten des Systems zu gewähren. Ein API-Benutzer hat keinen Zugriff auf Daten über die Softwareoberfläche. +
Die SOAP API wird seit einiger Zeit nicht mehr weiterentwickelt, so dass sie technisch nicht mehr in allen Bereichen kompatibel ist mit der Datenstruktur von plentymarkets. Die REST API löst die SOAP API ab und stellt die neuere Technologie dar.  +
Eine detaillierte Beschreibung der SOAP-Schnittstelle findet sich unter folgendem Link: +
https://cdn02.plentymarkets.com/pmsbpnokwu6a/plugin/production/plentymanual/images/basics/assets/SOAP-Version-200-Documentation-2016-07-14.zip[https://cdn02.plentymarkets.com/pmsbpnokwu6a/plugin/production/plentymanual/images/basics/assets/SOAP-Version-200-Documentation-2016-07-14.zip] +
Eine detaillierte Beschreibung der REST-Schnittstelle findet sich unter folgender Adresse: +
https://developers.plentymarkets.com/[https://developers.plentymarkets.com/]

==== Benutzerklasse Logistik

Die Benutzerklasse Logistik hat über die Softwareoberfläche Zugriff auf folgende Bereiche:
 * Startseite
 * Kalender
 * Warenbestände suchen und bearbeiten
 * Wareneingänge suchen und bearbeiten
 * Warenberechnung
 * Datenimport und -export
 * Lagerort-Verwaltung
 * Aufträge suchen und bearbeiten
 * Fulfillment

==== Benutzerklasse Blog

Die Benutzerklasse Blog dient dazu einem Benutzer zu ermöglichen Blogbeiträge zu erstellen. Die Klasse hat Berechtigungen für folgende Bereiche:
 * Startseite
 * Kalender
 * Blog
Der Zugriff auf den Kalender bezieht sich lediglich auf den benutzereigenen Kalender. Kalender anderer Benutzer müssen durch diese zur Ansicht oder Bearbeitung freigegeben werden.

==== Benutzerklasse Newsletter2Go

Benutzerklasse, die automatisch für die Einrichtung einer link:https://knowledge.plentymarkets.com/crm/newsletter-versenden#2100[*Newsletter2Go*]-Schnittstelle verwendet wird.

=== Fachliche und technische Beschreibung des Moduls Auftragsabwicklung

Die Auftragsabwicklung als ein Modul von plentymarkets erlaubt die zentrale Bearbeitung und Abwicklung von Aufträgen, die aus verschiedenen Kanälen stammen. Für ein generelles Verständnis der Abwicklung von Aufträgen in plentymarkets sind folgende Punkte wichtig: +
plentymarkets unterscheidet verschiedene Auftragstypen und Auftragsherkünfte. Die Auftragstypen dienen dazu, verschiedene Geschäftsvorfälle abzubilden. Folgende Auftragstypen gibt es in plentymarkets:
 * Auftrag
 * Angebot
 * Gewährleistung
 * Gutschrift
 * Lieferauftrag
 * Reparatur
 * Retoure
 * Sammelauftrag
 * Sammelgutschrift
 * Vorbestellung
Die Auftragsherkünfte dienen dazu, zu kennzeichnen, über welchen Kanal ein Auftrag generiert wurde. Einige Herkünfte sind bereits standardmäßig im System gespeichert und andere können noch eigens hinzugefügt werden. Die eigenen können später auch wieder gelöscht werden. Das Löschen einer eigenen Herkunft löscht jedoch nicht die Herkunftsinformation in einem Auftrag., sonder bewirkt lediglich, dass zukünftig kein Auftrag mehr über diesen Kanal generiert werden kann. In den Informationen eines Auftrags bleibt konkret die ID der Herkunft gespeichert. Folgende Herkünfte sind standardmäßig in jedem plentymarkets System vorangelegt:

|===
|ID|Name|Verwendung|Erstellung|Entfernt|Kommentar

|0.00|Manuelle Eingabe|Auftrag|11.11.2013||
|1.00|Mandant (Shop)|Auftrag|11.11.2013||
|2.00|eBay|Auftrag|26.10.2012|13.10.2014|
|2.00|eBay|Filter|18.11.2014||
|2.01|eBay United States|Auftrag|09.12.2014||
|2.02|eBay Canada (English)|Auftrag|09.12.2014||
|2.03|eBay UK|Auftrag|09.12.2014||
|2.04|eBay Australia|Auftrag|09.12.2014||
|2.05|eBay Austria|Auftrag|09.12.2014||
|2.06|eBay Belgium (French)|Auftrag|09.12.2014||
|2.07|eBay France|Auftrag|09.12.2014||
|2.08|eBay Germany|Auftrag|09.12.2014||
|2.09|eBay Motors|Auftrag|09.12.2014||
|2.10|eBay|Auftrag|13.10.2014|18.11.2014|
|2.10|eBay Italy|Auftrag|09.12.2014||
|2.11|eBay Belgium(Dutch)|Auftrag|09.12.2014||
|2.12|eBay Netherlands|Auftrag|09.12.2014||
|2.13|eBay Spain|Auftrag|09.12.2014||
|2.14|eBay Switzerland|Auftrag|09.12.2014||
|2.15|eBay Hong Kong|Auftrag|09.12.2014||
|2.16|eBay India|Auftrag|09.12.2014||
|2.17|eBay Ireland|Auftrag|09.12.2014||
|2.18|eBay Malaysia|Auftrag|09.12.2014||
|2.19|eBay Canada (French)|Auftrag|09.12.2014||
|2.20|eBay Philippines|Auftrag|09.12.2014||
|2.21|eBay Poland|Auftrag|09.12.2014||
|2.22|eBay Singapore|Auftrag|09.12.2014||
|3.00|Elmar|Auftrag|11.11.2013||
|4.00|Amazon|Filter|26.10.2012||früher auch als Auftragsherkunft
|4.01|Amazon Germany|Auftrag|12.12.2014||
|4.02|Amazon UK|Auftrag|12.12.2014||
|4.03|Amazon USA|Auftrag|12.12.2014||
|4.04|Amazon France|Auftrag|12.12.2014||
|4.05|Amazon Italy|Auftrag|12.12.2014||
|4.06|Amazon Spain|Auftrag|12.12.2014||
|4.20|Amazon B2B|Auftrag|14.09.2016|20.09.2016|
|4.21|Amazon Germany B2B|Auftrag|14.09.2016||
|4.22|Amazon UK B2B|Auftrag|31.05.2017||
|5.00|Yatego|Auftrag|26.10.2012||
|6.00|Kelkoo|Auftrag|11.11.2013||
|7.00|Google Products|Auftrag|11.11.2013||
|8.00|Auvito|Unbekannt|26.10.2012||
|101.00|Ricardo|Auftrag|26.10.2012||
|102.00|real.de|Auftrag|20.06.2013||früher Hitmeister
|103.00|Kassensystem|Auftrag|11.11.2013||
|104.00|Amazon FBA|Filter|11.11.2013||
|104.01|Amazon FBA Germany|Auftrag|12.12.2014||
|104.02|Amazon FBA UK|Auftrag|12.12.2014||
|104.03|Amazon FBA USA|Auftrag|12.12.2014||
|104.04|Amazon FBA France|Auftrag|12.12.2014||
|104.05|Amazon FBA Italy|Auftrag|12.12.2014||
|104.06|Amazon FBA Spain|Auftrag|12.12.2014||
|104.20|Amazon FBA B2B|Auftrag|14.09.2016|20.09.2016|
|104.21|Amazon FBA Germany B2B|Auftrag|14.09.2016||
|104.22|Amazon FBA UK B2B|Auftrag|31.05.2017||
|105.00|Zentralverkauf|Auftrag|26.10.2012||Marktplatz geschlossen seit 31.01.2014
|105.00|Shopzilla|Merkmal|26.07.2017||
|106.00|Rakuten.de|Auftrag|11.11.2013||
|106.02|Rakuten.co.uk|Auftrag|18.05.2015||Marktplatz geschlossen seit 31.08.2016
|107.00|Neckermann.de Enterprise|Auftrag|26.10.2012||Keine technische Anbindung vorhanden* (Insolvenz 01.10.2012)
|108.00|Otto|Auftrag|26.10.2012||
|108.02|Otto Integration|Auftrag|05.05.2015||
|109.00|Shopgate|Auftrag|26.10.2012||
|110.00|Allyouneed|Auftrag|26.10.2012||früher MeinPaket
|111.00|Gimahhot|Auftrag|26.10.2012||Marktplatz geschlossen und übergegangen in Yatego
|112.00|Shopperella|Auftrag|26.10.2012|27.04.2017|Geschlossen bzw. Insolvenz seit Juni 2011
|112.00|billiger.de|Auftrag|27.04.2017||
|113.00|Shopshare|Auftrag|26.10.2012||Keine technische Anbindung vorhanden*
|114.00|Quelle|Auftrag|26.10.2012||Keine technische Anbindung vorhanden*
|115.00|Restposten|Auftrag|26.10.2012||
|116.00|Kauflux|Auftrag|26.10.2012||
|117.00|Home24|Auftrag|26.10.2012||Keine technische Anbindung vorhanden*
|118.00|Zalando|Auftrag|26.10.2012||
|119.00|Neckermann.at Enterprise|Auftrag|26.10.2012||
|120.00|Neckermann.at Cross-Docking|Auftrag|26.10.2012||
|121.00|Idealo|Auftrag|26.10.2012||
|121.02|Idealo Direktkauf|Auftrag|14.07.2016||
|122.00|La Redoute|Auftrag|26.10.2012||
|123.00|Laary|Auftrag|26.10.2012||Keine technische Anbindung vorhanden*
|124.00|SumoNet|Auftrag|26.10.2012||früher SumoScout, Abgeschaltet 30.09.2016
|125.00|Hood|Auftrag|26.10.2012||
|126.00|ParfumDEAL|Auftrag|26.10.2012||Marktplatz geschlossen und übergang zu Gimahhot
|127.00|BeezUP|Auftrag|16.11.2012||
|128.00|Google Shopping DE|Merkmal|15.01.2013||
|129.00|Google Shopping Int.|Merkmal|15.01.2013||
|130.00|Tracdelight|Auftrag|26.03.2013||
|131.00|Plus.de|Auftrag|16.09.2013||
|132.00|GartenXXL.de|Auftrag|16.09.2013||
|133.00|Twenga|Auftrag|25.09.2013||
|134.00|Play.com|Auftrag|21.10.2013||Keine technische Anbindung *
|134.00|SporTrade|Auftrag|24.10.2013||Keine technische Anbindung vorhanden*, Insolvenz Februar 2014
|135.00|Newsletter2Go|Auftrag|24.10.2013||
|136.00|Play.com|Auftrag|24.10.2013||Marktplatz am 23.05.2015 zu Rakuten.co.uk
|137.00|Grosshandel.eu|Auftrag|05.11.2013||
|138.00|Hertie|Auftrag|03.12.2013||
|139.00|CouchCommerce|Auftrag|29.01.2014||Keine technische Anbindung vorhanden*
|140.00|Pixmania|Merkmal|28.02.2014||
|141.00|Schuhe.de|Merkmal|12.05.2014||
|142.00|MyBestBrands|Merkmal|04.08.2014||
|143.00|Cdiscount|Auftrag|12.08.2014||
|143.02|Cdiscount C Logistique|Auftrag|19.08.2016||
|144.00|DaWanda|Auftrag|13.10.2014||
|145.00|Fruugo|Auftrag|12.02.2015||
|146.00|Shopping24|Merkmal|02.07.2015||
|147.00|Flubit|Auftrag|20.07.2015||
|148.00|Web-API|Markierung|05.08.2015||
|149.00|Mercateo|Auftrag|10.08.2015||
|150.00|Check24|Auftrag|01.06.2016||
|153.00|billiger.de|Auftrag|24.04.2017|27.04.2017|
|152.00|BOL.com|Auftrag|01.09.2016||
|204.00|Amazon B2B|Auftrag|07.09.2016|14.09.2016|
|204.01|Amazon Germany B2B|Auftrag|07.09.2016|14.09.2016|
|===
Tabelle 1: Systemherkünfte +
*Die Auftragsherkunft ist noch im System hinterlegt, aber es findet kein Datenaustausch mehr statt. Es ist nicht mehr möglich Daten/Artikel über die Schnittstelle zu senden.

Bei den oben aufgeführten Herkünften handelt es sich um Systemherkünfte. Systemherkünfte deshalb, weil sie bei Auslieferung eines plentymarkets Systems bereits angelegt sind und nicht gelöscht werden können. Die Systemherkünfte sind jedoch nicht automatisch aktiv. Sie sind lediglich bereits namentlich angelegt und verfügen über eine ID. Damit über eine Herkunft tatsächlich Aufträge generiert werden können und diese Herkunft einem Auftrag auch zugeordnet werden kann, muss sie mindestens aktiviert werden, aber bei vielen Systemherkünften sind noch weitere Einstellungen notwendig. +
Den Systemherkünften stehen die eigenen Herkünfte gegenüber. Eigene Herkünfte werden wie bereits erwähnt durch den Anwender hinzugefügt und müssen anschließend genau wie Systemherkünfte aktiviert werden. Im Gegensatz zu Systemherkünften können eigene Herkünfte später auch wieder gelöscht werden.  +
Für alle Herkünfte gilt also, dass sie aktiviert werden müssen und keine Herkunft ohne Wunsch des Anwenders zur Verfügung steht. Welche Schritte genau zur Einrichtung einer Herkunft notwendig sind, unterscheidet sich von Herkunft zu Herkunft und wird in den Beschreibungen der Module Multi-Channel, POS, Online-Shop sowie in den Plugin-Beschreibungen erläutert.

Zunächst folgt eine kurze exemplarische Beschreibung der Auftragsabwicklung. Für diese Kurzbeschreibung nehmen wir an, dass die Ware vorrätig ist, der Kunde im Shop gekauft hat und alle Angaben des Kunden korrekt sind. 

Exemplarische Kurzbeschreibung einer Auftragsabwicklung +
Die Bestellung geht als Auftrag ins System ein und erhält eine Auftrags-ID. Da die Artikel, die der Kunde bestellt hat, vorrätig sind, wartet der Auftrag nur auf eine Zahlungszuweisung, um für den Versand freigegeben zu werden. Der Kunde zahlt und die Zahlung wird anhand der Auftrags-ID dem Auftrag zugeordnet. Die Zahlung entspricht außerdem genau der Rechnungssumme, sodass der Auftrag vollständig bezahlt ist. Der Auftrag wird für den Versand freigegeben und versandfertig gemacht. Das versandfertige Paket wird einem Versanddienstleister übergeben und dem Kunden zugestellt. Der Kunde ist mit der Ware zufrieden, weshalb weder eine Retoure erfolgt noch andere nachträgliche Schritte notwendig sind.

In dem oben beschriebenen Fall muss der Anwender von plentymarkets während der Abwicklung kaum eingreifen, da weder der Kunde eine Änderung wünscht noch auf Seiten des Anwenders Verzögerungen oder Probleme auftreten. Da jedoch nicht jeder Auftrag so unproblematisch ausgeliefert wird, gibt es viele Einstellungen und Bearbeitungsmöglichkeiten, die ein Eingreifen ermöglichen. In welchen Fällen der Anwender tatsächlich in die Abwicklung eingreift und welche Schritte er ausführt, liegt in seinem Ermessen. In der fachlichen und technischen Beschreibung der Auftragsabwicklung wird nachfolgend nur aufgeführt, was geändert werden kann. Die Schritte und Einstellungen, die gewählt oder geklickt werden müssen, damit die Änderung erfolgt, werden wiederum im Handbuch ausführlich beschrieben.

==== Auftragstypen


Die Aufträge der verschiedenen Auftragstypen verfügen über unterschiedliche Einstellungen und somit über unterschiedliche Bearbeitungsmöglichkeiten. Generell gilt, dass ein Auftrag beim Erstellen im System eine ID erhält, die unabhängig vom Auftragstyp hochgezählt wird. Die Auftrags-ID wird durch das System vergeben. Es handelt sich hierbei um einen eindeutigen sogenannten Auto-Increment-Wert. In einem neu angelegten System sind 2 Beispielaufträge mit den IDs 101 und 102 vorhanden. Ausgehend von der ID 102 wird hochgezählt. Der Startwert für die Auftrags-IDs kann nicht geändert werden.

===== Auftragstyp Auftrag

Der Auftragstyp Auftrag dient zum Erfassen und Abwickeln von Kundenbestellungen. Der Kanal, über den der Auftrag generiert wurde, wird als Herkunft in den Auftragsdaten gespeichert. Aufträgen wird außerdem ein Status zugeordnet. Der verfügbare Statusbereich liegt zwischen 1 und 18.9. Je eine Nachkommastelle ist erlaubt, sodass insgesamt 190 Status zur Verfügung stehen. Da mithilfe der Auftragsstatus der Fortschritt der Abwicklung abgebildet werden soll, sind auch einige Systemautomatismen mit den Status verknüpft.  +
Jeder Auftrag wird bei Eingang in ein plentymarkets System zunächst auf Status 3 gesetzt. Diese Statuszuordnung ist ein Systemautomatismus. Anschließend kann der Anwender den Auftrag bearbeiten. Er kann dem Kunden eine Empfangsbestätigung senden. Er kann weitere Artikel, z.B. Gratisproben, hinzufügen. Er könnte dem Kunden einen Rabatt einräumen. Er kann die Rechnungsadresse, die Lieferanschrift, die Versandart sowie die Artikelpositionen ändern. Wie die Absprache mit dem Kunden bei Änderungen am Auftrag erfolgt, ist dabei Sache des Anwenders. Wenn einem Auftrag eine Zahlung zugeordnet werden konnte, erfolgt ein weiterer Statuswechsel. Auf welchen Status der Auftrag wechselt, hängt davon ab, ob der Auftrag unter-, über- oder vollständig bezahlt ist. Wenn ein Auftrag unterbezahlt ist, wird er automatisch auf Status 3.3 gesetzt. Wenn ein Auftrag überbezahlt ist, wird er automatisch auf Status 3.2 gesetzt. Wenn ein Auftrag vollständig bezahlt ist und das Modul Warenwirtschaft nicht verwendet wird, wechselt der Auftrag auf Status 5. Status 5 bedeutet, dass der Auftrag für den Versand freigegeben wurde. Dieser Status eignet sich also, um Picklisten oder Ähnliches zu erstellen. +
Ein vom System angestoßener automatischer Statuswechsel auf Status 5 erfolgt auch für einige Zahlungsarten, bei denen ein Warten auf die Zahlung nicht sinnvoll ist. Zu diesen Zahlungsarten gehören z.B. Kauf auf Rechnung, Lastschrift oder Zahlung per Nachnahme. Eine Liste der Zahlungsarten findet sich im https://www.plentymarkets.eu/handbuch/payment/zahlungsarten-verwalten/#7[Handbuch]. +
Wenn das Modul Warenwirtschaft genutzt wird, haben die Einstellungen zur Bestandsführung zusätzlich Einfluss auf den automatischen Statuswechsel, sodass daraus ein anderes Verhalten resultieren kann.

Was ein eingeloggter Benutzer von plentymarkets letztendlich in der Abwicklung eines Auftrags vom Typ Auftrag bearbeiten kann, hängt von seinen Benutzerrechten ab. Die folgende Beschreibung orientiert sich an einem Benutzer mit vollen Bearbeitungsrechten. Bei einem solchen Benutzer hängen die Bearbeitungsmöglichkeiten in einem Auftrag vom Fortschritt der Abwicklung und von der Herkunft ab. Insbesondere das Erzeugen von Dokumenten sorgt für systemseitige Einschränkungen der Bearbeitungsmöglichkeiten, die der Benutzer nicht umgehen kann. Nachdem ein Dokument erzeugt wurde, werden die Einstellungen eingeschränkt, die bearbeitet werden können. Welche Einstellungen noch bearbeitbar sind, hängt wiederum von dem Typ des Dokuments ab. Bei Aufträgen mit einer automatisch zugeordneten Herkunft ist die Herkunft ab dem Moment der Auftragsanlage, also bevor ein Dokument erzeugt wurde, nicht mehr änderbar. Bei Aufträgen mit einer manuell zugeordneten Herkunft ist die Herkunft auch nach Auftragsanlage noch änderbar. Bis das erste Dokument erzeugt wurde, können folgende Angaben ergänzt oder geändert werden:
 . die Rechnungsadresse, 
 . die Lieferadresse, 
 . die Auftragspositionen, 
 . die Bankdaten des Kunden,
 . das Eingabedatum mit Eingabeuhrzeit des Auftrags,
 . das Auftragsgewicht,
 . die Markierung,
 . die Mahnstufe,
 . die Kundennotizen,
 . die Auftragsnotizen,
 . der Status eines Auftrags,
 . der Auftragstyp,
 . der Eigner des Auftrags,
 . die Herkunft, wenn es eine manuell zugeordnete Herkunft ist,
 . die Sprache des Auftrags,
das Lager des Auftrags,
 . der Warenausgang kann gebucht werden,
 . das Versanddatum,
 . das Rückgabedatum,
 . die Auftragswährung samt Umrechnungskurs,
 . die Zahlungsart,
 . das Zahlungsziel,
 . der Versanddienstleister,
 . das Versandprofil,
 . die externe Auftragsnummer,
 .  das Zeichen des Kunden,
 .  die Anzahl der Pakete,
 . die Paketnummern,
 . der Rabatt pro Artikelposition.

Weitere Bearbeitungsmöglichkeiten, die zur Verfügung stehen, wenn noch kein Dokument erzeugt wurde, sind:
 . das Kopieren eines Auftrags, 
 . das Teilen eines Auftrags, 
 . das Löschen eines Auftrags, 
 . das Gruppieren von Aufträgen, 
 . das Zuordnen von Lagerorten,
 . das Lösen von Lagerortzuordnungen,
 . das Versenden von E-Mails,
 . das Zuordnen und Zurücksetzen von Zahlungen,
 . das Erstellen von Belegen,
 . das Erstellen von Artikeletiketten für die Varianten im Auftrag
 . und das Erstellen von Lieferaufträgen für den Auftrag.

Das Erstellen eines Belegs, auch Dokument genannt, führt zu Einschränkungen der Bearbeitungsmöglichkeiten. Die Einschränkungen unterscheiden sich je nach Dokument, das erzeugt wurde. Die Dokumente, die in einem Auftrag vom Typ Auftrag erstellt werden können, werden in Tabelle 2 zusammen mit den Bearbeitungsmöglichkeiten aufgeführt. +
Zunächst werden jedoch noch einige andere Bearbeitungsmöglichkeiten kurz erläutert, wie das Gruppieren und Teilen von Aufträgen. +
Gruppieren bedeutet, dass mindestens zwei Aufträge zu einem neuen Auftrag zusammengefasst werden, wobei die eigentlichen Aufträge gelöscht werden. Der gruppierte Auftrag erhält eine neue Auftrags-ID. +
Gruppiert werden können Aufträge jedoch nur unter folgenden Bedingungen:
 * die Rechnungsanschrift ist gleich,
 * die Lieferanschrift ist gleich,
 * die Herkunft ist gleich,
 * der Auftragstyp aller Aufträge ist vom Typ _Auftrag_,
 * es wurde kein Rechnungsdokument erzeugt und
 * die Aufträge haben keine untergeordneten Aufträge anderer Auftragstypen.
Teilen eines Auftrags bedeutet, dass Artikelpositionen gewählt werden und ein neuer Auftrag angelegt wird, der diese Artikelpositionen enthält. Der neu angelegte Auftrag kann wiederum geteilt werden, wenn er mehr als eine Artikelposition enthält. Der ursprüngliche Auftrag bleibt erhalten, lediglich die gewählten Artikelpositionen werden aus dem Auftrag entfernt. Für jeden geteilten Auftrag stehen alle Bearbeitungsmöglichkeiten zur Verfügung. +
Das Erstellen von Lieferaufträgen bedeutet, dass im Funktionsumfang reduzierte Aufträge erstellt werden. Ein Lieferauftrag dient dem Versand von Waren aus unterschiedlichen Lagern oder mit unterschiedlicher Verfügbarkeit. Ein Lieferauftrag ist fest mit dem Auftrag, in dem er erstellt wurde, verbunden. Der ursprüngliche Auftrag wird in diesem Zusammenhang auch häufig Hauptauftrag genannt. In einem Lieferauftrag ist es z.B. nicht möglich eine Rechnung zu erstellen, da er nur dem Versand dient und die Rechnung die gesamte Bestellung berücksichtigt. Welche Funktionen genau in einem Lieferauftrag zur Verfügung stehen, wird später detailliert erläutert. +
Wenn bereits ein Dokument, wie z.B. eine Rechnung, erzeugt wurde, ist die Bearbeitung stark eingeschränkt. Die folgende Tabelle zeigt, welche Bearbeitungsmöglichkeiten bestehen, nachdem das aufgeführte Dokument im Auftrag erzeugt wurde.

|===
|Dokument|Bearbeitungsmöglichkeiten

|Rechnung|Nach dem Erzeugen sind viele Bearbeitungsmöglichkeiten gesperrt.
|Lieferschein|Das Erzeugen eines Lieferscheins sorgt nicht für Einschränkungen.
|Auftragsbestätigung|Das Erzeugen einer Auftragsbestätigung sorgt nicht für Einschränkungen.
|Mahnung|Das Erzeugen einer Mahnung sorgt nicht für Einschränkungen.
|Adressetikett|Das Erzeugen eines Adressetiketts im Auftrag hat keine Auswirkungen auf den Auftrag.
|Gelangensbestätigung|Das Erzeugen einer Gelangensbestätigung sorgt nicht für Einschränkungen.
|Abhollieferung|Das Erzeugen eines Abhollieferscheins sorgt nicht für Einschränkungen.
|Rücksendeschein|Das Erzeugen eines Rücksendescheins sorgt nicht für Einschränkungen.
|Stornobeleg|Ein Stornobeleg kann nur erzeugt werden, wenn bereits eine Rechnung erzeugt wurde. Durch das Erzeugen des Stornobelegs stehen wieder alle Bearbeitungsmöglichkeiten, die durch das Erzeugen einer Rechnung gesperrt wurden, zur Verfügung.
|===
Tabelle 2: Bearbeitungsmöglichkeiten im Auftrag nach dem Erzeugen eines Dokuments

===== Auftragstyp Angebot

Der Auftragstyp Angebot dient der Unterbreitung von Angeboten an Kunden. Der Funktionsumfang oder die Bearbeitungsmöglichkeiten des Angebots sind geringer als beim Auftrag. So kann z.B. bei einem Angebot kein Warenausgang gebucht werden und es kann nicht in Lieferaufträge geteilt werden, weil dieser Auftragstyp nicht für den Versand vorgesehen ist. Aus diesem Grund können auch keine Paketnummern, kein Versanddatum und kein Rückgabedatum eingetragen werden sowie keine Lagerorte zugeordnet oder wieder gelöst werden. Aus den Aufzählungen oben sind also folgende Punkte nicht möglich: Q, R, S, BB, V, VI, XI. Außerdem ist die Anzahl der Dokumente, die in einem Angebot erzeugt werden können geringer. Vier unterschiedliche Dokumente können erzeugt werden. Diese Dokumente sind:
 * Rechnung,
 * Auftragsbestätigung,
 * Angebot und
 * Stornobeleg
Die weiteren Funktionen gleichen denen eines Auftrags. Das Erzeugen eines Dokuments hat auch beim Angebot Einfluss auf die Bearbeitungsmöglichkeiten. Die folgende Tabelle listet auf, welche Bearbeitungsmöglichkeiten nach dem Erzeugen des jeweiligen Dokuments zur Verfügung stehen.

|===
|Dokument|Bearbeitungsmöglichkeiten

|Rechnung|Nach dem Erzeugen sind viele Bearbeitungsmöglichkeiten gesperrt.
|Auftragsbestätigung|Das Erzeugen einer Auftragsbestätigung sorgt nicht für Einschränkungen.
|Angebot|Das Erzeugen eines Angebotsdokuments sorgt nicht für Einschränkungen.
|Stornobeleg|Ein Stornobeleg kann nur erzeugt werden, wenn bereits eine Rechnung erzeugt wurde. Durch das Erzeugen des Stornobelegs stehen wieder alle Bearbeitungsmöglichkeiten, die durch das Erzeugen einer Rechnung gesperrt wurden, zur Verfügung.
|===
Tabelle 3: Bearbeitungsmöglichkeiten im Angebot nach dem Erzeugen eines Dokuments

===== Auftragstyp Vorbestellung

Der Auftragstyp Vorbestellung dient zum Erfassen von Bestellungen, bei denen das Erscheinungs- oder Verfügbarkeitsdatum der Ware in der Zukunft liegt. Vorbestellungen können manuell erfasst werden oder neue Aufträge des Typs Auftrag, die z.B. Artikel mit einem Erscheinungsdatum in der Zukunft erhalten, können automatisiert in Vorbestellungen umgewandelt werden.  +
Bei einer Vorbestellung kann kein Warenausgang gebucht werden und sie kann nicht in Lieferaufträge geteilt werden, weil dieser Auftragstyp nicht für den Versand vorgesehen ist. Aus diesem Grund können auch keine Paketnummern, kein Versanddatum und kein Rückgabedatum eingetragen werden sowie keine Lagerorte zugeordnet oder wieder gelöst werden. Aus den Aufzählungen oben sind also folgende Punkte nicht möglich: Q, R, S, BB, V, VI, XI. Außerdem ist die Anzahl der Dokumente, die in einer Vorbestellung erzeugt werden können geringer. Folgende Dokumente können erzeugt werden:
 * Rechnung,
 * Auftragsbestätigung und
 * Stornobeleg.
Die weiteren Funktionen gleichen denen eines Auftrags. Das Erzeugen eines Dokuments hat auch bei einer Vorbestellung Einfluss auf die Bearbeitungsmöglichkeiten. Die folgende Tabelle listet auf, welche Bearbeitungsmöglichkeiten nach dem Erzeugen des jeweiligen Dokuments zur Verfügung stehen.

|===
|Dokument|Bearbeitungsmöglichkeiten

|Rechnung|Nach dem Erzeugen sind viele Bearbeitungsmöglichkeiten gesperrt.
|Auftragsbestätigung|Das Erzeugen einer Auftragsbestätigung sorgt nicht für Einschränkungen.
|Stornobeleg|Ein Stornobeleg kann nur erzeugt werden, wenn bereits eine Rechnung erzeugt wurde. Durch das Erzeugen des Stornobelegs stehen wieder alle Bearbeitungsmöglichkeiten, die durch das Erzeugen einer Rechnung gesperrt wurden, zur Verfügung.
|===
Tabelle 4: Bearbeitungsmöglichkeiten in einer Vorbestellung nach dem Erzeugen eines Dokuments

===== Auftragstyp Gutschrift

Der Auftragstyp Gutschrift dient zur Rückzahlung von Beträgen an Kunden. Es handelt sich hierbei also um eine Gutschrift, wie sie im allgemeinen Sprachgebrauch verstanden wird, und nicht um eine buchhalterische Gutschrift. +
Eine Gutschrift ist ein untergeordneter Auftragstyp, d.h. sie ist einem anderen Auftrag eines anderen Typs zugeordnet und kann nur aus einem bereits bestehenden Auftrag heraus erstellt werden. In Aufträgen der folgenden Auftragstypen können Gutschriften erstellt werden:
 * Auftrag
 * Retoure
 * Reparatur
 * Gewährleistung
Bei all diesen Typen kann eine Rückzahlung notwendig werden, deshalb kann bei Ihnen eine Gutschrift erstellt werden. +
Der Standardstatus, den eine Gutschrift nach dem Erstellen erhält, ist Auftragsstatus 11. Alle Varianten, die im Auftrag enthalten sind, zu dem die Gutschrift erzeugt wird, werden zunächst vollständig in die Gutschrift übernommen. Die Varianten können anschließend z.B. aus der Gutschrift entfernt werden. Generell stehen in einem Auftrag des Typs Gutschrift folgende Bearbeitungsmöglichkeiten nicht zur Verfügung:
 * L - kein Ändern des Auftragstyps
 * Q - kein Buchen eines Warenausgang
 * R - kein Eingabefeld für ein Versanddatum
 * S - kein Eingabefeld für ein Rückgabedatum
 * AA - kein Eingabefeld für die Paketanzahl
 * BB - kein Eingabefeld für Paketnummern
 * I - kein Kopieren des Auftrags
 * II - kein Teilen des Auftrags
 * V - kein Zuordnen von Lagerorten
 * VI - kein Lösen von Lagerorten
 * XI - kein Erstellen von Lieferaufträgen
Die Mehrheit dieser Möglichkeiten sind relevant für den Versand von Ware und da eine Gutschrift nicht für den Versand gedacht ist, stehen sie in diesem Auftragstyp nicht zur Verfügung. +
Die folgende Tabelle führt auf welche Dokumente in einer Gutschrift erzeugt werden können und welche Einschränkung durch das Erzeugen entstehen: 

|===
|Dokument|Bearbeitungsmöglichkeiten

|Gutschrift|Nach dem Erzeugen sind viele Bearbeitungsmöglichkeiten gesperrt.
|Korrekturbeleg|Das Erzeugen eines Korrekturbelegs sorgt nicht für Einschränkungen.
|Stornobeleg Gutschrift|Ein Stornobeleg kann nur erzeugt werden, wenn bereits eine Gutschrift erzeugt wurde. Durch das Erzeugen des Stornobelegs stehen wieder alle Bearbeitungsmöglichkeiten, die durch das Erzeugen einer Gutschrift gesperrt wurden, zur Verfügung.
|===
Tabelle 5: Bearbeitungsmöglichkeiten in einer Gutschrift nach dem Erzeugen eines Dokuments

===== Auftragstyp Gewährleistung

Der Auftragstyp Gewährleistung dient zum Erfassen und Abwickeln von Artikeln, bei denen der Anspruch auf Gewährleistung zutrifft. +
Eine Gewährleistung kann nur manuell erstellt werden. Eine Gewährleistung ist ein untergeordneter Auftragstyp, d.h. er ist einem anderen Auftrag eines anderen Typs zugeordnet und kann nur aus einem bereits bestehenden Auftrag heraus erstellt werden. Eine Gewährleistung kann aus einem Auftrag des Typs Auftrag oder des Typs Retoure erstellt werden. Beim Erzeugen einer Gewährleistung muss der Anwender wählen, welche Varianten aus dem übergeordneten Auftrag in die Gewährleistung übernommen werden sollen. Erst nachdem die Wahl durch Speichern bestätigt wurde, wird der Auftrag des Typs Gewährleistung erzeugt. Eine Gewährleistung wird automatisch auf Status 5 gesetzt beim Erzeugen. +
In einem Auftrag des Typs Gewährleistung ist es generell nicht möglich eine Mahnstufe zu wählen. Eine Änderung des Auftragstyps ist ebenfalls nicht möglich. Außerdem kann der Auftrag nicht kopiert oder geteilt werden. Damit sind folgende Punkte aus der Aufzählung unter Auftrag nicht möglich:
 * H
 * L
 * I
 * II

|===
|Dokument|Bearbeitungsmöglichkeiten

|Rechnung|Nach dem Erzeugen sind viele Bearbeitungsmöglichkeiten gesperrt.
|Lieferschein|Das Erzeugen eines Lieferscheins sorgt nicht für Einschränkungen.
|Auftragsbestätigung|Das Erzeugen einer Auftragsbestätigung sorgt nicht für Einschränkungen.
|Mahnung|Das Erzeugen einer Mahnung sorgt nicht für Einschränkungen.
|Adressetikett|Das Erzeugen eines Adressetiketts hat keine Auswirkungen auf die Gewährleistung.
|Gelangensbestätigung|Das Erzeugen einer Gelangensbestätigung sorgt nicht für Einschränkungen.
|Abhollieferung|Das Erzeugen eines Abhollieferscheins sorgt nicht für Einschränkungen.
|Rücksendeschein|Das Erzeugen eines Rücksendescheins sorgt nicht für Einschränkungen.
|Stornobeleg|Ein Stornobeleg kann nur erzeugt werden, wenn bereits eine Rechnung erzeugt wurde. Durch das Erzeugen des Stornobelegs stehen wieder alle Bearbeitungsmöglichkeiten, die durch das Erzeugen einer Rechnung gesperrt wurden, zur Verfügung.
|===
Tabelle 6: Bearbeitungsmöglichkeiten in einer Gewährleistung nach dem Erzeugen eines Dokuments

===== Auftragstyp Retoure

Der Auftragstyp Retoure dient zum Erfassen von retournierten Artikeln. Eine Retoure kann manuell oder automatisiert erstellt werden. Eine Retoure ist ein untergeordneter Auftragstyp, da er einem bereits bestehenden Auftrag zugeordnet ist. Manuell kann eine Retoure in einem Auftrag des Typs Auftrag oder des Typs Gewährleistung erstellt werden.  +
Beim manuellen Erzeugen einer Retoure muss der Anwender wählen, welche Varianten aus dem übergeordneten Auftrag in die Retoure übernommen werden sollen. Außerdem kann ein Status und ein Grund für die Retoure ausgewählt werden sowie eine Paketnummer eingetragen werden. Status 9 ist vorausgewählt. Erst nachdem die Wahl durch Speichern bestätigt wurde, wird der Auftrag des Typs Retoure erzeugt. +
In einem Auftrag des Typs Gewährleistung ist es generell nicht möglich eine Mahnstufe zu wählen. Eine Änderung des Auftragstyps ist ebenfalls nicht möglich. Außerdem kann der Auftrag nicht kopiert oder geteilt werden. Weiterhin sind alle Bearbeitungsmöglichkeiten, die im Zusammenhang mit dem Versand oder Zahlungen stehen nicht möglich. Damit sind folgende Punkte aus der Aufzählung unter Auftrag nicht möglich:
 * H
 * L
 * Q
 * R
 * S
 * T
 * U
 * V
 * W
 * X
 * Y
 * Z
 * AA
 * BB
 * CC
 * I
 * II
 * XI
In einer Retoure kann der retournierten Variante eine Artikelstatus zugeordnet werden. Es kann ein Hinweis zur Variante sowie ein Prozentwert, der den Artikelwert der retournierten Varianten angibt, eingetragen werden. Der Grund für die Retoure kann geändert sowie Ware wieder eingebucht werden.

|===
|Dokument|Bearbeitungsmöglichkeiten

|Rücksendeschein|Das Erzeugen eines Rücksendescheins sorgt nicht für Einschränkungen.
|Abhollieferung|Das Erzeugen eines Abhollieferscheins sorgt nicht für Einschränkungen.
|===
Tabelle 7: Bearbeitungsmöglichkeiten in einer Retoure nach dem Erzeugen eines Dokuments

===== Auftragstyp Reparatur

Der Auftragstyp Reparatur dient zum Erfassen von Artikeln, die repariert werden können. Eine Reparatur kann nur aus einem Auftrag vom Typ Retoure heraus erstellt werden. Es handelt sich also um einen Auftrag, der der Retoure untergeordnet ist und in den nur Artikel, die bereits als retourniert erfasst wurden, übernommen werden können. Eine Reparatur kann nur manuell angelegt werden, da bei jedem Artikel geprüft werden muss, ob er repariert und somit in eine Reparatur übernommen werden kann.

|===
|Dokument|Bearbeitungsmöglichkeiten

|Rechnung|_Inhalte werden ergänzt_
|Lieferschein|_Inhalte werden ergänzt_
|Auftragsbestätigung|_Inhalte werden ergänzt_
|Mahnung|_Inhalte werden ergänzt_
|Adressetikett|_Inhalte werden ergänzt_
|Gelangensbestätigung|_Inhalte werden ergänzt_
|Abhollieferung|_Inhalte werden ergänzt_
|Rücksendeschein|_Inhalte werden ergänzt_
|Reparaturschein|_Inhalte werden ergänzt_
|===
Tabelle 8: Bearbeitungsmöglichkeiten in einer Reparatur nach dem Erzeugen eines Dokuments

===== Auftragstyp Sammelauftrag

Der Auftragstyp Sammelauftrag dient zum Zusammenfassen von unbezahlten Aufträgen, für die eine übergreifende Rechnung gestellt werden soll. Beim Erzeugen von Sammelaufträgen werden nur die folgenden drei Auftragstypen berücksichtigt:
 * Auftrag
 * Gewährleistung
 * Reparatur
Die Aufträge, die in einen Sammelauftrag übernommen werden, können durch den Anwender weiter eingeschränkt werden. Zum einen kann er aus den Auftragstypen wählen, welche in Sammelaufträge übernommen werden können. Also ob alle drei Auftragstypen oder nur zwei Auftragstypen oder nur ein Auftragstyp für Sammelaufträge berücksichtigt werden. Zum anderen kann der Anwender Status wählen, die Aufträge haben müssen, um für Sammelaufträge berücksichtigt zu werden. +
Der Sammelauftrag selbst wird automatisch beim Erstellen auf Status 1 gesetzt. +
In einem Sammelauftrag können folgende Dokumente erstellt werden:
 * Rechnung und
 * Mahnung.

|===
|Dokument|Bearbeitungsmöglichkeiten

|Rechnung|_Inhalte werden ergänzt_
|Mahnung|_Inhalte werden ergänzt_
|===
Tabelle 9: Bearbeitungsmöglichkeiten in eines Sammelauftrags nach dem Erzeugen eines Dokuments

===== Auftragstyp Sammelgutschrift

Der Auftragstyp Sammelgutschrift dient zum Zusammenfassen von Gutschriften, um eine Sammelrückzahlung vorzunehmen.

===== Auftragstyp Lieferauftrag

Der Lieferauftrag dient zur Auslieferung von Waren. Für einen Lieferauftrag kann keine Rechnung gestellt werden. Ein Lieferauftrag ist immer einem Auftrag zugeordnet und in diesem Auftrag erfolgt die Rechnungsstellung. Das Anlegen von Lieferaufträgen ist sinnvoll bei Aufträgen mit mehreren Artikelpositionen, die entweder in unterschiedlichen Lagern gelagert werden oder die mit unterschiedlichen Dienstleistern versendet werden sollen. Mithilfe von Lieferaufträgen kann ein Teil der bestellten Ware bereits ausgeliefert werden, während ein anderer Teil erst noch nachbestellt oder produziert wird. +
Es gibt zwei Möglichkeiten, Lieferaufträge anzulegen, manuell oder automatisiert. Beim manuellen Erstellen wählt der Anwender Artikelpositionen aus, die er in einen Lieferauftrag übernehmen möchte. Hierzu gibt er pro Artikelposition die Anzahl ein, die er in einen Lieferauftrag übernehmen möchte. Anschließend muss er auf Lieferauftrag anlegen klicken und ein Lieferauftrag wird angelegt. Diese Vorgehensweise sollte er fortsetzen, bis alle Artikelpositionen in Lieferaufträge überführt worden. +
Beim automatisierten Teilen werden auf einmal alle Artikelpositionen anhand eines festgelegten Kriteriums in Lieferaufträge aufgeteilt. Das Teilen erfolgt jedoch nur, wenn mindestens zwei Lieferaufträge durch das Teilen entstehen. Wenn alle Artikelpositionen in einen Lieferauftrag übernommen würden, wird nicht geteilt. Folgende vier Kriterien stehen für das Teilen in Lieferaufträge zur Wahl:
 * Lager
 * Versandprofil
 * Lager und Versandprofil
 * Lager und Netto-Warenbestand
Das automatisierte Teilen kann wiederum manuell durch den Anwender oder automatisiert angestoßen werden. Automatisiert angestoßen bedeutet, dass der Anwender einen  Zeitpunkt, zu dem ein Auftrag in Lieferaufträge geteilt wird, bestimmt. Die Funktion, die hierzu genutzt werden kann, nennt sich Ereignisaktion. Die allgemeine Funktionsweise von Ereignisaktionen wird an anderer Stelle beschrieben.
