= Kopfdokument: Vorlage zur Verfahrensdokumentation für plentymarkets Anwender
:lang: de
include::{includedir}/_header.adoc[]

== Definition plentymarkets

plentymarkets ist eine modular aufgebaute und Plugin-fähige Software für den Handel mit Sachgütern, digitalen Gütern und immateriellen Gütern. plentymarkets ist ein Produkt der plentymarkets GmbH und wird ausschließlich im SaaSA-Modell angeboten. Die Software verfügt über integrale und optionale Module. plentymarkets wird in verschiedenen Tarifen angeboten. Je nach Tarif unterscheiden sich die integralen und optionalen Module.
Folgende Module sind verfügbar: Artikel, Auftragsabwicklung, CRM (Kundenkontakt / Beziehungsmanagement), Payment (Zahlungsanbindungen / Zahlungszuordnung), Fulfillment (Versandanbindungen), Online-Shop, Multi-Channel (Online-Marktplatz- und Vergleichsportalanbindungen), Warenwirtschaft und POS (Kassensystem für stationären Handel).

== Tarifstruktur

Aktuell ist plentymarkets in den Tarifen Classic und Zero verfügbar. In beiden Tarifen stehen integrale und optionale Module zur Verfügung. Integrale Module sind Module, die von Anfang an im Funktionsumfang des Systems enthalten sind. Optionale Module können zusätzlich gewählt werden und gehören dann ebenfalls zum Funktionsumfang des Systems.  Die integralen und optionalen Module unterscheiden sich je nach Tarif.

=== Tarif Classic

Folgende Module sind integral im Tarif Classic: Online-Shop, Auftragsabwicklung, CRM, Payment und Fulfillment. Optionale Module im Tarif Classic sind: Multi-Channel, POS und Warenwirtschaft.

=== Tarif Zero

Für den Tarif Zero sind integral: Online-Shop, Auftragsabwicklung, CRM, Payment, Fulfillment, Multi-Channel und Warenwirtschaft. Optional in diesem Tarif ist das Modul POS.
