= Fachliche und technische Beschreibung plentyWarehouse App

Die plentyWarehouse App enthält die folgenden Funktionen zur Verwaltung von Lagerbeständen und Durchführung verschiedener Vorgänge der Warenwirtschaft:

- 



[TIP]
.Ergänzen Sie Ihre eigenen Firmendaten
====
Dieses Kapitel enthält eine Mischung aus rein informativen Texten über die plentyWarehouse App und aus Textblöcken, in denen Sie Informationen selbst ergänzen müssen. Gehen Sie dieses Kapitel sorgfältig durch und ergänzen Sie alle GoBD-relevanten Informationen zu Ihrer eigenen Firma.
====

== Systemvoraussetzungen und Betrieb

Die plentymarkets App wird in folgenden App-Stores kostenlos bereitgestellt:

** iOS: https://itunes.apple.com/de/app/plentymarkets/id957702618?mt=8[https://itunes.apple.com/de/app/plentymarkets/id957702618?mt=8^]
** Android: https://play.google.com/store/apps/details?id=eu.plentymarkets.mobile[https://play.google.com/store/apps/details?id=eu.plentymarkets.mobile^]

Versionen der plentymarkets App sind durch Versionsnummern gekennzeichnet. Änderungen an der Software werden sowohl in den Changelogs der App-Stores als auch im plentymarkets Forum veröffentlicht.

** https://forum.plentymarkets.com/c/changelog/changelog-app[https://forum.plentymarkets.com/c/changelog/changelog-app]

== Hardware

Die plentymarkets App läuft auf mobilen Endgeräten mit folgenden Systemvoraussetzungen:

* Android-Geräte mit OS-Version ab 4.2.2
* iOS-Geräte (iPad, iPhone, iPod) mit OS-Version ab 8

Die App wird ohne eigene Hardware ausgeliefert. Je nach Anwendungsfall werden aber link:https://knowledge.plentymarkets.com/de-de/manual/main/app/installieren.html#100[unterschiedliche Endgeräte^] empfohlen.

Ergänzen Sie die folgende Tabelle. Hier werden die unternehmenseigenen Tablets, Smartphones und sonstigen mobilen Endgeräte aufgelistet, auf denen die plentymarkets App installiert wurde.

[[tabelle-app-hardware-vorlage]]
.Eingesetzte Hardware
|===
|Gerätetyp|Modellnummer|Hersteller

|{nbsp}
|{nbsp}
|{nbsp}

|{nbsp}
|{nbsp}
|{nbsp}

|{nbsp}
|{nbsp}
|{nbsp}
|===

== Zugang zur App

=== Anmeldung

Die plentymarkets App ist nur in Kombination mit einem gebuchten plentymarkets ERP-System funktionsfähig. Das heißt, dass Sie bei der Erstanmeldung die Login-Daten Ihres plentymarkets ERP-Systems eingeben müssen. Diese Login-Daten bestehen aus:

* Basis-URL des plentymarkets ERP-Systems
* Benutzer
* Passwort

=== Zugriffsrechte

Admin-Benutzer haben uneingeschränkten Zugriff auf die plentyWarehouse App. Ergänzen Sie die Liste der Admin-Benutzer im <<#_fachliche_und_technische_beschreibung_benutzer_und_benutzerrechte, Kapitel zu Benutzerrechten>> und geben Sie somit an, welche Mitarbeiter über uneingeschränkten Zugriff auf alle Funktionen der plentyWarehousse App verfügen.

Für alle anderen Benutzerklassen müssen die Benutzerrechte pro Rolle definiert werden. Die Zugriffsrechte für die plentyWarehouse App werden im Menü *Einrichtung » Einstellungen » Benutzer » Konten » Konto öffnen » Tab: Mobile* definiert. Ergänzen Sie die Liste der Backend-Benutzer im <<#_fachliche_und_technische_beschreibung_benutzer_und_benutzerrechte, Kapitel zu Benutzerrechten>> und geben Sie somit an, welche Mitarbeiter über eingeschränkten Zugriff auf die Funktionen der plentymarkets App verfügen.

== App-Funktionen

Die App beinhaltet eine Reihe nützlicher Funktionen, die im link:https://knowledge.plentymarkets.com/de-de/manual/main/app/funktionen.html[plentymarkets Benutzerhandbuch^] beschrieben sind. Besondere Bedeutung im Sinne der GoBD kommt dem mobilen Kassensystem plentyPOS zu. Die Kasse wird <<#_fachliche_und_technische_beschreibung_plentypos, in einem separaten Kapitel beschrieben>>.

Je nach App-Version, die laut der obigen Tabelle auf den mobilen Endgeräten installiert ist, können der Funktionsumfang der App und des Kassensystems plentyPOS hinsichtlich der Einstellungsmöglichkeiten und technischer Besonderheiten wie Speicherungsverhalten abweichen. Die vorliegenden Informationen sowie die Beschreibungen des <<#_fachliche_und_technische_beschreibung_plentypos, Kassensystems plentyPOS>> basieren stets auf dem Funktionsumfang der jeweils aktuell verfügbaren, neuesten Version der plentymarkets App. Bei der Erstellung der unternehmenseigenen Verfahrensdokumentation muss daher genau beachtet werden, welche Versionen der plentymarkets App genutzt werden. Informationen zum Funktionsumfang und Änderungen in einzelnen Versionen der plentymarkets App können link:https://forum.plentymarkets.com/c/app-pos[hier^] eingesehen werden.
