=== Fachliche und technische Beschreibung Benutzer und Benutzerrechte

Benutzer sind die Personen, die die Software plentymarkets bedienen. Die Benutzerrechte dienen dazu, einem Benutzer den Zugriff zu Bereichen oder Menüs der Software zu ermöglichen, zu beschränken oder zu verwehren. Benutzerrechte heißen in plentymarkets Berechtigungen. +
Die Benutzerrechte eines Benutzer in plentymarkets hängen zunächst von seinem Benutzerzugang ab. Jedem Benutzer muss ein Benutzerzugang zugeordnet werden. Die Benutzerzugänge sind systemseitig vorgegeben und können durch die Anwender nicht geändert werden. +

==== Benutzerzugänge

Folgende Benutzerzugänge gibt es in plentymarkets:

 * Admin
 * Backend
 * REST-API

Jeder Benutzerzugang ist mit unterschiedlichen Rechten versehen, die in den folgenden Kapiteln näher beschrieben werden. Die Vergabe von Rechten wird detailliert im Handbuch auf der Seite link:https://knowledge.plentymarkets.com/basics/arbeiten-mit-plentymarkets/benutzer-verwalten#90[Benutzerkonten verwalten^] beschrieben. +
Außerdem können optional Benutzerrollen angelegt werden. Mithilfe von Benutzerrollen lassen sich Rechte für mehrere Benutzer gleichzeitig vergeben. Die Benutzer müssen dafür der Rolle zugeordnet werden.

===== Benutzerzugang Admin

Der Benutzerzugang Admin verfügt über alle Rechte und dient zur Verwaltung des Systems. Benutzern dieses Zugangs können keine Rechte zusätzlich gewährt oder verwehrt werden. Sie verfügen pauschal über alle Rechte.

===== Benutzerzugang Backend

Der Benutzerzugang Backend verfügt standardmäßig über keine Rechte und bietet die größte Möglichkeit der individuellen Zuordnung von Rechten, die im Tab Berechtigung freitgeschaltet werden können.

===== Benutzerzugang REST-API

Für den Benutzerzugang REST-API können im Benutzerkonto REST-Calls freigeschaltet werden. Diese werden einzeln aktiviert. *Achtung*: Nutzern mit diesem Benutzerzugang wird der Zugriff auf das Backend verweigert.

Standardmäßig sind jedoch keine Zugriffsrechte für REST aktiviert. Es besteht lediglich die Möglichkeit, einem Benutzer des Zugangs REST-API per REST Zugriff auf Daten des Systems zu gewähren. Ein REST-API-Benutzer hat keinen Zugriff auf Daten über die Softwareoberfläche. +
Eine detaillierte Beschreibung der REST-Schnittstelle findet sich auf der link:https://developers.plentymarkets.com/[Developers-Seite^]. +

==== Rechte vergeben

Die Benutzerrechte in plentymarkets sind in die folgenden Bereiche unterteilt:

* Berechtigungen
* Menü-Sichtbarkeiten
* Plugins

Die Bereiche Berechtigungen und Menü-Sichtbarkeiten sind verknüpft, wodurch die gewählten Rechte für den jeweils anderen Bereich automatisch mit aktiviert werden.

Beim Vergeben von Berechtigungen gilt generell, dass das Aktivieren einer Berechtigung einer übergeordneten Ebene alle darunter liegenden Berechtigungen aktiviert. Das Entfernen einer Berechtigung einer übergeordneten Ebene entfernt analog alle darunter einsortieren Berechtigungen.

==== Liste der Admin- und Backend-Benutzer

Ergänzen Sie in der folgenden Tabelle, welche Personen über welchen Zugriff verfügen.

Folgende Personen sind Admin-Benutzer und verfügen über uneingeschränkten Zugriff auf das plentymarkets System

Person 1: (_Name, Vorname; ggf. Personalnummer, Organisationseinheit, Funktion im Unternehmen_) +
Person 2: (_Name, Vorname; ggf. Personalnummer, Organisationseinheit, Funktion im Unternehmen_) +
Person 3: (_Name, Vorname; ggf. Personalnummer, Organisationseinheit, Funktion im Unternehmen_)

Folgende Personen sind Backend-Benutzer und verfügen über eingeschränkten Zugriff auf das plentymarkets System:

Person 1: (_Name, Vorname; ggf. Personalnummer, Organisationseinheit, Funktion im Unternehmen_) +
Person 2: (_Name, Vorname; ggf. Personalnummer, Organisationseinheit, Funktion im Unternehmen_) +
Person 3: (_Name, Vorname; ggf. Personalnummer, Organisationseinheit, Funktion im Unternehmen_)

===== Berechtigungen

Mithilfe der Berechtigungen wird festgelegt welche tatsächlichen Daten ein Benutzer sieht. +
Die Sichtbarkeiten sind in 5 Abschnitte unterteilt, die in der folgenden Tabelle aufgeführt und erläutert sind.


[[tabelle-sichtbarkeiten]]
.Sichtbarkeiten in plentymarkets
[cols="1,3"]
|====
|*Sichtbarkeiten* |*Erläuterung*

|*Lager*
|Die Lager sind einzeln wählbar unterteilt nach Lagertypen.

|*Sichtbare Auftragsstatus*
|Die Auftragsstatus sind einzeln wählbar. Zur Auswahl stehen alle 29 Standard-Auftragsstatus sowie alle eigenen.

|*Setzbare Auftragsstatus*
|Die Auftragsstatus sind einzeln wählbar. Zur Auswahl stehen alle 29 Standard-Auftragsstatus sowie alle durch den Anwender eingetragenen Status.

|*Mandanten*
|Die Mandanten sind einzeln wählbar.

|*Ticketstatus*
|Die Ticketstatus sind einzeln wählbar. Zur Auswahl stehen alle durch den Anwender angelegten Ticketstatus.
|====

*_Hinweis_*: Die dort aufgeführten Sichtbarkeiten werden bald in das Menü *Einrichtung » Einstellungen » Benutzer » Rechte » Benutzer » Tab: Ressourcen* umgezogen.


==== Menü und REST-API-Rechte verwalten

Mit den Rechten wird festgelegt, welche Berechtigungen (REST-Rechte) ein Benutzer hat und welche Menüs und Plugins er sehen und öffnen kann. Außerdem kann bestimmt werden, welche Bearbeitungsmöglichkeiten der Benutzer im Menü haben soll.

===== Berechtigungen

In diesem Bereich werden die REST-Rechte verwaltet, die für bestimmte Aktionen benötigt werden.

* Artikel
* Aufträge
* Authorisierung
* Blog
* Buchhaltung
* CMS
* CRM
* Daten
* Editoren
* Einrichtung
* Kommentare
* Kunde
* Listing
* Markierung
* Märkte
* PIM
* plentyApp
* plentybase
* Plugins
* POS
* Prozesse
* Service
* Service-Center
* Stammdaten
* Start
* System
* Warenbestände
* Zahlenformat
* Zertifizierung

===== Menü-Sichtbarkeiten

In diesem Bereich wird die Abbildung von Menü und Systemeinstellungen verwaltet. Dort können die für den Benutzer sichtbaren Bereiche gewählt werden. Die REST-Rechte für die Menüpunkte werden automatisch gesetzt.

* Start
* Artikel
* Listings
* Waren
* CRM
* Aufträge
* Daten
* CMS
* Plugins
* Prozesse
* Einrichtung
* Support

===== Plugins

In diesem Bereich wird die Freigabe der Menü-Sichtbarkeit für Plugins verwaltet. Zunächst werden nur die Plugins mit ihren einzelnen Einträgen, jedoch ohne die korrekte Route, angezeigt. Die hier aufgelisteten Plugins dienen lediglich als Beispiel.

* EBICS
* PayPal
* FormatDesigner
* DHLShipping

===== REST-Rechte

Eine Auflistung aller verfügbaren REST-Rechte ist im <<anhang_rest-berechtigungen#, Anhang: REST-Berechtigungen>> zu finden.
