= Fachliche und technische Beschreibung des Moduls Artikel
//Inhalt geprüft am 14.10.2022
//ToDo - sobald die neue Artikel-UI als standard eingebunden wird, dann nochmal den Text prüfen und anpassen und Links auf Handbuchseiten bei Bedarf ändern

Artikeldaten werden in plentysystems zentral verwaltet.
Das heißt, dass Händler ihre Produktdaten im plentysystems ERP-System einpflegen.
Daraufhin können sie ihre Ware auf diversen <<#_fachliche_und_technische_beschreibung_des_moduls_plentychannel, Marktplätzen>>, im eigenen <<#_fachliche_und_technische_beschreibung_des_moduls_webshop, Webshop>> und im <<#_fachliche_und_technische_beschreibung_plentypos, stationären Laden>> verkaufen.

Müssen Daten, wie z.B. die Beschreibung oder der Preis eines Artikels, zu einem späteren Zeitpunkt geändert werden, muss der Händler diese Daten lediglich zentral im plentysystems ERP-System ändern.
Die Änderung kann automatisch auf allen genutzten Vertriebskanälen angezeigt werden.

[TIP]
.Ergänzen Sie Ihre eigenen Firmendaten
====
Dieses Kapitel enthält eine Mischung aus rein informativen Texten über die plentysystems Artikelverwaltung und aus Textblöcken, in denen Sie Informationen selbst ergänzen müssen. Gehen Sie dieses Kapitel sorgfältig durch und ergänzen Sie alle GoBD-relevante Informationen zu Ihrer eigenen Firma.
====

== Einführung in die plentysystems Artikelstruktur

Zu den Artikeldaten gehören Angaben wie z.B. Kategorien, Preise, Hersteller, Beschreibungstexte und Bilder. Um die Artikelverwaltung zu erleichtern, werden diese Daten auf drei Ebenen aufgeteilt:

* Systemeinstellungen
* Artikel
* Varianten

_Systemeinstellungen_ sind Angaben, die auf mehrere Artikel gleichzeitig zutreffen. Beispielsweise werden mehrere Artikel in einer Kategorie einsortiert oder von demselben Hersteller angefertigt. Systemeinstellungen werden einmalig in plentysystems gespeichert und daraufhin auf alle zutreffenden Artikel und Varianten angewandt.

_Artikel_ sind als Datencontainer zu verstehen. Sie beinhalten immer eine oder mehrere _Varianten_, d.h. eine oder mehrere verkaufbare Ausführungen eines Produkts. Wird zum Beispiel ein Hemd in den Größen 36, 38 und 40 angeboten, bilden alle Größen zusammen den Artikel. Jede einzelne Größe ist eine Variante dieses Artikels.

Zusammengefasst kann die Artikelstruktur in drei Datenebenen dargestellt werden:

[[tabelle-artikelstruktur]]
.Die plentysystems Artikelstruktur
[cols="1,2"]
|===
|*Ebene*|*Erläuterung*

|Systemeinstellungen|Einstellungen, die mit mehreren Artikeln oder Varianten verknüpft werden
|Artikel|Datencontainer zur Verwaltung von Varianten
|Varianten|Verkaufbare Ausführung eines Produkts
|===

=== Wie werden Varianten gebildet?

In plentysystems können Varianten entweder durch verschiedene Kombinationen aus <<#_einheiten, Einheit und Inhalt>> oder durch den Einsatz von <<#_attribute, Attributen>> erstellt werden:

[[tabelle-variantenerstellung]]
.Variantenerstellung
[cols="1,2"]
|===
|Methode|Erläuterung

|Kombination aus Einheit/Inhalt|Varianten unterscheiden sich durch die Menge und/oder Einheit, z.B.: +
- Seife: 100ml, 250ml, 500ml
|Kombination aus Attributwerten|Varianten unterscheiden sich durch die Attributwerte, z.B.: +
- Dekokissen: Farbe (rot, schwarz, grau) = 1 Attribut +
- T-Shirt: Farbe (grün, blau), Größe (S, M, L, XL) = 2 Attribute +
- Schuhe: Farbe (schwarz, braun), Größe (38, 39, 40), Breite (schmal, normal) = 3 Attribute
|===

Manche Produkte werden allerdings _nicht_ in unterschiedlichen Ausführungen verkauft, d.h. sie haben keine unterschiedliche Varianten. Da ein Artikel alleine aber keinen verkaufbaren Produkt ist, muss jeder Artikel mindestens auch eine Variante besitzen. In plentysystems ist es technisch nicht möglich, Artikel komplett ohne Varianten zu erstellen.

Die erste Variante eines Artikels wird als Hauptvariante bezeichnet. Hat ein Artikel mehrere Varianten, kann die Hauptvariante entweder selbst ein verkaufbares Produkt sein oder ähnlich wie der Artikel rein virtuell bestehen, um die weiteren Untervarianten des Artikels anhand von Vererbung zu verwalten.

=== Was ist Vererbung?

Die Hauptvariante eines Artikels unterscheidet sich von den Untervarianten dadurch, dass ihre Daten weitergegeben, also vererbt, werden können. Die Hauptvariante ist also eine Elternvariante, die bestimmte Daten an ihre Kinder vererbt.

Die Vererbungsfunktion ist standardmäßig aktiviert. Wenn eine neue Variante eines Artikels erstellt wird, erbt diese Variante Einstellungen der Hauptvariante, solange keine davon abweichenden Daten gespeichert werden.

[#100]
== Erstellung, Import und Export von Artikeldaten

Einerseits können Anwender Artikel- und Variantendaten link:https://knowledge.plentymarkets.com/de-de/manual/main/artikel/neue-artikel.html[manuell in plentysystems erstellen^].
Andererseits können sie auch Daten zwischen ihrem plentysystems System und anderen, externen Systeme austauschen.
Hierfür stehen link:https://knowledge.plentymarkets.com/de-de/manual/main/artikel/import-export-anlage.html[unterschiedliche Tools^] zur Verfügung.
Anwender können Artikeldatensätze z.B.:

* link:https://knowledge.plentymarkets.com/de-de/manual/main/maerkte/ebay-einrichten.html#11000[aus vorhandenen eBay-Listings importieren^].
* link:https://knowledge.plentymarkets.com/de-de/manual/main/daten/ElasticSync.html[in CSV-Dateien pflegen und anschließend importieren^].
* link:https://knowledge.plentymarkets.com/de-de/manual/main/daten/rest-api.html[aus externen Systemen mit der REST-API importieren^].
* link:https://knowledge.plentymarkets.com/de-de/manual/main/artikel/export.html[aus ihrem plentysystems System exportieren^].

Ergänzen Sie die Beschreibung des Ablaufs in Ihrem eigenen Unternehmen. Geben Sie an, wie Ihre Mitarbeiter Produktdaten anlegen und austauschen:

* [_Beschreibung des Ablaufs im Unternehmen einfügen_]

== Verwaltung von Artikeldaten

Das Menü *Artikel » Artikel bearbeiten* bietet eine Übersicht aller im System gespeicherten Artikel- und Variantendatensätze. Welche Daten in der Übersicht angezeigt werden, ist von den gesetzten Filtern abhängig.

In diesem Menü können Artikel- und Variantendaten eingesehen und manuell geändert werden.

=== Artikel- und Varianten-IDs

Artikel und Varianten werden durch eindeutige IDs in plentysystems gekennzeichnet. Diese IDs werden beim Erstellen des Artikels bzw. der Variante erzeugt und sind systemweit eindeutig.

_Artikel-IDs_ können von Anwendern frei gewählt und manuell geändert werden. plentysystems rät jedoch davon ab, da aufgrund der Komplexität der Daten und Datenverknüpfungen Folgefehler entstehen können. Wird bei der Artikelanlage keine ID angegeben, wird beim Speichern des neuen Artikels automatisch die nächste verfügbare ID vergeben. Bei der automatisch vergebenen ID handelt es sich um einen eindeutigen Wert, der automatisch schrittweise erhöht wird.

_Varianten-IDs_ können nicht von Anwendern beeinflusst und nicht im Nachhinein geändert werden. Bei der Varianten-ID handelt es sich um einen fortlaufenden, eindeutigen Wert, der automatisch schrittweise erhöht wird.

Ergänzen Sie die Beschreibung des Ablaufs in Ihrem eigenen Unternehmen. Geben Sie an, wie Ihre Mitarbeiter Artikel-IDs wählen:

* [_Beschreibung des Ablaufs im Unternehmen einfügen_]

=== Änderungen nachvollziehen

==== Änderungshistorie
//Der gleiche Inhalt findet sich auch im Kapitel Auftragsabwicklung

Mit Hilfe der link:https://knowledge.plentymarkets.com/de-de/manual/main/artikel/aenderungen.html[Änderungshistorie^] können Anwender Änderungen an rechnungsrelevanten Daten verfolgen. Zum Beispiel können Anwender den gesamten Lebensweg eines Artikels oder eines Auftrags nachvollziehen.
Die Änderungshistorie setzt sich aus den folgenden Teilen zusammen:

* *_Suche_*: Änderungsaufzeichnungen, die weniger als sechs Monate zurückliegen, können live durchsucht werden.
* *_Archiv_*: Nach Ablauf der sechs Monate werden die Daten in ein Archiv verschoben. Dort sind die Daten weiterhin zugänglich, können jedoch nicht mehr durchsucht werden.
Die Änderungen werden 11 Jahre archiviert.
Anwender können die Archivdateien anfordern und herunterladen.

Die Änderungshistorie ist manipulationssicher und vertrauenswürdig in dem Sinne, dass Anwender die Einträge weder ändern noch löschen können.
Änderungen können lediglich abgerufen und durchsucht werden.

Standardmäßig ist die Änderungshistorie ausgeschaltet.
Anwender müssen sie also selbst aktivieren.
Dabei können Anwender alle GoBD-relevanten Einstellungen gleichzeitig aktivieren.
Alternativ können Anwender selbst entscheiden:

* welche Datenfelder protokolliert werden sollen (GoBD-relevante Datenfelder sind entsprechend gekennzeichnet).
* ob das Archiv aktiviert werden soll, d.h. ob die protokollierten Änderungen 11 Jahre lang abrufbar sein sollen.

==== Zeitstempel

In plentysystems werden jeweils beim Erstellen und Ändern von Artikel- und Variantendaten Zeitstempel erzeugt. Der Zeitstempel der letzten Änderung wird bei jeder Änderung der Daten entsprechend aktualisiert.
Für Artikel sind diese Zeitstempel im Menü *Artikel » Artikel bearbeiten » Artikel öffnen » Tab: Global* zu finden, für Varianten im Menü *Artikel » Artikel bearbeiten » Artikel öffnen » Tab: [Varianten-ID]*.

Einige verknüpfte Entitäten haben einen eigenen Timestamp, der bei Änderungen aktualisiert wird. Timestamps sind nicht in der Variante sichtbar.

==== Sonstige Möglichkeiten

Anwender können Änderungen an Artikel- und Variantendaten auch selbst erfassen und dokumentieren.
Zu diesem Zweck können Anwender diverse link:https://knowledge.plentymarkets.com/de-de/manual/main/daten/FormatDesigner.html[Artikel- und Variantendaten exportieren^].

Ergänzen Sie die Beschreibung des Ablaufs in Ihrem eigenen Unternehmen. Geben Sie an, wie Ihre Mitarbeiter Änderungen an Artikel- und Variantendaten protokollieren:

* [_Beschreibung des Ablaufs im Unternehmen einfügen_]

Das Löschen von Artikeln und Varianten wird lediglich vom Anbieter des ERP-Systems plentysystems protokolliert.

=== Preise
==== Was sind Verkaufspreise?

In plentysystems wird zwischen Verkaufspreisen und Preisen unterschieden.
Die Verkaufspreise sind Datencontainer (ähnlich wie Artikel es auch sind).
Sie ermöglichen das zentrale Verwalten von Bedingungen, die auf Preise zutreffen sollen.
Verkaufspreise bestimmen also link:https://knowledge.plentymarkets.com/de-de/manual/main/artikel/preise.html[in welchen Situationen^] eine Variante zu einem bestimmten Preis verkauft wird.

Verkaufspreise gehören zu den zentral gespeicherten <<#_einführung_in_die_plentymarkets_artikelstruktur, Systemeinstellungen>>. Nach der Erstellung werden Verkaufspreise mit einzelnen Varianten verknüpft.

In einem neu angelegten System sind standardmäßig zwei Verkaufspreise mit den IDs 1 und 2 hinterlegt.
Anwender können diese Standard-Verkaufspreise ändern, löschen und/oder beliebig viele neue Verkaufspreise erstellen. Die vom Anwender erstellten Verkaufspreise erhalten eine fortlaufende ID beginnend mit ID 3. Bei dieser ID handelt es sich um einen sogenannten Auto-Increment-Wert, der durch das System vergeben und nicht geändert werden kann.

==== Was sind Preise?

Im Gegensatz zu dem Verkaufspreis ist der Preis der tatsächliche Geldbetrag, zu dem eine Variante verkauft wird, wenn die durch den Verkaufspreis definierten Bedingungen erfüllt sind. Einer Variante können beliebig viele Verkaufspreise zugeordnet werden. Pro Verkaufspreis wird dann ein Preis direkt an der Variante gespeichert.

Standardmäßig werden die Kombinationen aus Verkaufspreis und Preis von der Hauptvariante an die Untervarianten des Artikels vererbt.
Das bedeutet, dass allen Varianten eines Artikels standardmäßig dieselben Kombinationen aus Verkaufspreis und Preis zugeordnet werden.

Intern arbeitet plentysystems mit Bruttopreisen.
Anwender können zwar entscheiden, ob Brutto- oder Nettopreise im Artikeldatensatz angezeigt werden sollen.
Diese Einstellung betrifft jedoch nur die Anzeige.
Es werden _ausschließlich_ Bruttopreise in der Datenbank gespeichert.

==== Wie können Preisdaten geändert werden?

Die Preise einer einzigen Variante können geändert werden, z.B.:

* durch die manuelle link:https://knowledge.plentymarkets.com/de-de/manual/main/artikel/import-export-anlage-verzeichnis.html#240[Eingabe eines neuen Preises^].
* durch das Aktivieren oder Deaktivieren der Vererbung.
* durch die Änderung eines Preises der Hauptvariante bei aktiver Vererbung.
* durch Verknüpfung mit einer <<#_preiskalkulationen, Preiskalkulation>>.

Die Preise mehrere Varianten können gleichzeitig geändert werden, z.B.:

* über die link:https://knowledge.plentymarkets.com/de-de/manual/main/artikel/massenbearbeitung.html#300[Varianten-Gruppenfunktion^].
* über die link:https://knowledge.plentymarkets.com/de-de/manual/main/artikel/massenbearbeitung.html#600[Stapelverarbeitung^].
* durch den link:https://knowledge.plentymarkets.com/de-de/manual/main/daten/ElasticSync.html[Import von Preisdaten^].
* per link:https://knowledge.plentymarkets.com/de-de/manual/main/daten/rest-api.html[REST-API^].

Preisänderungen können in der plentysystems <<#_änderungshistorie, Änderungshistorie>> protokolliert werden. Dies setzt voraus, dass der Anwender die Änderungshistorie und die relevanten Datenfelder aktiviert hat.
Alternativ können Anwender GoBD-relevante Änderungen selbst erfassen und dokumentieren. Ergänzen Sie die Beschreibung des Ablaufs in Ihrem eigenen Unternehmen. Geben Sie an, wie Ihre Mitarbeiter GoBD-relevante Änderungen erfassen:

* [_Beschreibung des Ablaufs im Unternehmen einfügen_]

==== Preiskalkulationen

link:https://knowledge.plentymarkets.com/de-de/manual/main/artikel/preise.html#1000[Preiskalkulationen^] gehören zu den zentral gespeicherten <<#_einführung_in_die_plentymarkets_artikelstruktur, Systemeinstellungen>>.
Sie dienen dazu, die Geldpreise von Varianten automatisch anhand bestimmter Kriterien zu berechnen und zu aktualisieren.

*_Beispiel_*: Anwender können mit dem Einkaufspreis des Artikels starten und dann die Transportkosten, Lagerkosten und Steuern hinzufügen. Schließlich können Anwender eine Gewinnspanne von 7% oben drauf legen.

_Im ersten Schritt_ erstellen Anwender individuelle Preiskalkulationen.
Diese können nur manuell erstellt und bearbeitet werden.

_Im zweiten Schritt_ bestimmen Anwender, für welche Varianten die Preiskalkulation verwendet werden soll.
Dies geschieht z.B. durch:

* die link:https://knowledge.plentymarkets.com/de-de/manual/main/artikel/import-export-anlage-verzeichnis.html#240[manuelle Verknüpfung^] der Preiskalkulation mit einer Variation.
* den link:https://knowledge.plentymarkets.com/de-de/manual/main/daten/elasticSync-artikel.html#2300[Import^] von Preiskalkulationsverknüpfungen.
* die Verwendung der link:https://knowledge.plentymarkets.com/de-de/manual/main/artikel/massenbearbeitung.html#300[Varianten-Gruppenfunktion^].

Bei aktivierter Vererbung werden diese Preise wie andere Preise auch von der Hauptvariante an die anderen Varianten des Artikels vererbt.

Änderungen, die Anwender an Preiskalkulationen vornehmen, werden nicht protokolliert. Daher müssen Anwender GoBD-relevante Änderungen selbst erfassen und dokumentieren. Ergänzen Sie die Beschreibung des Ablaufs in Ihrem eigenen Unternehmen. Geben Sie an, wie Ihre Mitarbeiter GoBD-relevante Änderungen erfassen:

* [_Beschreibung des Ablaufs im Unternehmen einfügen_]

==== Welche Rabatte auf Preise sind möglich?

In plentysystems sind link:https://knowledge.plentymarkets.com/de-de/manual/main/crm/vorbereitende-einstellungen.html#rabattsystem-nutzen[Rabatte^] im Sinne von _Preisnachlässen_ zu verstehen. Rabatte können beispielsweise verwendet werden, um:

* bestimmten Kundenklassen einen günstigeren Preis anzubieten.
* die Artikel einer bestimmten link:https://knowledge.plentymarkets.com/de-de/manual/main/artikel/kategorien.html#1530[Kategorie^] zu vergünstigen.
* bestimmte Zahlungsarten attraktiver zu machen.
* beschädigte Ware manuell link:https://knowledge.plentymarkets.com/de-de/manual/main/pos/pos-kassenbenutzer.html#140[an der Kasse im stationären Laden^] zu vergünstigen.
* werbliche Aktionen durchzuführen, z.B. 20% auf alles außer Tiernahrung. Solche Aktionen werden mit sogenannten link:https://knowledge.plentymarkets.com/de-de/manual/main/auftraege/gutscheine.html[Aktionsgutscheinen^] durchgeführt.

Artikel können im Menü *Artikel » Artikel bearbeiten » Artikel öffnen » Tab: Global* mit der Option link:https://knowledge.plentymarkets.com/de-de/manual/main/artikel/import-export-anlage-verzeichnis.html#40[Aktionsgutschein/POS-Rabatt^] von Rabatten an der plentyPOS Kasse ausgeschlossen werden. Das bedeutet, dass das Kassenpersonal keinen manuellen Rabatt eingeben kann. Auch Kundenklassenrabatte und Aktionsrabatte sind für diese nicht rabattfähigen Artikel ungültig.

==== Anzeige des niedrigsten Preises der letzten 30 Tage

plentysystems enthält eine link:https://knowledge.plentymarkets.com/de-de/manual/main/artikel/verzeichnis.html#340[Niedrigstpreisfunktion], die es Händlern ermöglicht, die Anforderungen, die in § 11 (1) der link:https://www.bmwk.de/Redaktion/DE/Downloads/P-R/novelle-der-preisangabenverordnung-pangv.pdf?__blob=publicationFile&v=4[Preisangabenverordnung] festgelegt sind, zu erfüllen.
Händler können den niedrigsten Preis manuell in plentysystems eingeben, den Preis importieren oder plentysystems den niedrigsten Preis automatisch ermitteln lassen.
Daraufhin kann der niedrigste Preis im Webshop angezeigt werden.

=== Kategorien
//aktualisieren wenn Limits da sind

In plentysystems können link:https://knowledge.plentymarkets.com/de-de/manual/main/artikel/kategorien.html[Kategorien^] sowohl im Sinne von _Warengruppen_ als auch im Sinne von den _Content-Seiten_ eines Webshops verstanden werden. In diesem Kapitel sind mit Kategorien Warengruppen gemeint. Sie dienen dazu, Produkte übersichtlich zu gruppieren.

Varianten können beliebig vielen Kategorien zugeordnet werden. Allerdings muss bereits bei der Erstellung einer neuen Variante eine Standardkategorie festgelegt werden. Diese Standardkategorie kann jederzeit geändert werden, allerdings ist es nicht möglich, Varianten ohne Standardkategorie zu pflegen.

Kategorien haben steuerrechtliche Relevanz, da ein oder mehrere Mengenrabatte für einzelne Kategorien im Menü *Einrichtung » Mandant » [Mandant öffnen] » Kategorierabatte* gespeichert werden können. Pro Kategorie sind bis zu drei Mengenrabatte möglich. Diese Rabatte werden automatisch angewendet, wenn Kunden die rabattfähige Menge an Varianten aus einer Kategorie erreichen oder überschreiten. Sie gelten jedoch nur für die Standardkategorie einer Variante. Diese Kategorierabatte können nur manuell im plentysystems Backend gespeichert werden. Ein Import oder Export dieser Konfiguration ist nicht möglich.

=== Einheiten

link:https://knowledge.plentymarkets.com/de-de/manual/main/artikel/einheiten.html[Einheiten^] gehören zu den zentral gespeicherten <<#_einführung_in_die_plentymarkets_artikelstruktur, Systemeinstellungen>>. Sie dienen dazu:

* verschiedene Varianten eines Artikels zu bilden.
* den Inhalt von Varianten zu definieren. Hierfür werden Einheiten mit den Varianten verknüpft und Mengenangaben hinterlegt.
* den Grundpreis gemäß der Grundpreisverordnung zu errechnen. Der Grundpreis wird auf Verkaufskanälen ausgegeben, wenn an der Variante die Option *Grundpreisanzeige* aktiviert ist. Auch bei Produkten, die der Grundpreisverordnung unterliegen, müssen Anwender diese Einstellung selbst vornehmen.

Standardmäßig sind 52 Einheiten nach ISO-Code in plentysystems Systemen gespeichert. Anwender können jedoch im Menü *Einrichtung » Artikel » Einheiten* auch eigene Einheiten erstellen.

=== Attribute

link:https://knowledge.plentymarkets.com/de-de/manual/main/artikel/attribute.html[Attribute^] gehören zu den zentral gespeicherten <<#_einführung_in_die_plentymarkets_artikelstruktur, Systemeinstellungen>>. Sie dienen dazu:

* Produkte zu charakterisieren.
* verschiedene Varianten eines Artikels zu bilden.

Im Menü *Einrichtung » Artikel » Attribute* können beliebig viele Attribute angelegt werden. Pro Attribut können außerdem beliebig viele Attributwerte erstellt werden.

[[tabelle-attribute]]
.Attribute und Attributwerte
[cols="1,3"]
|===
|Beispiel: Attribut|Beispiel: Attributwerte

|Farbe|rot, grün, blau
|Größe|36, 38, 40
|===

=== Eigenschaften und Merkmale

In plentysystems ist es auch möglich, Produkte zu charakterisieren, ohne dabei Varianten zu bilden.
Hierfür werden link:https://knowledge.plentymarkets.com/de-de/manual/main/artikel/eigenschaften.html[Eigenschaften und Merkmale] verwendet.
Darüber lassen sich Features, z.B. technische Details wie “Bluetooth” oder “WLAN” abbilden.
Eigenschaften und Merkmale sind nicht an den Warenbestand gekoppelt.

Sowohl Eigenschaften als auch Merkmale gehören zu den zentral gespeicherten <<#_einführung_in_die_plentymarkets_artikelstruktur, Systemeinstellungen>>.
Nach der Erstellung werden Merkmale allerdings auf der Artikelebene verknüpft und Eigenschaften auf der Variantenebene.

Eigenschaften und Merkmalen kommen eine besondere Bedeutung im Sinne der GoBD zu, da sie Aufpreise definieren können.
Anwender tragen einen Wert ein, wenn sie für das Merkmal/die Eigenschaft einen Aufpreis berechnen möchten.
Dieser Wert wird automatisch zum Artikelpreis addiert.
Anwender entscheiden auch, ob der Aufpreis besteuert werden soll und falls ja, welcher Steuersatz gelten soll.
link:https://knowledge.plentymarkets.com/de-de/manual/main/artikel/personalisierte-artikel.html#verpflichtend-vorausgewaehlt[Eine mögliche Anwendung] ist zum Beispiel die Darstellung von Pfandbeträgen, bei denen keine Mehrwertsteuer angewendet wird.

Der Aufschlag kann direkt in der Eigenschaft/im Merkmal gespeichert werden.
Alternativ kann auch ein produktspezifischer Aufpreis direkt im Artikel/Variante gespeichert werden.

Änderungen an Eigenschaften/Merkmalen und daraus resultierende Preisänderungen werden nicht protokolliert. Die Protokollierung solcher Änderungen obliegt dem Anwender.
Änderungen am produktspezifischen Aufpreis werden in der Änderungshistorie protokolliert.
Dies setzt voraus, dass der Anwender die Änderungshistorie und die relevanten Datenfelder aktiviert hat. Alternativ können Anwender GoBD-relevante Änderungen selbst erfassen und dokumentieren.
Ergänzen Sie die Beschreibung des Ablaufs in Ihrem eigenen Unternehmen. Geben Sie an, wie Ihre Mitarbeiter GoBD-relevante Änderungen erfassen:

* [_Beschreibung des Ablaufs im Unternehmen einfügen_]

=== Versandprofile

<<#_fachliche_und_technische_beschreibung_versandabwicklung, Versandprofile>> gehören zu den zentral gespeicherten <<#_einführung_in_die_plentymarkets_artikelstruktur, Systemeinstellungen>>. Sie beinhalten die vom Händler angebotenen Versandservices und Portokosten. Nach der Erstellung werden Versandprofile mit Artikeln verknüpft.

Die Versandkosten einer Variante ergeben sich also aus der Konfiguration der mit dem Artikel verknüpften Versandprofile. Um höhere Portokosten, z.B. für große oder sperrige Güter, zu berechnen, können an der Variante zwei zusätzliche Portoaufschläge definiert werden.

Beim Erstellen eines neuen Artikels ist standardmäßig kein Versandprofil aktiviert. Pro Artikel sollte jedoch mindestens ein Versandprofil aktiviert werden, da sonst ungewollte Effekte bei der Versandkostenberechnung auftreten können.

=== Hersteller

link:https://knowledge.plentymarkets.com/de-de/manual/main/artikel/hersteller.html[Herstellerdaten] gehören zu den zentral gespeicherten <<#_einführung_in_die_plentymarkets_artikelstruktur, Systemeinstellungen>>.
Im zentralen Herstellerdatensatz werden Name, Kontaktdaten und marktplatzspezifische IDs des Herstellers gespeichert.
Nach der Erstellung werden Hersteller mit Artikeln verknüpft.

plentysystems vergibt jedem Herstellerdatensatz automatisch eine ID.
Bei dieser ID handelt es sich um einen eindeutigen Auto-Increment-Wert, der vom Anwender nicht beeinflusst werden kann.
Neue plentysystems Systeme werden mit zwei Herstellerdatensätzen geliefert, die die IDs 1 und 2 haben.
Anwender können diese Herstellerdatensätze ändern, löschen und/oder beliebig viele neue Datensätze erstellen.
Die vom Anwender erstellten Datensätze erhalten eine fortlaufende ID beginnend mit ID 3.

Manche Hersteller erheben für den Verkauf auf bestimmten Kanälen Provisionen.
Um dieser Forderung Rechnung zu tragen, kann am Hersteller ein Provisionsbetrag in Prozent gespeichert werden.
Provisionen werden immer für eine bestimmte Kombination aus link:https://knowledge.plentymarkets.com/de-de/manual/main/webshop/mandanten-verwalten.html[Mandant^] und link:https://knowledge.plentymarkets.com/de-de/manual/main/auftraege/auftragsherkunft.html[Herkunft^] gespeichert.

Herstellerprovisionen können nur manuell im Menü *Einrichtung » Artikel » Hersteller* hinterlegt werden. Änderungen an den Einstellungen für Herstellerprovisionen werden nicht protokolliert. Ergänzen Sie die Beschreibung des Ablaufs in Ihrem eigenen Unternehmen. Geben Sie an, wie Ihre Mitarbeiter GoBD-relevante Änderungen erfassen:

* [_Beschreibung des Ablaufs im Unternehmen einfügen_]

== Multipacks, Artikelpakete und Artikelsets

Anwender haben drei verschiedene Möglichkeiten, Produkte zu kombinieren und als eine Verkaufseinheit anzubieten. Die folgende Tabelle vergleicht die Möglichkeiten und erläutert sie beispielhaft.

[[tabelle-multipacks-pakete-sets]]
.Produkte kombinieren und als Verkaufseinheit anbieten
[cols="1,4a"]
|===
|Art |Erläuterung

|link:https://knowledge.plentymarkets.com/de-de/manual/main/artikel/multipacks-pakete-sets-verwalten.html#1000[Multipack^]
|*_Beispiel_*: 1 Flasche Wasser, eine Packung mit 6 Flaschen und eine Packung mit 12 Flaschen.

*_Technische Angaben_*:

* Multipacks sind verschiedene Stückzahlen derselben Variante.
* Die Hauptvariante entspricht der kleinsten Verkaufseinheit des Produkts, z.B. 1 Flasche.
* Alle weiteren Varianten sind Kombinationen dieser kleinsten Verkaufseinheit, z.B. 6 oder 12 Flaschen.
* <<#_preise, Preise>> funktionieren genauso wie bei normalen Artikeln. Verkäufer werden allerdings empfohlen, die Vererbungsfunktion zu deaktivieren und stattdessen für jede Variante einen eigenen Preis zu speichern.
* Bestand wird nur an der Hauptvariante verwaltet.

|link:https://knowledge.plentymarkets.com/de-de/manual/main/artikel/multipacks-pakete-sets-verwalten.html#2000[Paket^]
|*_Beispiel_*: Ein Bartpflege-Kit bestehend aus einer Schere, einer Bürste, Bartöl und Bartwachs.

*_Technische Angaben_*:

* Pakete bestehen aus unterschiedlichen Varianten, die zusammengefasst und zu einem Paketpreis angeboten werden.
* Bestellt werden kann nur das komplette Paket. Die einzelnen Bestandteile können nicht gewählt werden.
* Es ist möglich, Varianten mit unterschiedlichen Steuersätzen zusammen in einem Paket anzubieten.
* Es ist auch möglich, den Paketpreis günstiger als die Summe der Einzelpreise zu definieren.
* Anwender geben den Paketpreis und den Umsatzsteuersatz am Artikeldatensatz selbst ein. Preis und Umsatzsteuersatz werden _nicht_ automatisch von plentysystems anhand der Bestandteile berechnet.
* Der Einkaufspreis kann dagegen automatisch auf Grundlage der Bestandteile berechnet werden.

|link:https://knowledge.plentymarkets.com/de-de/manual/main/artikel/multipacks-pakete-sets-verwalten.html#3000[Set^]
|*_Beispiel_*: Eine Fußballuniform bestehend aus einem Trikot, Shorts und Socken. Der Endkunde stellt sich seine eigene Uniform zusammen, indem er die gewünschte Größe und Farbe für jede der drei Komponenten auswählt.

*_Technische Angaben_*:

* Sets bestehen aus mehreren Artikeln (Trikot, Shorts, Socken).
* Bei der Bestellung können Endkunden für jeden Artikel die gewünschte Variante wählen (Größe, Farbe).
* Die Hauptvariante selbst ist virtuell, kann also nicht verkauft werden.
* Für Sets werden keine Festpreise gespeichert, da der Verkäufer im Vorfeld nicht weiß, welche Kombination verkauft wird.
Stattdessen prüft plentysystems regelmäßig die Preise aller im Set enthaltenen Varianten und ermittelt die günstigste kaufbare Kombination (der sogenannte "Ab-Preis"). plentysystems prüft die Preise:
** wenn ein Bestandteil zu einem Set hinzugefügt wird.
** wenn ein Bestandteil aus einem Set gelöscht wird.
** wenn der "Ab-Preis" manuell aktualisiert wird.
** jede Nacht.
* Es ist möglich, ein Set günstiger als die Summe seiner Bestandteile zu machen. Verkäufer können dies auf zwei Wegen tun:
** Einerseits könnten Händler günstigere Geldbeträge für den Set-Verkaufspreis speichern als für den normalen Verkaufspreis.
** Andererseits könnten Händler einen prozentualen Rabatt eingeben, der für das gesamte Set gilt.
|===

Ergänzen Sie die Beschreibung des Ablaufs in Ihrem eigenen Unternehmen.
Geben Sie an, wie Preise für Multipacks, Pakete und Sets verwaltet werden.
Geben Sie an, wie Ihre Mitarbeiter GoBD-relevante Änderungen erfassen:

* [_Beschreibung des Ablaufs im Unternehmen einfügen_]

== Backup

Anwender können eine link:https://knowledge.plentymarkets.com/de-de/manual/main/daten/backup.html[Backup-Funktion^] nutzen, um Artikel- und Variantendaten in der Datenbank auf einen früheren Stand zurückzusetzen oder um gelöschte Daten wiederherzustellen.

Im Menü *Einrichtung » Einstellungen » Hosting » Backup* finden Anwender eine Übersicht der Backups, die in den letzten Monate automatisch erstellt wurden. Anwender können diese Backups entweder einspielen oder als .sql.gz-Dateien herunterladen.
