= Fachliche und technische Beschreibung des Moduls Plugins

Mit dem Plugin-Modul ist es möglich, das PlentyONE System um zusätzliche Funktionen zu erweitern und individuell zu gestalten. Bei Plugins handelt es sich um Erweiterungen des PlentyONE Systems. So ist es etwa möglich, neue Zahlungsarten zu einem Webshop oder eine neue Schnittstelle zum Backend hinzuzufügen.

Plugins können über verschiedene Quellen im System eingebunden werden:

    * https://marketplace.plentymarkets.com/[plentyMarketplace^]
    * Git
    * https://marketplace.plentymarkets.com/plenty-tools/plentydevtool_6652[plentyDevTool^]

Nach dem Einbinden müssen Plugins in einem Plugin-Set installiert, aktiviert und bereitgestellt werden, damit ihr Code ausgeführt wird. Weitere Informationen zu diesen Schritten sind auf der Handbuchseite https://knowledge.plentymarkets.com/de-de/manual/main/plugins/hinzugefuegte-plugins-installieren[Hinzugefügte Plugins installieren^] beschrieben.

== plentyMarketplace

Auf plentyMarketplace können Plugins entweder entgeltlich oder unentgeltlich erworben werden. Diese Plugins wurden entweder von PlentyONE oder Drittanbietern entwickelt. 

Je nach Anbieter ist es möglich, Plugins für einen Zeitraum von 30 Tagen kostenlos zu testen oder sie zu abonnieren. Bei Abonnements kann das Zahlungsintervall zwischen monatlich, 3-monatlich, halbjährlich und jährlich variieren, je nach Ermessen des Anbieters. Außerdem ist es möglich, einige Funktionen des Plugins kostenlos und andere kostenpflichtig anzubieten. Anbieter definieren diese Modelle in der Marketplace-JSON.

Einzelheiten zu den Arten von angebotenen Plugins sowie den verschiedenen Kaufoptionen sind auf der Handbuchseite https://knowledge.plentymarkets.com/de-de/manual/main/plugins/plugins-system-hinzufuegen#marketplace-plugins[Plugins dem System hinzufügen^] beschrieben. Einzelheiten zur Implementierung des verschiedenen Modelle sind auf der Entwicklerseite https://developers.plentymarkets.com/marketplace/plugin-pricing-models[Plugin pricing models^] und dem zugehörigen Tutorial https://developers.plentymarkets.com/tutorials/marketplace-subscriptions[Marketplace subscription plugins^] beschrieben.

Wenn ein Plugin erworben wird, wird von PlentyONE automatisch ein Auftrag an der entsprechenden Kunden-ID hinterlegt (siehe Kapitel <<#_kontakt_ids>>). Sind einer Kunden-ID mehrere PlentyONE Systeme zugeordnet, steht das Plugin in all diesen Systemen zu Verfügung.

Eine Liste aller auf plentyMarketplace angebotenen Plugins ist im Anhang plentyMarketplace-Plugins aufgeführt.

== Git

Plugins können dem System über Git-Dienste wie GitHub und Bitbucket hinzugefügt werden. Das Repository, das hinzugefügt werden soll, muss eine https://developers.plentymarkets.com/dev-doc/plugin-information[valide Plugin-JSON^] enthalten.

Wenn ein Plugin über Git eingebunden wird, werden die zugehörigen Dateien auf AWS (siehe Kapitel <<#_aws_cloud_aufbau_sicherheitsarchitektur_speicherkonzept_löschkonzept>>) in einem Unterverzeichnis gespeichert.

== plentyDevTool

Es ist möglich, dem System ein lokales Verzeichnis als Plugin hinzuzufügen. Hierfür muss die Software plentyDevTool verwendet werden. Das Verzeichnis, das hinzugefügt werden soll, muss eine https://developers.plentymarkets.com/dev-doc/plugin-information[valide Plugin-JSON^] enthalten.

Wenn ein lokales Plugin eingebunden wird, werden die zugehörigen Dateien auf AWS in einem Unterverzeichnis gespeichert.

== Plugins installieren, aktivieren und bereitstellen

Bevor sie verwendet werden können, müssen Plugins vom Anwender installiert, aktiviert und bereitgestellt werden.

Beim Installieren von Plugins, die auf plentyMarketplace erworben wurden, wird der beim Kauf angelegte Auftrag von PlentyONE überprüft. Anschließend werden die Dateien des Plugins in das AWS-Verzeichnis des Kunden kopiert. Je nachdem, ob das Plugin in der Plugin-JSON als Open Source oder Closed Source definiert wurde, werden die Dateien in das Unterverzeichnis Public oder Private kopiert.

Nach dem Installieren können Anwender Plugins innerhalb eines Plugin-Sets aktiviert und deaktiviert werden. Nur aktivierte Plugins werden beim Bereitstellen berücksichtigt. Nachdem ein Plugin bereitgestellt wurde, kann es aktiviert und deaktiviert werden. Wenn ein Plugin bereitgestellt und deaktiviert ist, wird der Code des Plugins nicht ausgeführt. Damit der Code ausgeführt wird, muss das Plugin aber nicht erneut bereitgestellt, sondern nur aktiviert werden.

Wenn ein Plugin-Set bereitgestellt wird, werden folgenden Schritte ausgeführt:

    * *In das Bereitstellungsverzeichnis kopieren*: Die aktiven Plugins werden von den verschiedenen Speicherorten in ein gemeinsames Verzeichnis kopiert.
    * *Code überprüfen*: Der gesammelte Code der kopierten Plugins wird überprüft.
    * *In das Build-Verzeichnis kopieren*: Wurde der Code erfolgreich überprüft, wird ein Build-Verzeichnis erstellt. Die Plugins werden in das Build-Verzeichnis kopiert.
    * *Ressourcen veröffentlichen*: Alle SCSS-Dateien werden kompiliert. Alle CSS-, JS-, UI, Bild- und Sprachdateien werden in ein öffentliches Bucket auf AWS S3 und zu Amazon CloudFront übertragen.
    * *Cache zurücksetzen*: Der Cache für aktive Plugins wird zurückgesetzt.
    * *Datenbanken migrieren*: Wenn ein aktives Plugin eine Datenbank verwendet, wird eine Migration durchgeführt.
    * *Konfigurationen bereinigen*: Die verfügbaren Konfigurationen aller Plugins werden mit den in der Datenbank gespeicherten Daten verglichen. Gibt es Abweichungen, werden die Konfigurationen entsprechend aktualisiert.

== Konfiguration

Teilweise müssen Einstellungen für Plugins vorgenommen oder Verknüpfungen mit Containern angelegt werden. Einzelheiten zum Einrichten von Einstellungen und Verknüpfungen sind auf der Handbuchseite https://knowledge.plentymarkets.com/de-de/manual/main/plugins/installierte-plugins-konfigurieren[Installierte Plugins konfigurieren^] beschrieben.

Alle notwendigen Schritte zur Einrichtung werden vom Anwender anhand einer vom Anbieter des Plugins zu Verfügung gestellten Anleitung vorgenommen.
