= Fachliche und technische Beschreibung E-Mail-Versand

plentysystems selbst ist kein E-Mail-Provider und bietet auch keine Services eines E-Mail-Providers an. Der Anwender bestimmt, welchen Anbieter er mit dem plentysystems System für den Versand seiner E-Mails verknüpft.

Alle E-Mails, die über das System versendet werden, basieren auf E-Mail-Vorlagen, die der Anwender einrichten muss. Einige E-Mail-Vorlagen sind bereits im System vorhanden – diese kann der Anwender gemäß seiner Bedürfnisse anpassen. Die Signatur beispielsweise muss der Anwender anpassen, da standardmäßig eine Mustersignatur eingestellt ist. Der Anwender kann beliebig viele E-Mail-Vorlagen erstellen.

Die E-Mail-Vorlagen können mit bestimmten Ereignissen, z.B. wenn eine neue Bestellung im Webshop des Anwenders eingeht oder wenn ein Kunde den Newsletter abonniert hat, verknüpft werden, damit das System automatisch E-Mails aus den Vorlagen erstellt und diese an die Kunden des Anwenders versendet. Ein weiteres Szenario wäre, dass der Anwender z.B. seine Mitarbeiter im Lager informiert, damit diese die Ware für den Versand vorbereiten. Das passende Ereignis dazu könnte der Zahlungseingang durch den Kunden sein.

Der Anwender legt fest, welche E-Mail wann automatisch versendet werden soll.

== E-Mail-Server-Zugangsdaten

Der Anwender muss die Zugangsdaten des E-Mail-Postfachs, aus dem er die E-Mails versenden möchte, im System speichern, damit das System E-Mails wie z.B. Auftragsbestätigungen und Versandbestätigungen von dieser E-Mail-Adresse versenden kann. Sind keine Daten gespeichert, kann kein E-Mail-Versand stattfinden.

Der Anwender muss den Postausgangsserver, den Port sowie die verfügbare Verschlüsselungsmethode wie von seinem E-Mail-Provider angegeben eingeben.

Der Anwender hat die Möglichkeit, den E-Mail-Versand vor dem Live-Betrieb zu testen. Im Testmodus werden alle E-Mails ausschließlich an die E-Mail-Adresse des Anwenders gesendet.

== E-Mail-Vorlagen erstellen

////
Aktuell gibt es im plentysystems System 2 Möglichkeiten, E-Mail-Vorlagen zu erstellen. Diese werden im Folgenden erläutert.

=== E-Mail-Vorlagen in den E-Mail-Einstellungen des Mandanten erstellen

Der Anwender kann beliebig viele E-Mail-Vorlagen erstellen. Die E-Mail-Vorlagen werden gemäß der Einstellung des Eigners, die man beim Erstellen der Vorlage wählen kann, in einem der drei bereits im System vorhandenen Ordner gespeichert:

 * Allgemeine E-Mail-Vorlagen – Eigner: Alle
 * Meine E-Mail-Vorlagen – Eigner: Eigener Benutzerkontoname
 * E-Mail-Vorlagen anderer Benutzer – Eigner: Anderer Benutzerkontoname

Die Namen der Ordner können nicht geändert werden und die Ordner können nicht gelöscht werden.

Der Ordner *Allgemeine E-Mail-Vorlagen* enthält bereits 12 E-Mail-Vorlagen, die in der folgenden Tabelle aufgelistet sind. Jede E-Mail-Vorlage besitzt eine ID, die vom System vergeben wird. Es handelt sich hierbei um einen eindeutigen, sogenannten Auto-Increment-Wert, der vom Anwender nicht geändert werden kann. Der Anwender kann jedoch die Namen der Vorlagen sowie deren Inhalt ändern.

[[tabelle-vorkonfigurierte-e-mail-vorlagen]]
.Vorkonfigurierte E-Mail-Vorlagen
[cols="1,3"]
|====
|ID |Name der E-Mail-Vorlage

|4 |Auftrag: Rechnung PDF-Anhang
|5 |Auftrag: Versandbestätigung
|6 |Ebay: Disputprozess
|7 |Auftrag: Zahlungserinnerung
|9 |Webshop: Newsletter Anmeldung
|10 |Auftrag: Änderung
|17 |Auftrag: Teilzahlung erhalten
|18 |Auftrag: Zahlungseingang vollständig
|21 |Webshop: Neues Passwort
|23 |Ebay: Eingangsbestätigung mit Bankdaten ohne Checkout
|25 |Ebay: Eingangsbestätigung Bestellung
|26 |Webshop: Eingangsbestätigung Bestellung
|====

Der Ordner *Meine E-Mail-Vorlagen* dient dazu, E-Mail-Vorlagen nur für den eigenen Benutzer zugänglich zu machen.

Der Ordner *E-Mail-Vorlagen anderer Benutzer* dient dazu, E-Mail-Vorlagen für alle Benutzer, die die Berechtigung im System des Anwenders haben, zugänglich zu machen. Unabhängig davon, welcher Benutzer im System angemeldet ist, kann dieser auf den Ordner zugreifen.

Weitere Informationen zum E-Mail-Versand sind im Handbuch auf der Seite link:https://knowledge.plentymarkets.com/de-de/manual/main/crm/e-mails-versenden.html[E-Mails^] zu finden.

=== E-Mail-Vorlagen über den EmailBuilder erstellen

////

Der Anwender kann beliebig viele E-Mail-Vorlagen erstellen. Außerdem kann er Ordner erstellen, die der besseren Übersicht und Struktur dienen.

Der Ordner *Standardvorlagen* enthält bereits 12 E-Mail-Vorlagen in deutscher und englischer Sprache, die in der folgenden Tabelle aufgelistet sind.

[[tabelle-standardvorlagen-emailbuilder]]
.Standardvorlagen im EmailBuilder
[cols="1,1"]
|====
|Name der deutschen Vorlage |Name der englischen Vorlage

|Auftrag: Änderung |Order: Changes
|Auftrag: Teilzahlung erhalten |Order: Partial payment received
|Auftrag: Versandbestätigung |Order: Shipping confirmation
|Auftrag: Zahlungseingang vollständig |Order: Payment complete
|Auftrag: Zahlungserinnerung |Order: Payment reminder
|Auftrag: Rechnung PDF-Anhang |Order: Invoice
|eBay: Disput / Storno, keine Zahlung |eBay: dispute / cancellation, no payment
|eBay: Eingangsbestätigung Bestellung |eBay: Order confirmation
|eBay: Eingangsbestätigung mit Bankdaten ohne Checkout |eBay: Order confirmation with bank details without checkout
|Shop: Neues Passwort |Shop: New password
|Shop: Newsletter-Anmeldung |Shop: Newsletter registration
|Shop: Eingangsbestätigung Bestellung |Shop: Order confirmation
|====

Der Anwender kann die Namen der Vorlagen sowie deren Inhalt und Betreff ändern.

Beim Erstellen der Vorlagen über den EmailBuilder stehen dem Anwender Widgets zur Verfügung. Diese können per Drag-and-drop an die gewünschte Stelle der Vorlage gesetzt werden und mit Inhalt, wie z.B. Variablen, befüllt werden. Die Variablen werden dann in der versendeten E-Mail durch die korrekten Werte ersetzt.

Weitere Informationen zum EmailBuilder sind im Handbuch auf der Seite link:https://knowledge.plentymarkets.com/de-de/manual/main/crm/emailbuilder.html[EmailBuilder^] zu finden.

== E-Mail-Versand automatisieren

Der Anwender kann einen großen Teil seiner Routineaufgaben wie z.B. das Versenden von Auftragsbestätigungen von seinem System erledigen lassen.

=== E-Mail-Versand anhand bestimmter Ereignisse automatisieren

Der Anwender hat die Möglichkeit, bestimmte Ereignisse mit einer E-Mail-Vorlage zu verknüpfen. Bei Eintritt des Ereignisses wird die verknüpfte E-Mail-Vorlage automatisch vom System an den Kunden versendet.

Die folgende Tabelle listet sowohl die im System bereits verfügbaren Ereignisse, die der Anwender mit zuvor erstellten E-Mail-Vorlagen verknüpfen kann, als auch deren Verwendungszweck auf. Die Namen der Ereignisse können nicht geändert werden.

[[tabelle-vorkonfigurierte-ereignisse-e-mail-vorlage]]
.Vorkonfigurierte Ereignisse, die mit einer E-Mail-Vorlage verknüpft werden können
[cols="1,3,3"]
|====
|Name des Ereignisses |Verwendungszweck |Voreingestellte E-Mail-Vorlagen

|Sende Kunde E-Mail zur Passwortänderung
|Sendet Kunden eine E-Mail mit einem Link zum neuen Passwort, der aktiv bestätigt werden muss.
|Webshop: Neues Passwort

|Bestätigung der Passwortänderung
|Sendet Kunden eine E-Mail zur Bestätigung der Passwortänderung.
|kein Versand

|Kunde möchte E-Mail-Adresse ändern
|Sendet Kunden eine Bestätigungs-E-Mail, wenn sie im Webshop ihre E-Mail-Adresse ändern und die neue E-Mail-Adresse eingeben. Die E-Mail-Vorlage sollte den Link zum Bestätigen der E-Mail-Adresse enthalten.
|kein Versand

|Newsletter Opt-In
|Sendet Kunden eine E-Mail, wenn diese sich für den Newsletter angemeldet haben. Die E-Mail-Vorlage sollte den Bestätigungslink, den die Kunden anklicken müssen, um die Newsletter-Anmeldung abzuschließen, enthalten.
|kein Versand

|Bestätigung Newsletter-Opt-In
|Sendet Kunden eine E-Mail als Bestätigung, sobald diese den Bestätigungslink, der mit der E-Mail-Vorlage für das Ereignis *Newsletter Opt-In* verschickt wurde, aktiviert haben.
|Webshop: Newsletteranmeldung

|Kundenregistrierung
|Sendet Kunden eine E-Mail, wenn diese sich neu im Webshop registriert haben.
|kein Versand

|Benachrichtigung bei verfügbarem Artikel
|Sendet Kunden eine E-Mail mit dem Hinweis, dass ein bestimmter Artikel wieder verfügbar ist. Der Kunde hat zuvor seine E-Mail-Adresse direkt bei dem nicht lieferbaren Artikel eingetragen.
|kein Versand

|Neuer Link zur Bestellbestätigung
|Sendet Gastkunden eine E-Mail mit der Möglichkeit, einen neuen Auftragsbestätigungslink anzufordern.
Die E-Mail-Vorlage sollte den Link zur Auftragsübersicht enthalten.
|kein Versand

|====

=== E-Mail-Versand über Ereignisaktionen automatisieren

Neben dem Verknüpfen von E-Mail-Vorlagen mit Ereignissen besteht die Möglichkeit, Ereignisaktionen einzurichten: Der Anwender definiert ein Ereignis, setzt Filter und legt Aktionen fest, die dann vom System automatisch im Ereignisfall ausgeführt werden. Beispielsweise kann der E-Mail-Versand eines Gutscheins ausgelöst werden, wenn der Kunde eine bestimmte Anzahl an Aufträgen generiert hat.

Weitere Informationen zu Ereignisaktionen sind im Handbuch auf der Seite link:https://knowledge.plentymarkets.com/de-de/manual/main/automatisierung/ereignisaktionen.html[Ereignisaktionen^] zu finden.

== Gesendete E-Mails einsehen

Der Anwender hat zum einen die Möglichkeit, alle E-Mails, die er an einen Kunden zu einem bestimmten Auftrag gesendet hat, einzusehen.

Außerdem kann der Anwender eine Statistik erstellen, um anzeigen zu lassen, welche E-Mail-Vorlagen wie häufig in einem bestimmten Zeitraum an alle seine Kunden versendet wurden.

Eine automatische E-Mail-Archivierung ist systemseitig nicht vorhanden.
