= Fachliche und technische Beschreibung des Moduls Newsletter

Um Newsletter an Kontakte zu senden, muss der Anwender entweder die Zugangsdaten seines E-Mail-Providers in PlentyONE speichern oder einen externen Newsletter-Anbieter mit PlentyONE verknüpfen.

Der Anwender kann den im System integrierten Newsletter-Dienst nutzen, seine Newsletter über den externen Anbieter CleverReach versenden oder einen Newsletter-Anbieter über ein Plugin anbinden. Weitere Informationen zu Newsletter-Plugins sind auf dem link:https://marketplace.plentymarkets.com/plugins/sales/marketing[plentyMarketplace^] zu finden.

Der Anwender kann bestimmte Ereignisse in seinem System einstellen. Wenn dieses Ereignis eintritt, resultiert daraus eine Aktion, d.h. der Newsletter wird dann automatisiert über das System an die Kunden bzw. Interessenten, die sich z.B. im Webshop für den Newsletter angemeldet haben, versendet.

Alle Informationen zum Newsletter-Versand sind im Handbuch auf der Seite https://knowledge.plentymarkets.com/de-de/manual/main/crm/newsletter-versenden.html[Newsletter^] zu finden.

== Häufigkeit des Newsletter-Versands

Der Newsletter-Versand ist tagsüber eingeschränkt. In der Nacht wird der Versand einer größeren Anzahl von E-Mails erlaubt.

 * Am Tag zwischen 8:00 und 0:00 Uhr: 60 E-Mails je Viertelstunde
 * In der Nacht zwischen 0:00 und 8:00 Uhr: 500 E-Mails je Viertelstunde

Ein automatisierter, zeitgesteuerter Prozess, ein sogenannter Cron-Job, arbeitet die Empfänger-E-Mail-Adressen dann sukzessive ab und versendet den Newsletter.

== Double-Opt-In-Methode

Das System bietet dem Anwender die Möglichkeit, die Double-Opt-In-Methode zu verwenden. Double-Opt-In bedeutet, dass der Kunde bzw. der Newsletter-Interessent, nachdem er sich für den Newsletter-Bezug im Webshop eingetragen hat oder sich im Bestellprozess entschieden hat, den Newsletter zu abonnieren, eine E-Mail mit einem Bestätigungslink erhält. Erst nachdem der Kunde bzw. Newsletter-Interessent auf den Link in der E-Mail geklickt hat, gilt dies als “bestätigt” und er ist für den Newsletter-Versand des Anwenders angemeldet.

Zum Verwenden der Double-Opt-In-Methode kann der Anwender für die im System vorhandenen Ereignisse *Newsletter Opt-In* und *Bestätigung Newsletter-Opt-In* je eine E-Mail-Vorlage erstellen und diese mit den Ereignissen verknüpfen.

Tritt das Ereignis ein, dass der Kunde sich für den Bezug des Newsletters im Webshop angemeldet hat, versendet das System automatisch die mit dem Ereignis *Newsletter Opt-In* verknüpfte E-Mail-Vorlage an den Kunden. Diese E-Mail-Vorlage sollte den Bestätigungslink, den der Kunde anklicken muss, um die Newsletter-Anmeldung abzuschließen, enthalten. Sobald der Kunde den Bestätigungslink anklickt, wird die mit dem Ereignis *Bestätigung Newsletter-Opt-In* verknüpfte E-Mail-Vorlage an den Kunden gesendet. Diese E-Mail-Vorlage sollte einen Text zur Bestätigung der erfolgreichen Newsletter-Anmeldung enthalten.

== Integrierter Newsletter-Dienst

Der Anwender muss die Zugangsdaten des E-Mail-Postfachs, aus dem er die Newsletter versenden möchte, speichern, damit das System E-Mails von dieser E-Mail-Adresse versenden kann.

Der Anwender muss den Postausgangsserver und den Port wie von seinem Provider angegeben eingeben und eine Verschlüsselungsmethode wählen.

== E-Mail-Ordner für Newsletter-Empfänger

Der Anwender kann beliebig viele Ordner für den Versand von Newslettern erstellen und so seine Newsletter anhand bestimmter Zielgruppen versenden. In den Ordnern speichert der Anwender entweder die E-Mail-Adressen seiner Kunden oder aber der Anwender räumt den Kunden die Möglichkeit ein, dass diese sich selbst für den Newsletter-Bezug eintragen können. Dazu gibt der Anwender die Ordner pro Mandant (Shop) für den Mein Konto-Bereich im Webshop frei. Das ist z.B. von Vorteil, wenn der Anwender regelmäßig Newsletter zu verschiedenen Themenbereichen versendet. So bestimmen die Kunden selbst, welche Newsletter sie von dem Anwender erhalten möchten. Die E-Mail-Adresse des Kunden wird dann automatisch in dem E-Mail-Ordner im System gespeichert.

Beim Erstellen des ersten Ordners schlägt das System die ID 1 vor. Beim Erstellen jedes weiteren Ordners schlägt das System jeweils die nächsthöhere ID vor. Der Anwender kann die vorgeschlagene ID verwenden oder eine andere ID vergeben. Sobald der Ordner erstellt ist, kann die ID nicht mehr geändert werden. Wichtig hierbei ist, dass die ID eindeutig ist: Wenn der Anwender eine bereits bestehende ID speichert, wird der ursprüngliche Ordner überschrieben.

== Externe Newsletter-Anbieter

Neben dem im System verfügbaren internen Newsletter-Dienst und dem Angebot von Newsletter-Plugins im link:https://marketplace.plentymarkets.com/plugins/sales/marketing[plentyMarketplace^] hat der Anwender die Möglichkeit, seine Newsletter über CleverReach zu versenden.

[discrete]
=== CleverReach

Möchte der Anwender die Newsletter an seine Kunden über die externe Schnittstelle CleverReach versenden, muss er sich zunächst über die Website von CleverReach registrieren. Im Anschluss daran muss er die Schnittstelle im System einrichten, damit die Daten zu CleverReach übertragen werden können.

PlentyONE überträgt die folgenden Daten an CleverReach, sofern der Newsletter-Bezug über das Double-Opt-In-Verfahren durch den Kunden bestätigt wurde:

 * Vorname
 * Nachname
 * Geburtstag
 * Geschlecht
 * Sprache
 * Artikeldaten
 * E-Mail-Adresse
 * Zeitpunkt der letzten Bestellung

== Import und Export

Der Anwender hat die Möglichkeit, z.B. Newsletterempfänger sowie die Ordner, in denen die Empfänger gespeichert sind, in PlentyONE automatisch oder manuell auszutauschen. Für den Austausch von Daten zwischen dem System des Anwenders und externen Systemen steht die link:https://developers.plentymarkets.com/[REST-API^] zur Verfügung.

Für den manuellen Austausch von Newsletter-Daten stehen dem Anwender die folgenden Formate zur Verfügung:

* Für den Import der Import-Typ *Newsletter-Empfänger* im Import-Tool

* Für den Export entweder der Katalog-Formattyp *Newsletter-Empfänger* oder das Datenformat *Newsletter-Empfänger* im Elastischen Export

Weitere Informationen sind im Handbuch auf den Seiten link:https://knowledge.plentymarkets.com/de-de/manual/main/daten/ElasticSync.html[Import-Tool nutzen^], link:https://knowledge.plentymarkets.com/de-de/manual/main/daten/catalogues-first-contact.html[Kataloge kennenlernen] und link:https://knowledge.plentymarkets.com/de-de/manual/main/daten/FormatDesigner.html[FormatDesigner^] zu finden.

*Hinweis*: Die selbe E-Mail-Adresse kann mehr als einmal in der Exportdatei oder in der REST-Abfrage vorkommen. Dies ist der Fall, wenn die E-Mail-Adresse in mehr als einem Ordner gespeichert ist. Pro Ordner kann dieselbe E-Mail-Adresse nur einmal gespeichert werden.
