= Fachliche und technische Beschreibung Benutzer und Benutzerrechte

Benutzer sind die Personen, die die Software plentymarkets bedienen. Die Benutzerrechte dienen dazu, einem Benutzer den Zugriff zu Bereichen oder Menüs der Software zu ermöglichen, zu beschränken oder zu verwehren. Benutzerrechte heißen in plentymarkets Rechte. +
Die Benutzerrechte eines Benutzers in plentymarkets hängen zunächst von seinem Benutzerzugang ab. Wird dem Benutzer kein Benutzerzugang zugewiesen, hängen die Benutzerrechte von den zugewiesenen Rollen ab. Die Benutzerzugänge sind systemseitig vorgegeben und können durch die Anwender nicht geändert werden. +

== Benutzerzugänge

Folgende Benutzerzugänge gibt es in plentymarkets:

 * Administrator
 * Nur API-Benutzer

Jeder Benutzerzugang ist mit den Rechten versehen, die in den folgenden Kapiteln näher beschrieben werden. Benutzern werden Rechte durch Rollen zugewiesen. Die gleiche Rolle kann mehreren Benutzern zugewiesen werden. Die Vergabe von Rollen wird detailliert im Handbuch auf der Seite link:https://knowledge.plentymarkets.com/business-entscheidungen/benutzerkonten-zugaenge#105[Benutzerkonten und Zugänge^] beschrieben. +

=== Benutzerzugang Administrator

Der Benutzerzugang Administrator verfügt über alle Rechte und dient zur Verwaltung des Systems. Benutzern dieses Zugangs können keine Rechte zusätzlich gewährt oder verwehrt werden. Sie verfügen pauschal über alle Rechte.

=== Benutzerzugang Nur API-Benutzer

Für den Benutzerzugang Nur API-Benutzer können in der zugewiesenen Rolle REST-Calls freigeschaltet werden. Diese werden einzeln aktiviert. *Achtung*: Nutzern mit diesem Benutzerzugang wird der Zugriff auf das Backend verweigert.

Standardmäßig sind jedoch keine Zugriffsrechte für REST aktiviert. Es besteht lediglich die Möglichkeit, einem Benutzer des Zugangs Nur API-Benutzer per REST Zugriff auf Daten des Systems zu gewähren. Ein Nur API-Benutzer hat keinen Zugriff auf Daten über die Softwareoberfläche. +
Eine detaillierte Beschreibung der REST-Schnittstelle befindet sich in der link:https://developers.plentymarkets.com/[Entwicklerdokumentation^]. +

== Rechte vergeben

Die Benutzerrechte in plentymarkets werden über Rollen verwaltet und unterteilen sich in:

* Menü- und Plugin-Sichtbarkeiten
* Berechtigungen

Die Menü- und Plugin-Sichtbarkeiten werden im einfachen Modus der Rollenerstellung vergeben, die Berechtigungen im erweiterten Modus der Rollenerstellung. Der einfache Modus und der erweiterte Modus sind miteinander verknüpft. Wenn Menü-Sichtbarkeiten im einfachen Modus aktiviert werden, sind dazugehörige Berechtigungen auch im erweiterten Modus automatisch aktiv. Diese Verknüpfung existiert nur in diese Richtung. Wenn im erweiterten Modus Berechtigungen vergeben werden, werden keine Menü- oder Plugin-Sichtbarkeiten automatisch aktiviert.

Beim Vergeben von Menü- und Plugin-Sichtbarkeiten sowie Berechtigungen gilt generell, dass das Aktivieren einer Berechtigung einer übergeordneten Ebene alle darunter liegenden Berechtigungen aktiviert. Das Entfernen einer Berechtigung einer übergeordneten Ebene entfernt analog alle darunter einsortieren Berechtigungen.

== Liste der Administratoren und Standardbenutzer

Ergänzen Sie in der folgenden Tabelle, welche Personen über welchen Zugriff verfügen.

Folgende Personen sind Administratoren und verfügen über uneingeschränkten Zugriff auf das plentymarkets System

Person 1: (_Name, Vorname; ggf. Personalnummer, Organisationseinheit, Funktion im Unternehmen_) +
Person 2: (_Name, Vorname; ggf. Personalnummer, Organisationseinheit, Funktion im Unternehmen_) +
Person 3: (_Name, Vorname; ggf. Personalnummer, Organisationseinheit, Funktion im Unternehmen_)

Folgende Personen sind Standardbenutzer und verfügen über eingeschränkten Zugriff auf das plentymarkets System:

Person 1: (_Name, Vorname; ggf. Personalnummer, Organisationseinheit, Funktion im Unternehmen_) +
Person 2: (_Name, Vorname; ggf. Personalnummer, Organisationseinheit, Funktion im Unternehmen_) +
Person 3: (_Name, Vorname; ggf. Personalnummer, Organisationseinheit, Funktion im Unternehmen_)

== Menü und REST-API-Rechte verwalten

Mit den Rechten wird festgelegt, welche Berechtigungen (REST-Rechte) ein Benutzer hat und welche Menüs und Plugins er sehen und öffnen kann. Außerdem kann bestimmt werden, welche Bearbeitungsmöglichkeiten der Benutzer im Menü haben soll.

=== Menü- und Plugin-Sichtbarkeiten im einfachen Modus

In diesem Bereich wird die Abbildung von Menü und Systemeinstellungen verwaltet. Dort können die für den Benutzer sichtbaren Bereiche gewählt werden. Die REST-Rechte für die Menüpunkte werden automatisch gesetzt.

* Start
* Artikel
* Listings
* Waren
* CRM
* Aufträge
* Daten
* CMS
* Plugins
* Prozesse
* Einrichtung
* Support
* Mobile

=== Berechtigungen

In diesem Bereich werden die REST-Rechte verwaltet, die für bestimmte Aktionen benötigt werden.

* Buchhaltung
* Authorisierung
* Automation
* Blog
* Zertifizierung
* Mandant
* CMS
* Kommentare
* CRM
* Daten
* Dokumente
* Editoren
* Artikel
* Listing
* Märkte
* Markierung
* Stammdaten
* plentyApp-Einstellungen
* Zahlenformat
* Aufträge
* plentyBI
* plentyBase-Einstellungen
* Plugins
* POS
* Prozesse
* Service
* Service-Center
* Einrichtung
* Start
* Warenbestände
* plentymarkets Systeme
* Vorlage
* Benutzer

=== REST-Rechte

Eine Auflistung aller verfügbaren REST-Rechte ist im <<#_anhang_rest-berechtigungen, Anhang: REST-Berechtigungen>> zu finden.
