= Fachliche und technische Beschreibung des Moduls Datenimport

In PlentyONE wird der Datenimport mit dem Import-Tool durchgeführt. Ein Import von Daten ist ratsam, wenn z.B. neue Artikel, Kundendaten oder Lagerbestände in das PlentyONE System eingepflegt werden sollen und die Daten bereits digital vorliegen. Das Tool ermöglicht es über das Erstellen von Importen, Datenimporte auszuführen. Ein Import kann manuell oder automatisiert erfolgen.

== Import-Typen in PlentyONE

PlentyONE stellt verschiedene Import-Typen zur Verfügung, mit denen ausgewählte Daten importiert werden können. Je nach Typ müssen bestimmte Datensätze vorhanden sein. Es gibt jeweils Abgleich- und Zuordnungsfelder, die für den Datenimport verwendet werden können.

Ein neuer Import kann im Menü *Daten » Import* erstellt werden.
Die verschiedenen Import-Typen und alle dazugehörigen Felder für den Datenimport sind im link:https://knowledge.plentymarkets.com/de-de/manual/main/daten/daten-importieren.html/[PlentyONE Handbuch^] unter *Daten » Daten importieren » Import-Typen* zu finden. Die folgende Tabelle zeigt zunächst, welcher Import-Typ für welche Importdaten zur Verfügung steht.

[[import-typen]]
.Import-Typen in PlentyONE
[cols="1,3"]
|====

|*Import-Typ* |*Importdaten*

|Artikel
|Artikel- und Variantendaten

|Attribute
|Daten zu Attributen und Attributwerten

|Aufträge
|Auftragsdaten

|Eigenschaften
|Eigenschaftsdaten

|Eigenschaften: Auswahlwerte
|Auswahlwerte von Eigenschaften

|Facetten
|Facettendaten

|Fahrzeugverwendungsliste
|Fahrzeugverwendungslisten

|Gutschein-Codes
|Daten zu Gutschein-Codes

|Hersteller
|Herstellerdaten

|Kampagnen
|Daten zu Gutscheinkampagnen

|Kategorien
|Kategoriedaten

|Kontakte, Firmen und Adressen
|Kontaktdaten

|Lager
|Lagerdaten

|Market-Listing
|Listingdaten

|Merkmale
|Merkmaldaten

|Newsletter
|Daten zu Newslettern

|Notizen
|Notizen

|Warenbestand
|Daten zum Warenbestand

|Wareneingang
|Ausgewählte Datensätze des Wareneingangs

|Zuordnung Zolltarifnummer
|Daten zu Zolltarifnummern
|====

== Abgleich

Mit dem Abgleich wird bestimmt, anhand welcher Daten identifiziert werden soll, ob bereits ein Datensatz besteht oder nicht. Bei den Abgleichfeldern handelt es sich um optionale Einstellungen. Wird kein Abgleichfeld gewählt, können die Daten der Datei keinen bestehenden Daten im System zugeordnet werden. Es können eins, mehrere oder alle Abgleichfelder festgelegt werden. Die angezeigten Abgleichfelder unterscheiden sich für jeden Import-Typ. +
Es kann außerdem festgelegt werden, was passieren soll, wenn durch den Abgleich keine bestehenden Daten gefunden werden. Dafür gibt es drei verschiedene Optionen, die hier im Kapitel <<#_importoptionen, Importoptionen>> aufgeführt sind. Für die Importoptionen kann außerdem festgelegt werden, ob die englische oder die deutsche Schreibweise der Dezimalzahl verwendet werden soll.

*Bsp.*:	DE: 1,25 oder 1.000,25 ; EN: 1.25 oder 1,000.25

== Zuordnung

Mit der Zuordnung wird festgelegt, welche Spalte der Datei welchem Datenfeld in PlentyONE entspricht. Es kann auch die automatische Zuordnung verwendet werden, die dafür sorgt, dass die Spalten der CSV-Datei den PlentyONE Datenfeldern automatisch zugeordnet werden. Damit die Zuordnung funktioniert, darf die Benennung der im FormatDesigner gewählten Felder nicht geändert werden. Ohne Zuordnung können keine Daten importiert werden. +
Für den Import können entweder alle Zeilen importiert werden oder es kann bei jeder Zeile individuell entschieden werden, ob sie beim Import berücksichtigt werden soll.
Mithilfe von Filtern können die zu importierenden Daten eingegrenzt werden. Bei der Verwendung mehrerer Filter werden nur Datensätze importiert, die auf alle Filter zutreffen. Es handelt sich also um eine Und-Verknüpfung der Filter.

== Eigene Zuordnung
Mit der Eigenen Zuordnung können vorhandene Werte einer CSV-Datei auf andere Werte im System gemappt werden. So kann definiert werden, für welche ID welcher Wert importiert werden soll. Importe können auch aus einem anderen PlentyONE System importiert werden, wofür der Abgleich und die Zuordnung angepasst werden müssen. Hier ist allerdings zu beachten, dass nur .json Dateien importiert werden können. +
Die eigene Zuordnung kann außerdem dazu genutzt werden, Daten während des Imports zu manipulieren und Werte zu ändern. Weitere Informationen dazu gibt es im PlentyONE Handbuch auf der Seite link:https://knowledge.plentymarkets.com/de-de/manual/main/daten/ElasticSync.html[Import-Tool nutzen^].

== Datenquellen
Als Quelle stehen die Optionen *Manueller Upload*, *FTP*, *SFTP* oder *HTTPS* zur Verfügung.
Je nach gewählter Option werden weitere Einstellungen sichtbar.

Über den Abgleich wird sichergestellt, dass die Daten identifiziert und korrekt übernommen werden. Sind die Daten einmal im System, werden die gleichen Daten bei erneuter Verarbeitung ignoriert, d.h. im System ändert sich nichts. Falls während des Imports ein Fehler auftritt, ist dieser im Menü unter *Daten » Logs* aufgeführt. Dort die importId als Referenztyp wählen und nach der ID filtern.
Alternativ können Fehler, die während des Importvorgangs aufgetreten sind, auch im Menü *Daten » Import* eingesehen werden.
Wurde der Import gestartet, ist kein Abbruch mehr möglich.

Es gibt die folgenden Anforderungen an die Dateien: +
*Format*: CSV +
*Zeichensatz*: Unicode UTF-8 oder Westeuropa ISO-8859-1 +
*Trennzeichen*: Semikolon, Komma, Tabulator oder Pipe

[[datenquellen-in-plentymarkets]]
.Datenquellen in PlentyONE
[cols="1,3"]
|====
|*Datenquelle* |*Erläuterung*

|Manueller Upload
|Hier wird eine lokale Datei gewählt und direkt hochgeladen. Bei dieser Option liegt die Datenhoheit bei PlentyONE. Somit liegen die importierten Daten in einem privaten Bereich, auf den nur die Personen mit Zugriff auf das System und das Import-Tool zugreifen können.

|FTP und SFTP
|Mit diesen Optionen können ebenfalls Daten bereitgestellt werden. Hier werden Host, Port, Benutzername, Passwort und Dateiname als Einstellungen sichtbar. Allerdings befinden sich diese Daten extern, d.h. PlentyONE kann hier nicht sicherstellen, dass die Daten gesichert sind. Wenn die gewählte Option aktiv ist, wird die Importdatei nach erfolgreichem Import automatisch in einen neuen Archiv-Ordner auf dem FTP-Verzeichnis verschoben.

|HTTPS
|Hier wird eine externe URL gewählt, unter der die Importdatei erreichbar ist. Der Anwender wählt, ob für den Zugriff auf die Datei eine Authentifizierung erforderlich ist oder nicht.
|====

== Importoptionen
Daten können importiert und exportiert werden. So können Importe sowohl lokal gesichert als auch von anderen Nutzern importiert werden. Für den Import gibt es verschiedene Optionen. Es kann gewählt werden, welche Daten importiert und welche Daten aktualisiert werden sollen.

[[import-optionen]]
.Import-Optionen
[cols="1,3"]
|====

|Neue Daten importieren, vorhandene aktualisieren
|Wenn anhand der Abgleichfelder keine übereinstimmenden Daten gefunden wurden, wird ein neuer Datensatz, z.B. ein neuer Artikel oder ein neuer Auftrag, hinzugefügt. Gleichzeitig werden bereits vorhandene Daten aktualisiert.

|Nur vorhandene Daten aktualisieren
|Vorhandene Daten werden aktualisiert. Wenn anhand der Abgleichfelder keine übereinstimmenden Daten gefunden wurden, wird der Datensatz nicht importiert.

|Nur neue Daten importieren
|Es werden ausschließlich neue Datensätze importiert, für die anhand der Abgleichfelder keine übereinstimmenden Daten gefunden wurden.
|====

== Werte mit RegEx ersetzen

Damit eine CSV-Datei beim Import wie gewünscht berücksichtigt wird, kann die sog. *RegEx-Funktion* (Regular Expression) genutzt werden. Diese sorgt dafür, dass Daten anhand von Befehlen beim Import manipuliert werden und folglich in der CSV-Datei keine Änderungen mehr vorgenommen werden müssen. Diese Werte stehen somit nicht in der CSV-Datei, können aber importiert werden. +
Mit der RegEx-Funktion können außerdem feste *Eigene Werte* vergeben werden, die nicht in der CSV-Datei enthalten sind.

Die zwei folgenden Beispiele sollen den Vorgang näher veranschaulichen.

*Beispiel 1*: +
Input: “24.12.2017” +
Search pattern: /^(\d+)\.(\d+)\.(\d+)$/ +
Replace pattern: $3﹣$2﹣$1 +
Result: “2017-12-24”

*Beispiel 2*: +
Input: “Mustermann, Max” +
Search pattern: /^(\w+), (\w+)$/ +
Replace pattern: $2 $1 +
Result: “Max Mustermann”

== Import von Massendaten
Die Queue sorgt dafür, dass auch große Datenmengen importiert werden können. Noch vor dem Import wird die Importdatei in Pakete zerlegt und anschließend in sogenannten Jobs abgearbeitet. Ein Job besteht aus 750 Zeilen einer CSV-Datei. Jedoch werden auch Importdateien, die weniger als 750 Zeilen enthalten, zu einem Job. Wird ein Import gestartet, wird die CSV-Datei in die entsprechenden Jobs aufgeteilt und in die Queue eingereiht. In der Queue werden neue Jobs ständig abgerufen und die Importe werden abgearbeitet. Dabei gibt es zwei verschiedene Status. Der Status *Offene Jobs* bedeutet, dass es Jobs gibt, die sich noch in der Queue befinden und darauf warten, abgearbeitet zu werden. *Abgeschlossene Jobs* hingegen wurden bereits bearbeitet und die Daten dementsprechend importiert.

== Status von Importen einsehen

Im Menü *Daten » Status* können Informationen zum Status von Importen eingesehen werden. Die Übersicht enthält Details zum Fortschritt der Jobs sowie zu eventuellen Fehlern, die während des Importvorgangs aufgetreten sind. Die Importe können bis zu 7 Tage zurückverfolgt werden.
In der Detailansicht werden dem Nutzer die konkreten Fehlermeldungen sowie Angaben zu Herkunft und Art des Fehlers zur Verfügung gestellt. Anhand der Fehlermeldungen kann die CSV-Datei entsprechend abgeändert und der Import anschließend erneut gestartet werden.
