=== Fachliche und technische Beschreibung des Moduls Gutscheine

==== Gutscheine

In plentymarkets sind link:https://knowledge.plentymarkets.com/auftraege/gutscheine[Gutscheine^] im Sinne von _Geschenkgutscheinen_ zu verstehen. Es handelt sich dann um einen Gutschein, wenn der Inhaber diesen zur Einlösung gegen Gegenstände oder Dienstleistungen verwenden kann.

Es handelt sich _nicht_ um einen Gutschein, wenn der Inhaber lediglich zu einem <<Sonderfall 2: Rabatte und Preisnachlässe, Preisnachlass>> beim Erwerb von Gegenständen oder Dienstleistungen berechtigt wird.

plentymarkets unterstützt die sogenannten Mehrzweck-Gutscheine (in plentymarkets Verkaufsgutscheine genannt). Das heißt, dass die Mehrwertsteuer zu dem Zeitpunkt erhoben wird, zu dem die Gegenstände oder Dienstleistungen geliefert bzw. erbracht werden. Diese Gutscheinart kann in plentymarkets sowohl verkauft als auch eingelöst werden.

Hierfür sind einige Vorbereitungen im ERP-System plentymarkets nötig:

* Pro Gutscheinwert muss ein Artikel in plentymarkets erstellt und mit einer link:https://knowledge.plentymarkets.com/auftraege/gutscheine#20[Kampagne^] verknüpft werden.
* Diese Artikel erhalten den Mehrwertsteuersatz 0%.
* Der Artikelpreis entspricht jeweils dem Gutscheinwert.

Beim Verkauf eines Gutscheins erhält der Kunde einen Gutschein-Code. Dieser Gutschein-Code ist systemseitig nicht mit dem Auftrag verknüpft. Der Gutschein-Code kann automatisch generiert werden. Alternativ können Händler auch mit eigenen Gutschein-Codes arbeiten, die entweder im Vorfeld im ERP-System plentymarkets gespeichert werden oder erst beim Verkauf im System gespeichert werden. Es ist technisch möglich, Gutschein-Codes mehrmals zu verkaufen.

Zum Einlösen eines Gutscheins benötigt der Kunde lediglich seinen Gutschein-Code. Beim Einlösen eines Gutscheins geschieht folgendes:

* Der Wert der Gutscheine wird vom zu zahlenden Betrag abgezogen.
* Der Umsatz erhöht sich um den eingelösten Gutscheinbetrag.

==== Rabatte und Preisnachlässe

In plentymarkets sind link:https://knowledge.plentymarkets.com/crm/kontakte-verwalten#25[Rabatte^] im Sinne von _Preisnachlässen_ zu verstehen. Rabatte können beispielsweise verwendet werden, um:

* <<Standardkunden und Bestandskunden, Bestandskunden>> einen günstigeren Preis als Standardkunden anzubieten.
* werbliche Aktionen durchzuführen, z.B. 20% auf alles außer Tiernahrung. Solche Aktionen werden mit sogenannten link:https://knowledge.plentymarkets.com/auftraege/gutscheine[Aktionsgutscheinen^] durchgeführt.

plentymarkets Händler können <<Standardkunden und Bestandskunden, Bestandskunden>> einen anderen Preis anbieten als Standardkunden. Solche Rabatte hängen von der link:https://knowledge.plentymarkets.com/crm/kontakte-verwalten#15[Kundenklasse] des Bestandskunden ab, und davon, ob für diese Kundenklasse ein link:https://knowledge.plentymarkets.com/crm/kontakte-verwalten#25[Rabatt] im ERP-System plentymarkets gespeichert ist.

Kundenklassenrabatte werden direkt auf den Auftrag angewendet, jedoch nicht separat im Auftrag ausgewiesen.

Artikel können im Menü *Artikel » Artikel bearbeiten » Artikel öffnen » Tab: Global » Option: Aktionsgutschein/POS-Rabatt* von Rabatten ausgeschlossen werden.
