
=== Fachliche und technische Beschreibung des Moduls Multi-Channel

==== Verwendungszweck

Das Softwaremodul Multi-Channel dient dem zusätzlichen Vertrieb auf Online-Marktplätzen und Preisvergleichsseiten. Folgende Funktionen stellt das Modul bereit: +
 * Schnittstellen-Zugriff auf Online-Märkte und Preisportale +
 * Bestandsabgleich über automatische Prozesse mit zeitlich festlegten Intervallen +
 * Produktdatenaustausch über automatische Prozesse mit zeitlich festlegten Intervallen +
 * Auftragsimport über automatische Prozesse mit zeitlich festlegten Intervallen +
 * Übermittlung von Zahlungs- und Versandbestätigungen per link:https://knowledge.plentymarkets.com/automatisierung/ereignisaktionen[Ereignisaktion^] oder über automatische Prozesse mit zeitlich festlegten Intervallen +
 * Meldung des Auftragsstatus an Marktplatzkunden per E-Mail per link:https://knowledge.plentymarkets.com/automatisierung/ereignisaktionen[Ereignisaktion^] +
 * Empfang von Kundennachrichten an zentraler Stelle über das link:https://knowledge.plentymarkets.com/crm/ticketsystem-nutzen[Ticketsystem^] +

==== Verfügbarkeit

Aktuell ist das Softwaremodul Multi-Channel in allen von plentymarkets angebotenen Tarifen inklusive (Starter, Pro, Plus).

==== Dokumentation

Die Dokumentation des Moduls Multi-Channel ist über die folgende URL erreichbar: link:https://knowledge.plentymarkets.com/maerkte[https://knowledge.plentymarkets.com/maerkte^]. Die Dokumentation der Marktplatz- und Preisportal-Plugins kann im jeweiligen Plugin im link:https://marketplace.plentymarkets.com/plugins/channels/marktplaetze[plentyMarketplace^] angesehen werden. Ein Download der Dokumentation ist zurzeit nicht möglich. +
Auf Anfrage stellt die plentysystems AG prüfenden Finanzbehörden ältere Versionen der Verfahrensdokumentation zur Verfügung.

==== Integrierte Kanäle

Die im Modul Multi-Channel fest integrierten Online-Marktplätze werden im Menü *Einrichtung » Märkte* eingerichtet. Folgende Online-Marktplätze sind im Modul Multi-Channel fest integriert: +

Tragen Sie in die Tabelle ein, auf welchen Online-Marktplätzen Sie mit plentymarkets verkaufen.

|===
|*Marktplatz*|*In Verwendung*|*Hinweis*

|Amazon|[_Ja/Nein_]|
|bol.com|[_Ja/Nein_]|
|eBay|[_Ja/Nein_]|
|Flubit|[_Ja/Nein_]|
|Fruugo|[_Ja/Nein_]|
|GartenXXL.at|[_Ja/Nein_]|
|GartenXXL.de|[_Ja/Nein_]|
|GoogleShopping DE|[_Ja/Nein_]|Veraltete Schnittstelle, die nicht mehr verwendet wird.
|GoogleShopping Int.|[_Ja/Nein_]|
|grosshandel.eu|[_Ja/Nein_]|Die Schnittstellenanbindung wurde von grosshandel.eu entwickelt.
|Hood|[_Ja/Nein_]|
|La Redoute|[_Ja/Nein_]|Veraltete Schnittstelle, die momentan nicht genutzt werden kann.
|Mercateo|[_Ja/Nein_]|
|Neckermann.at|[_Ja/Nein_]|
|Netto|[_Ja/Nein_]|
|OTTO|[_Ja/Nein_]|Der Marktplatz OTTO verfügt über drei Schnittstellen: *Direktversand*, *Cooperation* und *Integration*, die sich im Auftragsimport unterscheiden. Weitere Informationen zu den verschiedenen Schnittstellen finden sie auf der link:https://knowledge.plentymarkets.com/maerkte/otto[OTTO-Handbuchseite^].
|Pixmania|[_Ja/Nein_]|
|real.de|[_Ja/Nein_]|
|Restposten.de|[_Ja/Nein_]|Die Schnittstellenanbindung wurde von Restposten.de entwickelt.
|ricardo.ch|[_Ja/Nein_]|
|Shopgate|[_Ja/Nein_]|
|Yatego|[_Ja/Nein_]|
|Zalando|[_Ja/Nein_]|
|===

Es sind jedoch nicht alle von plentymarkets angebotenen Online-Marktplätze im Modul Multi-Channel fest integriert. Weitere Märkte stehen in plentymarkets als link:https://knowledge.plentymarkets.com/plugins/neue-plugins[Plugins^] zur Verfügung und müssen zunächst installiert werden, damit sie im Menü *Einrichtung » Märkte* sichtbar sind und somit eingerichtet werden können. Plugins können im link:https://marketplace.plentymarkets.com/[plentyMarketplace^] heruntergeladen werden.

Für einige Online-Marktplätze und Preissuchmaschinen, bei denen Daten über den elastischen Export übertragen werden, sind Grundeinstellungen bereits im Menü *Einrichtung » Märkte* fest integriert und konfigurierbar. Für diese Märkte werden jedoch zusätzlich die jeweiligen Datenformate, die als Plugins zur Verfügung stehen, für den elastischen Export benötigt. Für folgende im Modul Multi-Channel integrierten Online-Marktplätze sind zusätzlich Plugin-Datenformate für den elastischen Export nötig: +

Tragen Sie in die Tabelle ein, auf welchen Online-Marktplätzen Sie mit plentymarkets verkaufen.

|===
|Marktplatz|*In Verwendung*

|Cdiscount|[_Ja/Nein_]
|CHECK24|[_Ja/Nein_]
|Google Shopping|[_Ja/Nein_]
|idealo Direktkauf|[_Ja/Nein_]
|Kauflux|[_Ja/Nein_]
|Rakuten.de|[_Ja/Nein_]
|===

==== Zusätzliche Marktplatz-Services

Für den Marktplatz Amazon steht der Amazon-Umsatzsteuerservice VCS zur Verfügung. Mit diesem Service können Amazon-Rechnungen durch plentymarkets oder durch Amazon erzeugt werden. +
Wenn Amazon-Rechnungen durch plentymarkets erzeugt werden, werden diese mit Daten von Amazon erzeugt, automatisch zu Amazon übertragen und bei Amazon gespeichert. Wenn Rechnungen durch Amazon erzeugt werden, werden diese mit Daten von Amazon erzeugt und bei Amazon gespeichert. In beiden Fällen können die Rechnungen nicht nachträglich geändert werden.

Weiterhin steht der Amazon-Service Multi-Channel zur Verfügung, womit Aufträge von externen Verkaufskanälen über Amazon abgewickelt werden können.

==== Auftragsherkünfte

Die Auftragsherkünfte dienen der Kennzeichnung, über welchen Online-Marktplatz ein Auftrag generiert wurde. Eine Übersicht zu den Auftragsherkünften, die standardmäßig in jedem plentymarkets System vorhanden sind, ist im Kapitel <<_Fachliche-und-technische-Beschreibung-des-Moduls-Auftragsabwicklung, Fachliche und technische Beschreibung des Moduls Auftragsabwicklung>> der Verfahrensdokumentation verfügbar. Bei den dort aufgeführten Auftragsherkünften handelt es sich um Systemherkünfte, die standardmäßig mit jedem plentymarkets System ausgeliefert werden und nicht gelöscht werden können. Systemherkünfte sind nicht automatisch aktiviert. +

Damit über Online-Marktplätze Artikel verkauft, Aufträge generiert und einer Herkunft zugeordnet werden können, muss die Auftragsherkunft zunächst aktiviert werden. Ohne die Aktivierung der Herkunft findet also kein Verkauf auf Online-Marktplätzen statt.

==== Verkauf über Multi-Channel

Um Artikel über das Modul Multi-Channel verkaufen zu können, müssen zunächst allgemeine Einstellungen vorgenommen werden. Eine Händlerregistrierung beim Online-Marktplatz ist Voraussetzung für den Verkauf von Artikeln. Grundsätzlich gilt für alle Marktplätze, dass zumindest die Artikelverfügbarkeit für die gewünschten Märkte und die jeweilige Auftragsherkunft aktiviert sowie der Verkaufspreis festgelegt wurden. Zudem müssen noch weitere Grundeinstellungen vorgenommen werden, die je nach Marktplatz variieren. Bei den meisten Online-Marktplätzen müssen zusätzlich plentymarkets Attribute, Kategorien, Merkmale oder Eigenschaften mit den Attributen, Kategorien und Merkmalen des Online-Marktes verknüpft werden. In einigen Fällen muss zusätzlich die marktplatzeigene Zahlungsart aktiviert werden. +

Bei vielen Marktplätzen können zudem über link:https://knowledge.plentymarkets.com/automatisierung/ereignisaktionen[Ereignisaktionen^] automatisch Informationen zu Versandbestätigungen, Stornierungen, Retouren etc. an die Schnittstelle gesendet werden.

==== Marktplatz-Zahlungsarten

Marktplatz-Zahlungsarten sind Zahlungsarten, die in Verbindung mit der Einrichtung eines Marktplatzes zur Kennzeichnung von Zahlungseingängen genutzt werden. Die Zahlungsarten der Marktplätze werden in der Regel nicht vollständig eingerichtet, sondern lediglich aktiviert. Ohne eine Aktivierung kann es zu Problemen bei der Zahlungsabwicklung kommen. Eine Übersicht zu den Marktplatz-Zahlungsarten finden Sie in der folgenden Tabelle.

|===
|*Zahlungsart*|*Erläuterung*

|Amazon|Zahlungsart für Aufträge, die über den Marktplatz Amazon ins plentymarkets System kommen.
|BOL.com|Zahlungsart für Aufträge, die über den Marktplatz bol.com ins plentymarkets System kommen.
|Cdiscount|Zahlungsart für Aufträge, die über den Marktplatz Cdiscount ins plentymarkets System kommen.
|CHECK24|Zahlungsart für Aufträge, die über den Marktplatz CHECK24 ins plentymarkets System kommen.
|eBay-Rechnungskauf|Zahlungsart für Kauf auf Rechnung bei eBay.
|Flubit|Zahlungsart für Aufträge, die über den Marktplatz Flubit ins plentymarkets System kommen.
|Fruugo|Zahlungsart für Aufträge, die über den Marktplatz Fruugo ins plentymarkets System kommen.
|GartenXXL.at|Zahlungsart für Aufträge, die über den Marktplatz GartenXXL.at ins plentymarkets System kommen.
|GartenXXL.de|Zahlungsart für Aufträge, die über den Marktplatz GartenXXL.de ins plentymarkets System kommen.
|idealo Direktkauf|Zahlungsart für Aufträge, die über den Marktplatz idealo Direktkauf ins plentymarkets System kommen.
|Neckermann.at Payment|Zahlungsart für Aufträge, die über den Marktplatz Neckermann.at ins plentymarkets System kommen.
|Netto|Zahlungsart für Aufträge, die über den Marktplatz Netto ins plentymarkets System kommen.
|Otto Payment|Zahlungsart für die Schnittstellen OTTO Cooperation und OTTO Integration.
|OTTO Direktversand|Zahlungsart für die Schnittstelle OTTO Direktversand.
|PIXmania Payment|Zahlungsart für Aufträge, die über den Marktplatz PIXmania ins plentymarkets System kommen.
|Rakuten|Zahlungsart für Aufträge, die über den Marktplatz Rakuten ins plentymarkets System kommen.
|real.de Payment|Zahlungsart für Aufträge, die über den Marktplatz real.de ins plentymarkets System kommen.
|Shopgate Payment|Zahlungsart für Aufträge, die über den Marktplatz Shopgate ins plentymarkets System kommen.
|Yatego Rechnung|Zahlungsart für Aufträge, die über den Marktplatz Yatego ins plentymarkets System kommen.
|Zalando Payment|Zahlungsart für Aufträge, die über den Marktplatz Zalando ins plentymarkets System kommen.
|===

==== Preisbildung

Verkaufspreise werden zentral verwaltet. Informationen zur Preisverwaltung in plentymarkets finden Sie im Kapitel <<_Was-sind-Verkaufspreise?, Preise>> der Verfahrensdokumentation. Weitere Informationen zu Verkaufspreisen finden Sie im Kapitel link:https://knowledge.plentymarkets.com/artikel/artikel-verwalten#870[Verkaufspreise verwalten^] des plentymarkets Handbuchs. +
In plentymarkets können beliebig viele Preise erstellt werden und somit können unterschiedliche Preise an die verschiedenen Schnittstellen übertragen werden. Damit Preise zu den Online-Marktplätzen übertragen werden können, müssen die Preise zunächst mit der Auftragsherkunft verknüpft werden. Für eBay und Amazon müssen zusätzlich die Plattform-Konten mit dem Verkaufspreis verknüpft sein, damit Preise übertragen werden. Verkaufspreise können auch als Aktionspreis gekennzeichnet werden. Aktionspreise werden z.B. für Marktplätze wie Amazon und real.de verwendet. Preisänderungen können manuell oder automatisch an die Schnittstellen übertragen werden.

Die Marktplätze eBay, Hood und ricardo.ch bilden bei der Preisbildung eine Ausnahme. Auf diesen Märkten werden Listings vom Typ *Auktion* oder *Festpreis* zum Verkauf angeboten. +
Auf Listings vom Typ *Auktion* kann geboten werden. Diese Listings werden mit einem Startpreis gestartet und an den Höchstbietenden verkauft. Listings vom Typ *Festpreis* werden zu einem festgelegten Preis angeboten. +
Ob ein Listing mit einem Festpreis oder in einer Auktion angeboten werden soll, wird im Artikel oder im Listing in plentymarkets eingestellt.

==== Datenaustausch

Daten können in plentymarkets automatisch über REST-API und FTP-Server oder manuell über ElasticSync und den elastischen Export mit den Schnittstellen ausgetauscht werden. Im Log und API-Log kann anhand von Log-Einträgen der Datenaustausch nachvollzogen werden.

|===
|*Marktplatz*|*Datenaustausch*

|Amazon|Im- und Export über Amazon MWS Webservice-API mit CSV- und XML-Dateien
|bol.com|Export über elastischen Export +
 Import über REST-API mit JSON
|Cdiscount|Im- und Export über SOAP-API mit XML-Datei
|CHECK24|Export über elastischen Export +
 Import über FTP-Server mit XML-Datei
|eBay|Im- und Export über REST-API mit XML-Dateien
|Flubit|Im- und Export über REST-API mit JSON
|Fruugo|Im- und Export über REST-API mit XML-Datei
|GoogleShopping Int.|Export über elastischen Export
|grosshandel.eu|Im- und Export über SOAP-API
|Hood|Im- und Export über REST-API mit XML-Dateien
|idealo|Export über elastischen Export und REST-API mit JSON
|Kauflux|Export über elastischen Export +
 Import über REST-API mit XML-Datei
|La Redoute|Im- und Export über SOAP-API mit XML-Datei
|Mercateo|Export über FTP-Server mit XML-Datei +
 Import über E-Mail
|Neckermann.at|Im- und Export über FTP-Server mit XML-Datei
|Netto eStores (Netto, GartenXXL.at, GartenXXL.de)|Im- und Export über SFTP-Server mit XML-Datei
|OTTO|Im- und Export über FTP-Server mit XML-Datei
|PIXmania|Im- und Export über REST-API mit CSV-Datei
|Rakuten.de|Export über elastischen Export +
Import über REST-API mit JSON
|real.de|Im- und Export über REST-API mit CSV-Datei
|Restposten.de|Im- und Export über SOAP-API
|ricardo.ch|Im- und Export über SOAP-API mit XML-Dateien
|Shopgate|Im- und Export über REST-API mit CSV-Datei
|Yatego|Export über FTP-Server mit CSV-Datei +
 Import über REST-API
|Zalando|Im- und Export über REST-API mit XML-Datei
|===

===== Welche Daten werden mit den Schnittstellen ausgetauscht?

plentymarkets überträgt Artikeldaten (z.B. Bestand, Preise, Produktinformationen) und Lieferdaten an die Online-Marktplätze. Auftragsdaten und Kundendaten werden von den Marktplätzen ins plentymarkets System importiert. Kundendaten können im plentymarkets System manuell angepasst werden.
