= Vorlage zur Verfahrensdokumentation für plentymarkets POS Anwender
:lang: de
include::{includedir}/_header.adoc[]

== plentymarkets App

=== Verwendungszweck


Die plentymarkets App ist eine mobile App, die die folgenden Funktionen bereitstellt:

* Anzeige von Kennzahlen des ERP-Systems plentymarkets
* Artikelsuche
* Kundensuche
* Auftragssuche
* Picklistenanzeige
* Umbuchung zwischen Lagern
* Kassensystem plentymarkets POS

=== Systemvoraussetzungen und Betrieb

Als Bestandteil der plentymarkets App läuft das Kassensystem plentymarkets POS auf mobilen Endgeräten mit folgenden Systemvoraussetzungen:

* Android-Geräte mit OS-Version ab 4.2.2
* iOS-Geräte (iPad, iPhone, iPod) mit OS-Version ab 8

Die plentymarkets App wird ohne eigene Hardware ausgeliefert.

Die plentymarkets App wird in folgenden App-Stores kostenlos bereitgestellt:

** iOS: https://itunes.apple.com/de/app/plentymarkets/id957702618?mt=8[https://itunes.apple.com/de/app/plentymarkets/id957702618?mt=8]
** Android: https://play.google.com/store/apps/details?id=eu.plentymarkets.mobile[https://play.google.com/store/apps/details?id=eu.plentymarkets.mobile]

Versionen der plentymarkets App sind durch Versionsnummern gekennzeichnet. Änderungen an der Software werden in den Changelogs der App-Stores veröffentlicht:

** iOS: https://itunes.apple.com/de/app/plentymarkets/id957702618?mt=8[https://itunes.apple.com/de/app/plentymarkets/id957702618?mt=8]
** Android: https://play.google.com/store/apps/details?id=eu.plentymarkets.mobile[https://play.google.com/store/apps/details?id=eu.plentymarkets.mobile]

Die plentymarkets App ist nur in Kombination mit einem gebuchten plentymarkets System funktionsfähig, da eine Anmeldung erforderlich ist.

// Mandanten

=== Sicherheitsfunktionen

Der Zugriff auf plentymarkets Daten über die plentymarkets App wird über umfassende Zugangsrechte gesteuert. Bei der Anmeldung müssen die Login-Daten eines gültigen plentymarkets Systems eingegeben werden. Diese Login-Daten bestehen aus:

* Basis-URL des plentymarkets Systems
* Benutzer
* Passwort

In welchem Umfang Benutzer die App nutzen können, wird über die Benutzerverwaltung des ERP-Systems plentymarkets gesteuert. Benutzer werden im Menü *Einstellungen » Grundeinstellungen » Benutzer* erstellt. Die Zugriffsrechte für die plentymarkets App werden im Menü *Einstellungen » Grundeinstellungen » Benutzer » Konten » Konto öffnen » Tab: Berechtigung » Tab: Mobile *definiert. Benutzer der Benutzerklasse Admin haben standardmäßig alle verfügbaren Rechte für den Zugriff auf plentymarkets App. Für alle anderen Benutzerklassen müssen die Rechte pro Benutzer oder pro Benutzerrolle definiert werden.

Für die plentymarkets App sind die folgenden Zugriffsrechte verfügbar:

[cols="1,2"]
|===
|*Rechtegruppe*|*Einzelrechte*

|Sichtbare Funktionen| * Alle
|POS-Funktionen| * Preis bearbeiten
|Sichtbare Kennzahlen| * Alle
|===

Diese Benutzerrechte werden im Handbuch des ERP-Systems plentymarkets näher erläutert: https://knowledge.plentymarkets.com/omni-channel/pos/pos-einrichten#130[https://knowledge.plentymarkets.com/omni-channel/pos/pos-einrichten#130]

Die folgenden Mitarbeiter verfügen über uneingeschränkten Zugriff auf alle Funktionen der plentymarkets App. Dies umfasst auch uneingeschränkten Zugriff auf alle Funktionen der Kassensoftware plentymarkets POS.

* [_Name, Vorname, ggf. Personalnummer, Organisationseinheit, Funktion im Unternehmen_]
* [_Name, Vorname, ggf. Personalnummer, Organisationseinheit, Funktion im Unternehmen_]
* [_Name, Vorname, ggf. Personalnummer, Organisationseinheit, Funktion im Unternehmen_]
* [_Name, Vorname, ggf. Personalnummer, Organisationseinheit, Funktion im Unternehmen_]


.Erteilte Rechte pro Benutzer
[cols="1,2"]
|====
|Mitarbeiter/-in |An Mitarbeiter/-in erteilte Rechte

|[_Name, Vorname, ggf. Personalnummer, Organisationseinheit, Funktion im Unternehmen_]
|Sichtbare Funktionen

 * Alle
 * Artikelsuche
 * Aufträge
 * Picklisten
 * Umbuchung
 * Konten
 * POS (beta)
 * Kundensuche

POS-Funktionen

* Preis bearbeiten
* Artikelposition umbenennen
* Rabatt gewähren
* Kassieren
* Kasse sperren
* Einlagen und Entnahmen
* Kassensturz
* Zwischenbericht
* Tagesabschluss
* Artikelsynchronisation 
* Aufträge hochladen
* Retoure anlegen
* Kunde auswählen
* Stornierung

Sichtbare Kennzahlen

* Alle
* Aufträge
* Durchschnittliche Aufträge
* Neue Kunden
* Unbezahlte Aufträge
* Unzugeordnete Zahlungen
* Neue Artikel
* Umsatz
* Durchschnittlicher Umsatz
* Verkaufte Artikel
* Durchschnittlich Verkaufte Artikel
* Artikel pro Auftrag
* Aktive Listings
* Gestartete Listings
* Wareneingänge
* Meldebestand
|====

== plentymarkets POS

plentymarkets POS ist ein Modul der plentymarkets App, das für den stationären Verkauf von Waren und/oder Dienstleistung entwickelt wurde. plentymarkets POS ist ein mobiles, App-basiertes Kassensystem. Im Sinne der GoBD ist plentymarkets POS ein Vorsystem der elektronischen Buchhaltung.

Der Zugriff auf die plentymarkets App wird über Zugriffsrechte gesteuert, die im ERP-System plentymarkets über Benutzerrechte pro Benutzer oder über Benutzerrollen definiert werden.

=== Verwendungszweck

plentymarkets POS dient zur exakten Einzelerfassung und Dokumentation sämtlicher Kassenvorgänge. Hierbei kann es sich um Bargeldtransaktionen, bargeldlose Transaktionen, Gutscheinzahlungen, Retouren, Stornierungen, Gutschriften, Einlagen oder Entnahmen handeln. plentymarkets POS bildet also alle Kassenvorgänge des Einzelhandels ab, dokumentiert diese Vorgänge unveränderlich und hält die Daten dieser Vorgänge in elektronischer Form vor. Kassenvorgänge werden durch Belege dokumentiert. Diese Belege werden im ERP-System plentymarkets manipulationssicher gespeichert. Außerdem wird pro Zahlungsvorgang ein Auftrag im ERP-System plentymarkets gespeichert.

Eine softwareseitige Erfassung von Geschäftsvorfällen kann in plentymarkets nicht unterdrückt werden. Eine Belegerstellung, ohne dass dabei die vereinnahmten Beträge erfasst werden, ist für plentymarkets POS Benutzer/-innen technisch nicht möglich.

Umfangreiche Berichtsoptionen ermöglichen außerdem eine detaillierte Visualisierung der Kassenvorgänge.


=== plentymarkets POS Betreiber

Die in dieser Verfahrensdokumentation aufgeführten Kassen werden von folgendem Unternehmen betrieben:

[cols="1,2"]
|===
|Unternehmensname|
|Anschrift|
|===

=== Verantwortliche Auskunftsperson

Verantwortliche Auskunftsperson für die Kassensysteme des Unternehmens ist/sind:

[cols="1,2"]
|===
|Name|
|Telefonnummer|
|E-Mail-Adresse|
|Weitere Anmerkungen|
|===


=== Eingesetzte Kassen

Durch die Nutzung der nachfolgend bezeichneten Hard- und Software wird sichergestellt, dass bei ordnungsgemäßer und zeitlich ununterbrochener Anwendung die GoBD eingehalten werden.

==== plentymarkets POS Kassen

Das Unternehmen verfügt über [_Anzahl der Kassen eingeben_] plentymarkets POS Kassensysteme. Diese Kassen haben die folgenden IDs/Namen:

|===
|Kassen-ID|Kassenname|Einsatzort (Adresse)|Einsatzzeitraum (von/bis)

|
|
|
|

|
|
|
|

|
|
|
|
|===

Systemseitig wird der Standort der Kasse in der Tabelle *plenty_account_address_pos_relation* und dort in folgenden Spalten gespeichert:

* *posBaseId* -> Die ID der Kasse, dem eine Adresse zugeordnet wurde.
* *addressID* -> Die ID des Standorts, der dem System zugeordnet wurde.

Systemseitig werden die Kassendaten in der Tabelle *plenty_pos_base* und dort in den folgenden Spalten gespeichert:

 * *_name_* -> Der Name der Kasse.
 * *_webstoreId_* -> Der Mandant der Kasse.
 * *_referrerId_* -> Die Herkunft der Aufträge, die über diese Kasse eingehen.
 * *_defaultCustomerId_* -> Die ID des Standardkunden.
 * *_shippingWarehouseId_* -> Das für die Kasse hinterlegte Vertriebslager.
 * *_orderReturnsWarehouseId_* -> Das für die Kasse hinterlegte Reparaturlager.
 * *_orderReturnsSotrageLocationId_* -> Der Lagerort im Reparaturlager.
 * *_currentCashBalanceValue_* -> Der Barbestand der Kasse, der zum aktuellen Zeitpunkt auf dem Server bekannt ist. Bei Offline-Betrieb kann dieser Bestand vom physischen Kassenbestand abweichen, bis alle Aufträge in das ERP-System plentymarkets importiert wurden.
 * *_currentReceiptNumber_* -> Die auf dem Server aktuell bekannte Anzahl der erstellten Belege. Bei Offline-Betrieb kann diese Anzahl von der Anzahl in der Kasse abweichen, bis alle Aufträge in das ERP-System plentymarkets importiert wurden.
 * *_grandTotal_* ->  Der Gesamtumsatz der Kasse, der zum aktuellen Zeitpunkt auf dem Server bekannt ist.  Bei Offline-Betrieb kann dieser Gesamtumsatz vom tatsächlichen Gesamtumsatz abweichen, bis alle Aufträge in das ERP-System plentymarkets importiert wurden.
 * *_deviceUUID_* -> Die einzigartige ID des Geräts, mit dem die Kasse gekoppelt ist.
 * *_deviceName_* -> Der nicht einzigartige Name des Geräts, mit dem die Kasse gekoppelt ist.
 * *_ecConnection_* -> Die eingerichtete EC-Verbindungsart (z.Z. Miura oder ohne)
 * *_applyMarketAvalibility_* -> Marktplatzverfügbarkeit berücksichtigen (ja/nein)
 * *_appyItemActive_* -> Nur aktive Varianten berücksichtigen (ja/nein)


==== Soft- und Hardware

////
Darstellung dieser Infos noch zu klären
////

|===
|Kasse|ID des gekoppelten mobilen Geräts|Eingesetzte Hardware|Eingesetzte Software|plentymarkets-System

|[_Kassen-ID, Name der Kasse_]
|[_ID des gekoppelten mobilen Geräts_]
|[_Modell, Hersteller_]
|[_Programmname, Versionsnummer, Hersteller_]
|[_plenty-ID, Link, Mandant (Shop)_]

|[_Kassen-ID, Name der Kasse_]
|[_ID des gekoppelten mobilen Geräts_]
|[_Modell, Hersteller_]
|[_Programmname, Versionsnummer, Hersteller_]
|[_plenty-ID, Link, Mandant (Shop)_]

|[_Kassen-ID, Name der Kasse_]
|[_ID des gekoppelten mobilen Geräts_]
|[_Modell, Hersteller_]
|[_Programmname, Versionsnummer, Hersteller_]
|[_plenty-ID, Link, Mandant (Shop)_]
|===

////
Alternative Darstellung
////

Für die Kasse mit der Kassen-ID [_ID einfügen_] kommt folgende Hardware zum Einsatz: +

* Tablet / Smartphone [Modell, Hersteller]
* Belegdrucker [Modell, Hersteller]
* Kartenterminal [Modell, Hersteller]
* Kassenlade [Modell, Hersteller]
* Barcodescanner [Modell, Hersteller]
* EC-Terminal [Modell, Hersteller]
* Sonstiges [Modell, Hersteller]

Für die Kasse mit der Kassen-ID [_ID einfügen_] kommt folgende Software zum Einsatz:

* Betriebssystem [Programmname, Versionsnummer, Hersteller]
* ERP-System [Programmname, Versionsnummer, Hersteller]
* Scan-Software [Programmname, Versionsnummer, Hersteller]
* Sonstiges [Programmname, Versionsnummer, Hersteller]


=== plentymarkets POS Geschäftsvorfälle

In plentymarkets POS werden Geschäftsvorfälle einzeln, vollständig und unveränderbar aufgezeichnet. Geschäftsvorfälle sind jederzeit über das Kassenjournal des ERP-Systems plentymarkets verfügbar und über den IDEA-Export maschinell auslesbar.

Die folgenden Arten von Geschäftsvorfällen können über plentymarkets POS erstellt und im ERP-System plentymarkets weiter verarbeitet werden:

* Aufträge
* Stornierungen
* Retouren/Gutschriften
* Einlagen
* Entnahmen

Für alle über plentymarkets POS erstellten Geschäftsvorfälle werden automatisch Belege erstellt. Diese Belege werden zur eindeutigen Kennzeichnung mit einer fortlaufenden Nummer versehen. Die Belegnummern setzen sich aus der ID der Kasse (vierstellig, ggf. mit führenden Nullen) und der Vorgangsnummer zusammen. Der erste Beleg der Kasse mit der ID 1 lautet also z.B. 0001-1.

Die in plentymarkets POS verfügbaren Geschäftsvorfälle werden nachfolgend einzeln erläutert.

==== Buchungsablauf bei Aufträgen

Verkäufe, die über plentymarkets POS abgewickelt werden, werden als Geschäftsfall des Typs *Auftrag* mit einer der Kasse fest zugeordneten Auftragsherkunft im ERP-System plentymarkets gespeichert. Diese Auftragsherkunft ist *103.[Kassen-ID]*. Während der Auftragsanlage werden die Auftragsdaten auf dem mobilen Endgerät zwischengespeichert, um die Ausfallsicherheit zu gewährleisten. Wird die Internetverbindung während der Auftragsanlage unterbrochen, wird der gesamte Auftrag auf dem mobilen Gerät gespeichert. Wird die Internetverbindung wiederhergestellt, werden die offline gespeicherten Aufträge an das ERP-System plentymarkets übertragen und dort gespeichert.

Während der Auftragserfassung können Kassierende je nach Benutzerrechten folgende Daten bearbeiten:

* Artikelposition umbenennen
* Einzelpreis ändern
* Gesamtpreis ändern
* Rabatt auf Einzelpositionen gewähren
* Rabatt auf gesamten Auftragswert gewähren
* Gutscheine einlösen

Nach Abschluss des Auftrags können diese Daten nicht mehr geändert werden.

Folgende Daten werden für Aufträge systemseitig gespeichert und auf dem Beleg dokumentiert:

* Datum und Uhrzeit des Auftrags
* Art des Geschäftsvorfalls
* Belegnummer
* Gekaufte Artikel
* Einzelpreise der Artikel
* Summe der Artikel
* Mehrwertsteuersätze
* Brutto- und Nettobetrag des Auftrags
* Zahlungsart
* Bei Barzahlung: Gegeben/Wechselgeld
* Bei Kartenzahlung: Nur Gesamtbetrag
* Ersteller/-in

Auftragsdaten mit der Herkunft POS werden im ERP-System plentymarkets wie folgt gespeichert:

* Geschäftsvorfall im Kassenjournal
* Beleg im Dokumentenarchiv
* Auftrag im Auftragsmodul
* Tab “Aufträge” des Kunden
* Daten für den IDEA-Export

Eine Änderung der Kassenauftragsdaten durch plentymarkets Anwender ist nicht möglich.

Bei bargeldloser Zahlung treten geringfügige Besonderheiten auf: Bei der Zahlungsart Kartenzahlung muss kein erhaltener Betrag eingegeben werden. Kassierer/-innen bestätigen mit einem Klick auf “Betrag erhalten/Zahlung abschließen” lediglich, dass die Zahlung mit Karte erfolgt ist.
Bei der Kartenzahlung mit Miura kann, wenn es in den Einstellungen so definiert wurde, diese Bestätigung des Zahlungseingang auch automatisiert passieren.
Außerdem wird bei der Zahlungsart Kartenzahlung der Barbestand der Kasse nicht erhöht.

===== Sonderfall 1: Gutscheinverkauf

Pro Gutscheinwert muss im ERP-System plentymarkets ein Gutscheinartikel mit dem Preis des Gutscheinwerts und dem Mehrwertsteuersatz 0% erstellt werden und mit einer Kampagne verknüpft werden.

Die genaue Vorgehensweise zum Verkauf von Gutscheinen wird im Handbuch des ERP-Systems plentymarkets beschrieben: https://knowledge.plentymarkets.com/omni-channel/pos/pos-einrichten#_gutscheinverkauf_vorbereiten[https://knowledge.plentymarkets.com/omni-channel/pos/pos-einrichten#_gutscheinverkauf_vorbereiten]

Die folgenden systemseitigen Prozesse sind steuerrechtlich von besonderer Relevanz:

* Beim Verkauf eines Verkaufsgutscheins erhöht sich der Umsatz nicht.
* Verkaufte Gutscheine werden auf dem Tagesbericht separat ausgewiesen. * Der Barbestand erhöht sich nur, wenn der Gutschein bar bezahlt wird.
* Beim Verkauf eines Gutscheins wird dem Kunden ein Gutschein-Code ausgehändigt. Dieser Gutschein-Code ist nicht mit dem Auftrag verknüpft.

Systemseitig ist es möglich, Gutschein-Codes mehrmals zu verkaufen. Um dies zu verhindern, sind Mitarbeiter/-innen angewiesen, beim Verkauf von Gutscheinen wie folgt vorzugehen:

* [_Beschreibung des Ablaufs im Unternehmen einfügen_]

===== Sonderfall 2: Gutscheineinlösung

Im ERP-System plentymarkets können zwar Aktionsgutscheine und Verkaufsgutscheine angelegt werden. Im Kassensystem plentymarkets POS können jedoch nur Verkaufsgutscheine eingelöst werden. Zur Einlösung ist ein Gutschein-Code erforderlich, der im ERP-System plentymarkets generiert und gespeichert wurde.

Die folgenden systemseitigen Prozesse sind steuerrechtlich von besonderer Relevanz:

* Der Wert des Verkaufsgutscheins wird vom zu zahlenden Betrag abgezogen.
* Der Umsatz erhöht sich um den eingelösten Gutscheinbetrag.
* Auf dem Tagesbericht wird der eingelöste Gutscheinwert mit der Zahlungsart *Gutschein* ausgewiesen.
* Der Barbestand der Kasse erhöht sich durch die Einlösung des Gutscheins nicht.

Die Vorgehensweise beim Einlösen von Gutscheinen wird im Handbuch des ERP-Systems plentymarkets beschrieben: https://knowledge.plentymarkets.com/omni-channel/pos/pos-kassenbenutzer#160[https://knowledge.plentymarkets.com/omni-channel/pos/pos-kassenbenutzer#160]

Abweichend von dieser Beschreibung sind Mitarbeiter/-innen angewiesen, beim Einlösen von Gutscheinen wie folgt vorzugehen:

* [_Beschreibung des Ablaufs im Unternehmen einfügen_]

===== Sonderfall 3: Bestandskunden

Damit POS-Aufträge korrekt in plentymarkets gespeichert werden, muss jedem Auftrag ein Kontakt zugeordnet sein. Um dieser Anforderung gerecht zu werden, wird in plentymarkets ein anonymer Standardkunde erstellt und mit der Kasse verknüpft.

plentymarkets POS Aufträge werden über den Standardkunden mit den folgenden Einstellungen erstellt:

[cols="1,2"]
|====
|Einstellung |Erläuterung

|**Kontakt-ID**
|

|**Firma**
|

|**Straße; +
PLZ**; +
**Ort**
|

|**Land**
|

|**Mandant**
|

|**Typ**
|

|**Klasse**
|

|Sonstige Einstellungen
|
|====

Kassierer/-innen mit den nötigen Benutzerrechten können Kassenvorgänge auch über im ERP-System plentymarkets gespeicherte Bestandskunden abwickeln, statt den Standardkunden zu wählen. Die Vorgehensweise für Kassierer/-innen wird im Handbuch des ERP-Systems plentymarkets beschrieben: https://knowledge.plentymarkets.com/omni-channel/pos/pos-kassenbenutzer#135[https://knowledge.plentymarkets.com/omni-channel/pos/pos-kassenbenutzer#135]

Abhängig von der <<CRM#1100, *Kundenklasse*>> des Bestandskunden, und davon, ob für diese Kundenklasse ein <<CRM#600, *Rabatt*>> im ERP-System plentymarkets gespeichert ist, kann der Verkaufspreis für Bestandskunden mit bestimmten Kundenklassen niedriger sein als der Verkaufspreis für den Standardkunden.

Kundenklassenrabatte werden direkt auf den POS-Auftrag angewendet und weder auf dem Kassenbeleg noch im Auftrag separat ausgezeichnet. Das bedeutet, dass über die Kundenklasse rabattierte Artikel auch auf dem Tagesbericht nicht unter *Rabattierte Artikel* aufgeführt werden.

==== Buchungsablauf bei Stornierungen

Stornierungen können nur über plentymarkets POS vorgenommen werden. Eine Stornierung über das ERP-System plentymarkets ist nicht möglich, um die Integrität des Berichtswesens zu gewährleisten sowie Barbestand und Belegnummernfolge nicht zu beeinträchtigen. Stornierbar sind nur abgeschlossene POS-Aufträge, die seit dem letzten Tagesabschluss über die Kasse erstellt wurden. Eine Stornierung ist nicht mehr möglich, nachdem ein Tagesabschluss für die Kasse generiert wurde. Danach muss eine Retoure erstellt werden.

Durch eine Stornierung über plentymarkets POS werden die folgenden Änderungen ausgelöst:

- Ein Beleg wird erstellt.
- Die Belegnummer für den Beleg wird erhöht.
- Der Barbestand wird erhöht.
- Ein Journal-Eintrag wird erstellt.
- Der Auftragsstatus wird geändert. Der neue Auftragsstatus ist [_Status einfügen, der Stornierungen zugewiesen wird. Standardeinstellung ist *[8] Storniert*._]




Die Vorgehensweise zum Stornieren von Aufträgen wird im Handbuch des ERP-Systems plentymarkets beschrieben: https://knowledge.plentymarkets.com/omni-channel/pos/pos-kassenbenutzer#173[https://knowledge.plentymarkets.com/omni-channel/pos/pos-kassenbenutzer#173]

Folgende Daten werden für Stornierungen systemseitig gespeichert und auf dem Beleg dokumentiert:

* Datum und Uhrzeit der Stornierung
* Art des Geschäftsvorfalls
* Belegnummer
* Stornierte Artikel
* Summe der Stornierung
* Mehrwertsteuersätze
* Brutto- und Nettobetrag der Stornierung
* Ersteller/-in
* ID des Auftrags

Die Daten einer Stornierung mit der Herkunft POS können im ERP-System plentymarkets wie folgt angezeigt werden:

* Geschäftsvorfall im Kassenjournal
* Beleg im Dokumentenarchiv
* Vorhandener Auftrag wird in Auftragsstatus *[_Status einfügen, der Stornierungen zugewiesen wird. Standardeinstellung ist *[8] Storniert*_]* gesetzt
* Anzeige im Tab *Aufträge* des Kunden
* Daten für den IDEA-Export

==== Buchungsablauf bei Retouren

Über plentymarkets POS erstellte Retouren werden im ERP-System plentymarkets als Auftrag des Typs *Retoure* ohne Hauptauftrag erstellt. Das bedeutet, dass datentechnisch keine Verbindung zwischen dem ursprünglichen Auftrag und der Retoure besteht.

Die Vorgehensweise zum Retournieren von Artikeln wird im Handbuch des ERP-Systems plentymarkets beschrieben:  +
https://knowledge.plentymarkets.com/omni-channel/pos/pos-kassenbenutzer#175

Folgende Daten werden für Retouren systemseitig gespeichert und auf dem Beleg dokumentiert:

* Datum und Uhrzeit der Retoure
* Art des Geschäftsvorfalls
* Belegnummer
* Retournierte Artikel
* Summe der Retoure
* Mehrwertsteuersätze
* Brutto- und Nettobetrag der Retoure
* Ersteller/-in
* ID der Retoure

Beim Erstellen einer Retoure wird außerdem eine Gutschrift erstellt und gespeichert.

Folgende Daten werden für Gutschriften systemseitig gespeichert und auf dem Beleg dokumentiert:

* Datum und Uhrzeit der Gutschrift
* Art des Geschäftsvorfalls
* Belegnummer
* Retournierte Artikel
* Summe der Gutschrift
* Mehrwertsteuersätze
* Brutto- und Nettobetrag der Gutschrift
* Ersteller/-in
* ID der Gutschrift
* ID der Retoure
* Belegnummer der Retoure

==== Buchungsablauf bei Einlagen

Einzahlungen in die Kasse, die nicht durch das Buchen von Aufträgen entstehen, werden als Einlagen über plentymarkets POS erfasst und im ERP-System plentymarkets gespeichert und archiviert. Systembedingt können Einlagen von allen Anwendern der Benutzerklasse “Admin” getätigt werden sowie von Anwendern mit der Benutzerklasse “Variabel”, für die das Recht “Einlagen und Entnahmen” aktiviert ist.

Um eine Einzahlung über plentymarkets POS zu tätigen, muss bei der Erfassung ein Grund für die Einlage angegeben werden. Eine Einlage ist nur möglich, wenn plentymarkets POS im Online-Modus läuft, also eine Verbindung zum ERP-System plentymarkets besteht. Die Einlagedaten werden also direkt an das ERP-System plentymarkets übertragen und nicht auf dem mobilen Endgerät zwischengespeichert.

Beim Erstellen eines Geschäftsvorfalls des Typs **Einlage** wird ein Beleg erstellt und im ERP-System plentymarkets im Menü *Aufträge » Dokumentenarchiv* sowie im Menü *Aufträge » POS » Kassenjournal* gespeichert. Einlagen werden außerdem im IDEA-Export berücksichtigt. Systembedingt können Einlagen nach der Erfassung nicht mehr gelöscht oder manipuliert werden.

Folgende Daten werden für Einlagen systemseitig gespeichert und auf dem Beleg dokumentiert:

* Datum und Uhrzeit der Einlage
* Belegnummer
* Art des Geschäftsvorfalls
* Eingelegter Betrag
* Grund für die Einlage
* Ersteller/-in
* ID der Kasse

Der Ablauf einer Einlage wird im Handbuch des ERP-Systems plentymarkets beschrieben: https://knowledge.plentymarkets.com/omni-channel/pos/pos-kassenbenutzer#180[https://knowledge.plentymarkets.com/omni-channel/pos/pos-kassenbenutzer#180]

Folgende Personen sind autorisiert, Einlagen durchzuführen:

* [_Name, Vorname, ggf. Personalnummer, Organisationseinheit, Funktion im Unternehmen_]
* [_Name, Vorname, ggf. Personalnummer, Organisationseinheit, Funktion im Unternehmen_]
* [_Name, Vorname, ggf. Personalnummer, Organisationseinheit, Funktion im Unternehmen_]

==== Buchungsablauf bei Entnahmen

Entnahmen aus der Kasse, die nicht durch das Buchen von Aufträgen entstehen, werden über plentymarkets POS erfasst und im ERP-System plentymarkets gespeichert und archiviert. Systembedingt können Entnahmen von allen Anwendern der Benutzerklasse “Admin” getätigt werden sowie von Anwendern mit der Benutzerklasse “Variabel”, für die das Recht “Einlagen und Entnahmen” aktiviert ist.

Um eine Entnahme über plentymarkets POS zu tätigen, muss bei der Erfassung ein Grund für die Einlage angegeben werden. Eine Entnahme ist nur möglich, wenn plentymarkets POS im Online-Modus läuft, also eine Verbindung zum ERP-System plentymarkets besteht. Die Entnahmedaten werden also direkt an das ERP-System plentymarkets übertragen und nicht auf dem mobilen Endgerät zwischengespeichert.

Beim Erstellen eines Geschäftsvorfalls des Typs Entnahme wird ein Beleg erstellt und im ERP-System plentymarkets im Menü *Aufträge » POS » Kassenjournal* gespeichert. Einlagen werden außerdem im IDEA-Export berücksichtigt. Systembedingt können Entnahmen nach der Erfassung nicht mehr gelöscht oder manipuliert werden.

Folgende Daten werden für Entnahmen systemseitig gespeichert und auf dem Beleg dokumentiert:

* Datum und Uhrzeit der Entnahme
* Belegnummer
* Art des Geschäftsvorfalls
* Entnommener Betrag
* Grund für die Entnahme
* Ersteller/-in
* ID der Kasse

Der Ablauf einer Entnahme wird im Handbuch des ERP-Systems plentymarkets beschrieben: https://knowledge.plentymarkets.com/omni-channel/pos/pos-kassenbenutzer#180

Folgende Personen sind autorisiert, Entnahmen durchzuführen:

* [_Name, Vorname, ggf. Personalnummer, Organisationseinheit, Funktion im Unternehmen_]
* [_Name, Vorname, ggf. Personalnummer, Organisationseinheit, Funktion im Unternehmen_]
* [_Name, Vorname, ggf. Personalnummer, Organisationseinheit, Funktion im Unternehmen_]

=== Elektronische Aufbewahrung von POS Geschäftsvorfällen im Kassenjournal

Sämtliche über plentymarkets POS generierten Geschäftsvorfälle werden in das ERP-System plentymarkets importiert. Ein Kassenbuch wird in Form eines elektronischen Kassenjournals automatisch erstellt und aktualisiert.

Das Kassenjournal ist im ERP-System plentymarkets über das Menü *Aufträge » POS » Kassenjournal* erreichbar. Das Kassenjournal enthält sämtliche Geschäftsvorfälle, die über plentymarkets POS Kassen in das System gelangen. Im Kassenjournal sind folgende Vorgänge möglich:

* Filterung von Geschäftsvorfällen anhand von Filtern
* Export der Daten im PDF-Format
* Export der Daten im CSV-Format
* Aufrufen der für die Geschäftsvorfälle gespeicherten Einzelbelege
* Aufrufen der für die Geschäftsvorfälle angelegten Aufträge

Für jeden Geschäftsvorfall sind im Kassenjournal die unten aufgeführten Daten gespeichert und einsehbar.

[cols="1,2,3"]
|====
|*Daten*|*Berechnungsformel*|*Erläuterung*

|*Datum*
|---
|Datum und Uhrzeit des Geschäftsvorfalls

|*Vorgang*
|---
|A = Ausgaben +
E = Einnahmen

|*Betrag*
|Umsatz bzw. Betrag des Vorgangs
|

|*Zahlungsart*
|---
|Die Zahlungsart, mit der der Geschäftsvorfall durchgeführt wurde. +
Bei Stornierung wird die Zahlungsart angezeigt, über die das Geld zurückgebucht wurde. +
Der Name der Zahlungsart wird im Menü *Einstellungen » Aufträge » Zahlung » Zahlungsarten* gespeichert bzw. aus dem Zahlungsart-Plugin übernommen. +
Bei Entnahmen und Einlagen ist das Feld leer.

|*Belegnummer*
|---
|Belegnummer im Format [Kassen-ID]-[fortlaufende Nummer]. +
 Ein Klick auf die Nummer öffnet den Beleg als PDF.

|*Typ*
|---
|Mögliche Typen: +
Auftrag, Einlage, Entnahme, Stornierung, Retoure, Gutschrift

|*Barbestand*
|Übertrag des vorherigen Barbestands + Betrag des aktuellen Eintrags (wenn nicht über Kartenzahlung)
|Der aktuelle Soll-Bestand der Kasse

|*Auftrags-ID*
|---
|Die Auftrags-ID im ERP-System plentymarkets. +
Bei Entnahmen und Einlagen ist das Feld leer.

|*Steuersatz*
|---
|Auflistung der im Auftrag enthaltenen Steuersätze. +
Die Steuersätze werden im Menü **Einstellungen » Mandant (Shop) » Standard » Standorte » Deutschland (Standard) » Buchhaltung** definiert und am Artikel gespeichert. +
Gutscheine werden mit 0% angezeigt. +
Bei Entnahmen und Einlagen ist das Feld leer.

|*USt.*
|Brutto-Betrag ./. Netto-Betrag
|Bei Entnahmen und Einlagen ist das Feld leer.

|*Buchungstext*
|---
|Der bei Entnahmen und Einlagen eingegebene Grund. Bei allen anderen Geschäftsvorfällen ist das Feld leer.
|====

Die im Kassenjournal angezeigten Daten sind nicht veränderbar. Allerdings kann die Anzahl der angezeigten Vorfälle durch das Setzen von Filtern reduziert werden. Folgende Filtermöglichkeiten sind verfügbar:

[cols="1,2"]
|===
|*Filter*|*Erläuterung / Filtermöglichkeiten*

|Belegnummer
|Filterung nach einer Belegnummer durch Eingabe derselben Belegnummer in die Felder **von** und **bis** +
Filterung nach einer Abfolge von Belegnummern durch Eingabe eines Bereichs

|Mandant (Shop)
|Filterung nach einem Mandanten (Shop)

|Kasse
|Filterung nach dem Namen einer Kasse

|Benutzer
|Filterung nach dem Benutzer, der den Geschäftsvorfall erstellt hat

|Zahlungsart
|Filterung nach der Zahlungsart. Folgende Zahlungsarten sind verfügbar: +
Barzahlung, EC-Karte, Gutscheinzahlung [_weitere, z.B. über Plugins eingebundene Zahlungsarten einfügen_]

|Zeitraum
|Filterung nach dem Zeitpunkt des Geschäftsvorfalls. Folgende Zeiträume sind verfügbar: +
Aktueller Monat, Letzter Monat, Letzte 30 Tage, Letzte 3 Monate, Letzte 6 Monate, Letzte 12 Monate, Letztes Jahr, Letztes Quartal, freie Datumsauswahl (von/bis)

|Typ
|Filterung nach Typ des Geschäftsvorfalls. Folgende Typen sind verfügbar: +
Auftrag, Einlage, Entnahme, Stornierung, Retoure, Gutschrift
|===


Aus dem Kassenjournal können außerdem Geschäftsvorfalldaten exportiert werden. Die Daten können im PDF- oder im CSV-Format exportiert werden. Exportiert werden jedoch nur die gefilterten Vorfälle. Um einen vollständigen Export zu erstellen, dürfen daher keine Filter angewendet werden.

Systemseitig sind die Daten des Kassenjournals in der Datentabelle *plenty_pos_journal* gespeichert. Die Einzeldaten sind in folgenden Spalten gespeichert:

 * *_posBaseId_* ->  Die ID des POS-Systems, an dem der Eintrag erstellt wurde
 * *_userId_* -> Die ID des Users, der den Auftrag erstellt hat
 * *_userRealName_* -> Der volle Name des Benutzers
 * *_type_* -> Der Typ des  Eintrag (z.B. Bon, Einlage, Entnahme)
 * *_actionFrom_* -> Wird aktuell nicht gefüllt
 * *_actionTo_* -> Wird aktuell nicht gefüllt
 * *_value_* -> Der Gesamtbetrag des Eintrags
 * *_currency_* -> Die Währung
 * *_note_* -> Eine dem Eintrag zugeordnete Notiz
 * *_receiptNumber_* -> Die Nummer des zum Eintrag erstellten Belegs
 * *_documentId_* -> Die ID des erstellten Dokuments
 * *_orderId_* -> Die ID des Auftrags
 * *_currentCashBalance_* -> Der Barbestand der Kasse zum gegebenen Zeitpunkt

=== Speicherung und Abrufbarkeit von plentymarkets POS Geschäftsvorfällen (Berichtswesen)

plentymarkets POS bietet umfassende Berichtsfunktionen. Folgende Berichte können erstellt werden:

* Zwischenberichte
* Tagesberichte
* Kassensturzberichte
* Statistiken

==== Zwischenberichte (X-Berichte)

Zwischenberichte zeigen eine Auflistung der Umsätze über die Kasse seit dem letzten Tagesabschluss. In plentymarkets POS können jederzeit und beliebig viele Zwischenberichte gedruckt werden. Wie Zwischenberichte erstellt werden, wird im Handbuch des ERP-Systems plentymarkets beschrieben: https://knowledge.plentymarkets.com/omni-channel/pos/pos-kassenbenutzer#220[https://knowledge.plentymarkets.com/omni-channel/pos/pos-kassenbenutzer#220]  +
Zwischenberichte sind kein gültiger Nachweis gegenüber dem Finanzamt und werden daher weder in der plentymarkets App noch im ERP-System plentymarkets gespeichert. Sie werden daher auch keinem Nummernkreis zugeordnet.

Im Unternehmen wird mit den Ausdrucken von Zwischenberichten wie folgt verfahren:

* [_Beschreibung des Ablaufs im Unternehmen einfügen_]

==== Tagesabschlussberichte (Z-Berichte)

Tagesabschlussbereichte sind GoBD-relevante Dokumente. In plentymarkets POS werden Tagesabschlussberichte manuell erstellt. Das System gibt keinen Erstellungsintervall vor.

Tagesabschlussberichte werden in plentymarkets POS in einem eigenen Nummernkreis fortlaufend nummeriert. Der erste Z-Bericht der Kasse hat also die Nummer 1, der zweite die Nummer 2 usw.

In plentymarkets POS generierte Tagesberichte enthalten die folgenden Informationen, die sowohl auf dem Tagesberichtsbeleg gedruckt als auch systemseitig gespeichert werden:

[cols="1,2,2"]
|====
|*Tagesberichtdaten*|*Berechnungsformel*|*Erläuterung*

3+|*Belegkopf*

|Unternehmensdaten
|---
|Kopfzeile gemäß Belegeinstellungen der Kasse

|Datum/Uhrzeit
|---
|Datum und Uhrzeit der Erstellung des Tagesabschlusses

3+|*Tagesabschluss*

|Nummer
|---
|Fortlaufende Nummer des Tagesabschlusses

|Erstellt von
|---
|Name des Benutzers, der den Tagesabschluss erstellt hat

|POS-ID
|---
|Systeminterne ID der Kasse

|Erster Beleg
|---
|Nummer des ersten Belegs seit letztem Tagesabschluss

|Letzter Beleg
|---
|Letzter Beleg dieses Tagesabschlusses

3+|*Zeitraum*

|Von
|---
|Datum und Uhrzeit der Generierung des ersten Belegs seit dem letzten Tagesbericht

|Bis
|---
|Datum und Uhrzeit der Generierung des aktuellen Tagesberichts

3+|*Barbestand*

|Entnahmen
|Summe der Entnahmen
|Anzahl in Klammern

|Einlagen
|Summe der Einlagen
|Anzahl in Klammern

|Anfangsbestand
|---
|Übertrag aus dem letzten Tagesabschlussbericht

|Soll-Bestand
|Anfangsbestand + Zugänge ./. Abgänge
|

|Ist-Bestand
|Summe der eingegebenen Stückelungen oder manuell eingegebene Gesamtsumme
|

3+|*Umsatz*

|Summe
|Summe der Aufträge ./. Summe der verkauften Gutscheine ./. Retouren ./. Stornierungen
|Umsatz seit dem letzten Tagesabschluss

|Grand Total
|Summe der Aufträge ./. Summe der verkauften Gutscheine ./. Retouren ./. Stornierungen
|Umsatz seit Inbetriebnahme der Kasse

3+|*Steuerbericht*

|%
|---
|Im ERP-System plentymarkets gespeicherte Steuersätze

|Steuer
|Steuersatz
|Auflistung der verschiedenen Steuersätze mit abzuführender Steuer

|Netto
|Umsatzsumme ./. Betrag des Steuersatzes
|

3+|*Sonstige Summen*

|Zahlungsarten
|Umsatz exklusive Stornierungen
|Auflistung aller genutzten Zahlungsarten inkl. Summe, Anzahl der Aufträge pro Zahlungsart in Klammern

|Retouren
|Summe der Retouren
|Summe der getätigten Retouren

|Stornierungen
|Summe der Stornierungen
|Anzahl in Klammern

|Rabattierte Artikel
|Summe der rabattierten Artikel
|Anzahl der rabattierten Artikel in Klammern

|Verkaufsgutscheine
|Summe der verkauften Gutscheine
|Anzahl in Klammern

|Benutzer
|Umsatzsumme pro Benutzer ./. Retouren ./. Stornierungen
|Auflistung der Kassenbenutzer (ID und Name) seit dem letzten Tagesabschluss inkl. des erwirtschafteten Umsatzes
|====

Tagesberichte werden in plentymarkets POS erstellt und automatisch an das ERP-System plentymarkets übertragen. Tagesberichte werden nicht auf dem mobilen Gerät gespeichert. Tagesberichte können im Menü *Aufträge » Dokumentenarchiv* aufgerufen werden. Dort werden sie als Dokumente des Typs “Z-Report” gespeichert.

Systemseitig werden die Daten der Tagesberichte in der Datentabelle *plenty_pos_z_report* und dort in den folgenden Spalten gespeichert:

 * *_posBaseId_* -> Die ID der Kasse, an der der Tagesabschluss erstellt wurde.
 * *_reportNumber_* -> Die Nummer des Tagesabschluss
 * *_createdAt_* -> Das Datum und die Uhrzeit, zu der der Tagesabschluss erstellt wurde.
 * *_fromDate_* -> Das Datum und die Uhrzeit des ersten Auftrages, der in dem Tagesabschluss berücksichtigt wurde.
 * *_toDate_* -> Das Datum und die Uhrzeit des letzten Auftrages, der in dem Tagesabschluss berücksichtigt wurde.
 * *_userId_* -> Die ID des Benutzers, der den Tagesabschluss durchgeführt hat.
 * *_userRealName_* -> Der reale Name des Benutzers, der den Tagesabschluss durchgeführt hat.
 * *_aggreageteTurnover_* -> Der Gesamtbetrag, der zum Zeitpunkt des Z-Berichts vorhanden war.
 * *_turnOverVATDutyShare_* -> Der verwendete Steuersatz und Mehrwertsteueranteil des Gesamtbetrags
 * *_turnOverVATNetShare_* -> Der verwendete Steuersatz und der Nettobetrag des Gesamtbetrags
 * *_methodOfPayments_* -> Die Beträge pro Zahlungsart.
 * *_methodOfPaymentsCount_* -> Zählung, wie oft mit welcher Zahlungsart gezahlt wurde.
 * *_returnItemsValue_* -> Der Gesamtwert der zurückgenommenen Artikel.
 * *_returnItemsCount_* -> Die Anzahl der zurückgenommenen Artikel.
 * *_rabateValue_* -> Der gesamte Rabattbetrag für diesen Zeitraum.
 * *_rabateCount_* -> Die Anzahl der gewährten Rabatte.
 * *_turnOverUser_* -> Der vom Benutzer eingetragene Betrag, welcher sich beim Tagesabschluss in der Kasse befand
 * *_currency_* -> Die Währung
 * *_firstReceipt_* -> Die Nummer des ersten Belegs, der im Tagesabschluss berücksichtigt wurde.
 * *_astReceipt_* -> Die Nummer des letzten Beleges, der im Tagesabschluss berücksichtigt wurde.
 * *_startCashBalance_* -> Der Barbestand, der sich zu Beginn des Tages in der Kasse befand.
 * *_endCashBalance_* -> Der Barbestand, der sich zum Ende des Tages in der Kasse befand.
 * *_grandTotal_* -> Der Gesamtbetrag, der zu diesem Zeitpunkt mit der Kasse eingenommen wurde.
 * *_currentCashBalance_* -> Der Barbestand, der sich zum Zeitpunkt des Tagesabschlusses in der Kasse befinden sollte.
 * *_actualCashBalance_* ->  Der Barbestand, der sich tatsächlich zum Zeitpunkt des Tagesabschlusses in der Kasse befand.
 * *_depositValue_* -> Der Gesamtbetrag, der als Einlage getätigt wurde.
 * *_depositCount_* -> Die Anzahl der Einlagen, die getätigt wurden.
 * *_withdrawlValue_* -> Der Gesamtbetrag, der aus der Kasse entnommen wurde.
 * *_withdrawlCount_* -> Die Anzahl der Entnahmen.
 * *_cancellationOrderValue_* -> Der Gesamtwert der stornierten Artikel.
 * *_cancelationOrderCount_* -> Die Gesamtanzahl der stornierten Artikel.

Folgende Mitarbeiter/-innen sind systemseitig und unternehmensseitig autorisiert und angewiesen, Tagesberichte zu erstellen:

* [_Name, Vorname, ggf. Personalnummer, Organisationseinheit, Funktion im Unternehmen_]
* [_Name, Vorname, ggf. Personalnummer, Organisationseinheit, Funktion im Unternehmen_]
* [_Name, Vorname, ggf. Personalnummer, Organisationseinheit, Funktion im Unternehmen_]

Tagesberichte werden zu folgenden Zeiten/im folgenden Intervall erstellt:

* [_Beschreibung des Ablaufs im Unternehmen einfügen_]

Tagesberichte werden [nur elektronisch/elektronisch erstellt und ausgedruckt].

* Mit ausgedruckten Tagesberichten wird wie folgt verfahren:

* [_Beschreibung des Ablaufs im Unternehmen einfügen_]

==== Kassensturzberichte

Kassenaufzeichnungen sind laut GoDB so zu führen, dass der Soll-Bestand jederzeit mit dem Ist-Bestand der Kasse abgeglichen werden kann. plentymarkets POS ist jederzeit kassensturzfähig. Es ist also jederzeit möglich, den Soll-Bestand laut Kassenjournal mit dem Ist-Bestand der Kasse zu vergleichen. Zu diesem Zweck werden die in der Kasse vorhandenen Geldscheine und Münzen physisch gezählt und ein Zählprotokoll erstellt. In plentymarkets POS kann entweder die Anzahl der einzelnen Münzen und Geldscheine oder das Ergebnis der Zählung als Gesamtbetrag eingeben werden. Kassensturzberichten wird keine Belegnummer zugewiesen.

Im Kassensturzbericht werden systembedingt die folgenden Informationen gespeichert:

* Zeitpunkt (Datum/Uhrzeit) des Kassensturzes
* Anwender, der den Kassensturz erstellt hat
* ID der Kasse
* Soll-Kassenbestand
* Stückelung und Menge (optional)
* Ist-Kassenbestand
* Differenz zwischen Soll- und Kassenbestand

Die Daten des Kassensturzberichts werden systemseitig in der Tabelle *plenty_pos_till_count* und dort in den folgenden Spalten gespeichert:

 * *_posBaseId_* ->  Die ID des POS-Systems, an dem der Kassensturz durchgeführt wurde
 * *_tillCountNumber_* -> Die Nummer des Kassensturzes
 * *_expectedCash_* -> Der erwartete Barbestand der Kasse
 * *_actualCash_* ->  Das vom Benutzer als Gesamtsumme eingegebene Ergebnis der Zählung.
 * *_userId_* ->  Die ID des Benutzers, der den Kassensturz durchgeführt wird
 * *_userRealName_* -> Der reale Name des Nutzers
 * *_currency_* -> Die Währung des Kassensturzes
 * *_money_* -> Die Ergebnisse der Münzzählung
 * *_date_* -> Das Datum und die Uhrzeit, zu dem der Kassensturz durchgeführt wurde
 * *_sum_* -> Die vom System errechnete Summe der vom Benutzer eingegebenen Anzahl der einzelnen Münzen und Geldscheine.
 * *_difference_* -> Die Differenz zwischen Ist- und Sollbestand

Folgende Mitarbeiter/-innen sind systemseitig und unternehmensseitig autorisiert und angewiesen, Kassenstürze durchzuführen:

* [_Name, Vorname, ggf. Personalnummer, Organisationseinheit, Funktion im Unternehmen_]
* [_Name, Vorname, ggf. Personalnummer, Organisationseinheit, Funktion im Unternehmen_]
* [_Name, Vorname, ggf. Personalnummer, Organisationseinheit, Funktion im Unternehmen_]
* [_Name, Vorname, ggf. Personalnummer, Organisationseinheit, Funktion im Unternehmen_]
* [_Name, Vorname, ggf. Personalnummer, Organisationseinheit, Funktion im Unternehmen_]

Kassenstürze werden zu folgenden Zeiten/in folgendem Interval durchgeführt:

* [_Beschreibung des Ablaufs im Unternehmen einfügen_]

Das Zählergebnis des Kassensturzes wird wie folgt erfasst:

* Nur Gesamtbetrag
* Stückelung und Menge der einzelnen Münzen/Geldscheine

Das Ergebnis des Kassensturzes wird automatisch an das ERP-System plentymarkets übertragen. Kassensturzbelege können im Menü *Aufträge » Dokumentenarchiv* aufgerufen werden. Dort werden sie als Dokumente des Typs *Kassensturz* gespeichert.


===== Ablauf bei Differenzen im Kassensturzergebnis

Wenn nach der Zählung des Barbestands der Ist-Kassenbestand vom Soll-Kassenbestand abweicht, sind softwareseitig in plentymarkets POS zwei Vorgehensweisen möglich:

* Die Differenz wird ausgeglichen. Bei negativem Ist-Kassenbestand wird also der Differenzbetrag in die Kasse eingezahlt und manuell eine Einlage gebucht. Bei positivem Ist-Kassenbestand wird der Differenzbetrag aus der Kasse entnommen und manuell eine Entnahme gebucht.
* Die Differenz wird gebucht, d.h., der Ist-Kassenbestand wird als neuer Soll-Kassenbestand übernommen. Im Hintergrund wird für diesen Vorgang entweder automatisch eine Einlage oder eine Entnahme mit dem Buchungstext “Differenz aus Kassensturz” gebucht. Dieser Vorgang wird im Handbuch des ERP-Systems plentymarkets beschrieben: https://knowledge.plentymarkets.com/omni-channel/pos/pos-kassenbenutzer#_differenz_buchen[https://knowledge.plentymarkets.com/omni-channel/pos/pos-kassenbenutzer#_differenz_buchen]

Mitarbeiter/-innen sind angewiesen, bei Kassensturzdifferenzen wie folgt zu handeln:

* [_Beschreibung des Ablaufs im Unternehmen einfügen_]

=== Maschinelle Auswertbarkeit der POS-Geschäftsvorfälle (IDEA-Export)

§ 147 Absatz 2 Nummer 2 AO der GoBD sieht vor, dass im Rahmen einer Außenprüfung alle zur Auswertung der aufzeichnungs- und aufbewahrungspflichtigen Daten  notwendigen Strukturinformationen in maschinell auswertbarer Form bereitzustellen sind. Um diesen Anforderungen gerecht zu werden, können alle plentymarkets POS Geschäftsvorfälle über das Menü *Aufträge » POS » IDEA-Export* des ERP-Systems plentymarkets in elektronisch auswertbarer Form exportiert werden. Der Export erfolgt pro Kalenderjahr ohne weitere Filterungen und enthält alle Geschäftsvorfälle aus allen plentymarkets POS Kassen des plentymarkets Systems. Benutzer können beim Export also nur das Kalenderjahr, jedoch nicht den Umfang der exportierten Daten beeinflussen. Der Datenexport erfolgt im GDPdU-konformen IDEA-Format und wurde durch die Audicon GmbH zertifiziert.

Die Daten des IDEA-Exports sind systemseitig in der Tabelle *pleny_pos_idea_export* in den folgenden Spalten gespeichert:

* *_token_* -> Das Token des Exports
* *_state_* -> Der Status des Exports (z.B. in Arbeit oder Fertig)
* *_progress_* -> Der aktuelle Fortschritt des Exports
* *_currentModule_* -> Das Modul, das z.Z. bearbeitet wird
* *_filename_* -> Der Dateiname der exportieren Datei
* *_modules_* -> Die Module, die in dem Export bearbeitet werden
* *_options_* -> Die Optionen, die für den Export gewählt wurden (z.B. das zu exportierende Jahr)
* *_createdAt_* -> Zeitpunkt (Datum und Uhrzeit), zu dem der Export gestartet wurde
* *_updatedAt_* -> Zeitpunkt (Datum und Uhrzeit), zu dem neue Daten zum Export hinzugefügt wurden

Der IDEA-Export besteht aus den folgenden Dateien:

* addresses.csv
* gdpdu-[TT-MM-JJJJ].dtd
* index.xml
* journal.csv
* locations.csv
* orderitems.csv
* orders.csv
* pos.csv
* taxrates.csv
* tillcount.csv
* user.csv
* variations.csv
* zreport.csv
* zreportpayments.csv

Nach Abschluss des Exports stehen die Dateien im Menü *Aufträge » POS » IDEA-Export* des ERP-Systems plentymarkets zum Download zur Verfügung.

Mitarbeiter/-innen sind angewiesen, bei IDEA-Exporten wie folgt zu handlen:

* [_Erstellungsintervall_]
* [_Für die Erstellung zuständige Person/-en_]
* [_Speicherort für heruntergeladene IDEA-Exporte_]
* [_Sonstiges_]

Das Handbuch der ERP-Lösung plentymarkets stellt eine detaillierte Anleitung zur Erstellung des IDEA-Exports bereit: https://knowledge.plentymarkets.com/omni-channel/pos/pos-einrichten#500[https://knowledge.plentymarkets.com/omni-channel/pos/pos-einrichten#500]

=== Verfahren bei Ausfall von plentymarkets POS

Kommt es zu einem Ausfall der Internetverbindung, ist eine Verbindung zum ERP-System plentymarkets nicht möglich. Artikel können nicht gesucht und keine neuen Aufträge erstellt werden. Bereits begonnene Verkäufe können jedoch abgeschlossen werden. Die aus diesen Verkäufen resultierenden Aufträge werden im Speicher des mobilen Geräts gespeichert und an das ERP-System plentymarkets gesendet, sobald die Verbindung wiederhergestellt wird.

Bei einem Ausfall des Kassensystems plentymarkets POS sind Mitarbeiter/-innen angewiesen, wie folgt zu handeln:

* [_Beschreibung des Ablaufs im Unternehmen einfügen_]


== Organisationsunterlagen

=== Herstellerseitige Dokumentation

Die Dokumentation des ERP-Systems plentymarkets ist online verfügbar. Dort ist der aktuelle Stand der Software dokumentiert. Ein Download der Dokumentation ist zurzeit nicht möglich. Auf Anfrage stellt die plentymarkets GmbH prüfenden Finanzbehörden ältere Versionen der Dokumentation zur Verfügung.

Die Dokumentation von plentymarkets POS ist über die folgenden URLs erreichbar:

* Bedienungsanleitung plentymarkets POS +
https://knowledge.plentymarkets.com/omni-channel/pos/pos-kassenbenutzer[https://knowledge.plentymarkets.com/omni-channel/pos/pos-kassenbenutzer]
* Programmieranleitung plentymarkets POS +
https://knowledge.plentymarkets.com/omni-channel/pos/pos-einrichten[https://knowledge.plentymarkets.com/omni-channel/pos/pos-einrichten]

=== Grundprogrammierung

Die Grundprogrammierung der Kasse erfolgt im ERP-System plentymarkets. Für die Grundprogrammierung sind die folgenden Personen zuständig:

* * [_Name, Vorname, ggf. Personalnummer, Organisationseinheit, Funktion im Unternehmen_]
* * [_Name, Vorname, ggf. Personalnummer, Organisationseinheit, Funktion im Unternehmen_]

Die folgenden Personen sind autorisiert, Umprogrammierungen der Kasse vorzunehmen:

* * [_Name, Vorname, ggf. Personalnummer, Organisationseinheit, Funktion im Unternehmen_]
* * [_Name, Vorname, ggf. Personalnummer, Organisationseinheit, Funktion im Unternehmen_]

[_Arbeitsanweisung für die Grundprogrammierung/Umprogrammierung. Wie werden Änderungen protokolliert?_]

==== Grundeinstellungen

Die Grundeinstellungen einer Kasse werden im Menü *Einstellungen » Mandant (Shop) » Mandant öffnen » POS » Kasse öffnen » Tab: Grundeinstellungen *vorgenommen. Die Einstellungen erfolgen pro Kasse.

Die folgenden Grundeinstellungen wurden vorgenommen [_1 Tabelle pro Kasse erstellen_]:

|===
|Option|Einstellung|Datum|Erläuterung

|ID|||
|Geräte-ID|||
|Name|||
|Herkunft|103.___||
|Standardkunde|||
|Marktplatz-Verfügbarkeit berücksichtigen|ja/nein||
|Nur aktive Varianten berücksichtigen|ja/nein||
|Standort|||
|Vertriebslager|||
|Reparaturlager|||
|===


==== Belegeinstellungen


Die Belegeinstellungen einer Kasse werden im Menü *Einstellungen » Mandant (Shop) » Mandant öffnen » POS » Kasse öffnen » Tab: Beleg *vorgenommen. Die Einstellungen erfolgen pro Kasse.

Die folgenden Belegeinstellungen wurden vorgenommen [_1 Tabelle pro Kasse erstellen_]:

|===
|Option|Einstellung|Datum|Erläuterung

|Identische Auftragspositionen|||
|Bild|||
|Kopfzeile|||
|Fußzeile|||
|===

Die Belegeinstellungen werden pro Kasse systemseitig in der Tabelle *plenty_pos_receipt_configuration* und dort in den folgenden Spalten gespeichert:

 * *_posBaseId_* -> Die ID der Kasse, der eine Belegkonfiguration zugewiesen werden soll.
 * *_imageName_* -> Der Name der Bilddatei
 * *_imagePath_* -> Der Pfad zum Bild
 * *_headerText_* -> Der Text, der am Kopf des Beleges stehen soll.
 * *_headerActive_* -> Ob der Kopftext auf dem Beleg ausgegeben werden soll (ja/nein).
 * *_footerText_* -> Der Text, der am Ende des Beleges stehen soll.
 * *_footerActive_* -> Ob der Fußtext auf dem Beleg ausgegeben werden soll (ja/nein).
 * *_barcodeActive_* -> Soll ein Barcode auf dem Beleg erscheinen (ja/nein)?
 * *_barcodeType_* -> Bestimmt, welche Art von Barcode genutzt wird.
 * *_barcodeHRI_* -> Die menschenlesbare Version des Barcodes.
 * *_barcodeWidth_* -> Die Breite des Barcodes.
 * *_barcodeHeight_* -> Die Höhe des Barcodes.
 * *_barcodeFont_* -> Das Aussehen des Barcodes.
 * *_bonType_* -> Definition, ob auf dem Bon alle Artikel einzeln oder zusammengefasst dargestellt werden sollen.


==== Aktivierte Zahlungsarten


Die folgenden Zahlungsarten sind für die Kasse aktiviert:

|===
|Zahlungsart|plentymarkets Zahlungsart|Datum der Aktivierung|Anmerkungen

|Barzahlungen|4 » Bar bei Übergabe||
|Kartenzahlungen über externe EC-Kartenterminals|11 » Barverkauf/EC-Karte||
|Gutscheinzahlungen|1700 » Coupon||
|===

==== Aktivierte Verkaufspreise


Die folgenden Verkaufspreise sind für die Kasse aktiviert:

|===
|Verkaufspreis|plentymarkets Zahlungsart|Datum der Aktivierung|Anmerkungen

||||
||||
||||
|===


* Informationen zur Grundprogrammierung bzw. spezifische Einstellungen (Customising)
* Protokolle über jede Veränderung der Kassenprogrammierung (z.B. Stammdaten)
* Protokolle über die Einrichtung von Verkäufer- oder Trainingsspeichern
* Aufzeichnung der Programmabrufe nach jeder Programmänderung (u.a. der Artikelpreise)

== [_Weitere Bestandteile einer Verfahrensdokumentation_]

=== [_Beschreibung des internen Kontrollsystems_]

=== [_Arbeitsanweisungen_]


=== [_Unternehmensspezifische Informationen_]

- Wo werden die aufbewahrungspflichtigen Kassenbelege (Z-Bons, Stornobelege, Registrierkassen streifen usw.) abgelegt bzw. aufbewahrt?
- Bis zu welcher Höhe werden Geldscheine angenommen (ausländische Sorten bzw. Falschgeldprüfung etc.)?
- Wie wird die Kasse übergeben?
- Wer führt die Belegbearbeitung und Belegprüfung durch?
- Wie wird die Belegbearbeitung und Belegprüfung durchgeführt?
- Wie wird der Kassenbestand (Bargeld) verbracht?
- Wie und durch wen erfolgt die Abstimmung zwischen Haupt- und Nebenkassen bzw. mit der Finanzbuchhaltung?


////
== Info-Links


http://www.karrer-viellieber.de/files/Blider/Dateien/MI_elektronische%20Kassensysteme%20ab%202017.pdf[http://www.karrer-viellieber.de/files/Blider/Dateien/MI_elektronische%20Kassensysteme%20ab%202017.pdf]

https://www.deubner-steuern.de/uploads/tx_diadeubner/LP_100408_MI_GoBD.pdf[https://www.deubner-steuern.de/uploads/tx_diadeubner/LP_100408_MI_GoBD.pdf]

http://www.bpw-online.de/steuertipps/verschaerfte-anforderungen-an-elektronische-kassen-und-andere-vorsysteme-zu-ihrer-buchhaltung.html[http://www.bpw-online.de/steuertipps/verschaerfte-anforderungen-an-elektronische-kassen-und-andere-vorsysteme-zu-ihrer-buchhaltung.html] +
Infos zu VD, mit Grafiken

http://www.lueders-warneboldt.de/aktuelles/steuerinformationen/anforderung-an-registrierkassen-ab-2017/[http://www.lueders-warneboldt.de/aktuelles/steuerinformationen/anforderung-an-registrierkassen-ab-2017/] +
Infos zu Anforderungen an Registrierkassen

http://steuerberatung-sachsen.de/wp-content/uploads/2017/01/Verfahrensdokumentation-Kassenf%C3%BChrung.pdf[http://steuerberatung-sachsen.de/wp-content/uploads/2017/01/Verfahrensdokumentation-Kassenf%C3%BChrung.pdf] +
Checkliste VD

https://www.css-group.de/products/kasse_60/vd_kasse60.pdf[https://www.css-group.de/products/kasse_60/vd_kasse60.pdf] +
Verfahrensdokumentation zu CSS Group® Kassensoftware 201

http://www.quorion.de/downloads/gobd/verfahrensdokumentation-gobd.pdf[http://www.quorion.de/downloads/gobd/verfahrensdokumentation-gobd.pdf] +
Verfahrensdoku quorion - checken

http://www.steuerkanzlei-feucht.de/aktuelles/Mandanten-Informationsbrief-2015-12-01.pdf[http://www.steuerkanzlei-feucht.de/aktuelles/Mandanten-Informationsbrief-2015-12-01.pdf]


Checklisten +
http://steuerberatung-sachsen.de/wp-content/uploads/2017/01/Verfahrensdokumentation-Kassenf%C3%BChrung.pdf[http://steuerberatung-sachsen.de/wp-content/uploads/2017/01/Verfahrensdokumentation-Kassenf%C3%BChrung.pdf]

http://www.stb-stuttgart.de/content/images/NWB%20Merkblaetter/Checkliste%20Kassenf%C3%BChrung.pdf[http://www.stb-stuttgart.de/content/images/NWB%20Merkblaetter/Checkliste%20Kassenf%C3%BChrung.pdf]

http://www.sharp.de/sharp/media/de/images/de/04-17_SHARP_FAQ_GoBD_4.3.pdf[http://www.sharp.de/sharp/media/de/images/de/04-17_SHARP_FAQ_GoBD_4.3.pdf]
////
