=== Tarifstruktur

Aktuell ist plentymarkets in den 3 Tarifgruppen *Starter*, *PRO* und *PLUS* verfügbar. Diese Tarifgruppen werden im Folgenden detailliert aufgeschlüsselt.

In allen Tarifen stehen integrale und optionale Module zur Verfügung. Integrale Module sind Module, die von Anfang an im Funktionsumfang des jeweiligen Systems enthalten sind. Optionale Module können zusätzlich gewählt werden und gehören dann ebenfalls zum Funktionsumfang des Systems. Die integralen und optionalen Module unterscheiden sich je nach Tarif.

==== Tarifgruppe *STARTER*

Die Tarifgruppe *STARTER* besteht aus dem Tarif *BASIC*. In diesem Tarif sind die folgenden Module integral:

  * Multi-Channel
  * Online-Shop
  * Auftragsabwicklung
  * Warenwirtschaft
  * CRM
  * Payment
  * Fulfillment
  * Prozesse
  * Cloud-Hosting

Zusätzlich ist die Nutzung folgender Leistungen inklusive:

  * ShopBuilder
  * ShopBooster
  * Facettensuche
  * Rest-API
  * Forensupport
  * Software-Updates

Das Modul *POS* ist immer optional und muss separat hinzugebucht werden. +
Benutzerlizenzen, Vertriebslager, Mandanten und Kassen können bis zu den in Tabelle 1 aufgeführten maximalen Anzahlen hinzugebucht werden.

.Optionen in der Tarifgruppe *STARTER*
[cols="1,3,3,3"]
|====
|Option |BASIC

|Laufzeit
|1 Monat

|Benutzerlizenzen
|5 inklusive / maximal 5

|Vertriebslager
|3 inklusive / maximal 3

|Mandanten
|1 inklusive / maximal 3

|POS / Kassen
|bis zu 5 Kassen zubuchbar

|====

==== Tarifgruppe *PRO*

Die Tarifgruppe *PRO* besteht aus den Tarifen *CLASSIC* und *FLEX*. Die folgenden Module sind in beiden Tarifen der Gruppe *PRO* integral:

  * Multi-Channel
  * Online-Shop
  * Auftragsabwicklung
  * Warenwirtschaft
  * CRM
  * Payment
  * Fulfillment
  * Prozesse
  * Cloud-Hosting

Zusätzlich ist die Nutzung folgender Leistungen inklusive:

  * ShopBuilder
  * ShopBooster
  * Facettensuche
  * Rest-API
  * Forensupport
  * Software-Updates

Das Modul *POS* ist immer optional und muss bei beiden Tarifen separat hinzugebucht werden. +
Benutzerlizenzen, Vertriebslager, Mandanten und Kassen können bis zu den in Tabelle 2 aufgeführten maximalen Anzahlen hinzugebucht werden.

.Optionen in der Tarifgruppe *PRO*
[cols="1,3,3"]
|====
|Option |CLASSIC |FLEX

|Laufzeit
|3-12 Monate
|6 Monate

|Benutzerlizenzen
|20 inklusive / maximal 50
|30 inklusive / maximal 100

|Vertriebslager
|3 inklusive / maximal 25
|5 inklusive / maximal 40

|Mandanten
|1 inklusive / maximal 15
|1 inklusive / maximal 30

|POS / Kassen
|bis zu 25 Kassen zubuchbar
|bis zu 99 Kassen zubuchbar

|====

In der Tarifgruppe Classic können zusätzlich Auftragspakete gebucht werden. Folgende Auftragspakete stehen zu Verfügung:

  * 500 Aufträge
  * 5.000 Aufträge
  * 10.000 Aufträge
  * 50.000 Aufträge

Auftragspakete können für einen Zeitraum von 3 Monaten, 6 Monaten oder 12 Monaten gebucht und beliebig kombiniert werden.

==== Tarifgruppe *PLUS*

Die Tarifgruppe *PLUS* besteht aus den Tarifen *PLUS* und *B2B PLUS*. Die folgenden Module sind in beiden Tarifen der Gruppe *PLUS* integral:

  * Multi-Channel
  * Online-Shop
  * Auftragsabwicklung
  * Warenwirtschaft
  * CRM
  * Payment
  * Fulfillment
  * Prozesse
  * Cloud-Hosting

Zusätzlich ist die Nutzung folgender Leistungen inklusive:

  * ShopBuilder
  * ShopBooster
  * Facettensuche
  * Rest-API
  * Forensupport
  * Software-Updates

Das Modul *POS* ist immer optional und muss bei beiden Tarifen separat hinzugebucht werden. +
Benutzerlizenzen, Vertriebslager, Mandanten und Kassen können bis zu den in Tabelle 3 aufgeführten maximalen Anzahlen hinzugebucht werden.

.Optionen in der Tarifgruppe *PLUS*
[cols="1,3,3"]
|====
|Option |PLUS |B2B PLUS

|Benutzerlizenzen
|60 inklusive / maximal 200
|1 inklusive / maximal 200

|Vertriebslager
|10 inklusive / maximal 50
|10 inklusive / maximal 50

|Mandanten
|3 inklusive / maximal 50
|3 inklusive / maximal 50

|POS / Kassen
|bis zu 99 Kassen zubuchbar
|bis zu 99 Kassen zubuchbar

|====

==== Tarif *plentymarkets PARTNER*

Der Tarif *plentymarkets PARTNER* kann nur von zertifizierten plentymarkets Partnern gebucht werden. Die folgenden Module sind im Tarif integral:

  * Multi-Channel
  * Online-Shop
  * Auftragsabwicklung
  * Warenwirtschaft
  * CRM
  * Payment
  * Fulfillment
  * Prozesse
  * Cloud-Hosting

Zusätzlich ist die Nutzung folgender Leistungen inklusive:

    * ShopBuilder
    * ShopBooster
    * Facettensuche
    * Rest-API
    * Forensupport
    * Software-Updates

Benutzerlizenzen, Vertriebslager, Mandanten und Kassen können bis zu den in Tabelle 4 aufgeführten maximalen Anzahlen hinzugebucht werden.

.Optionen im Tarif *plentymarkets PARTNER*
[cols="1,3"]
|====
|Option |plentymarkets *PARTNER*

|Benutzerlizenzen
|5 inklusive / maximal 10

|Vertriebslager
|3 inklusive / maximal 3

|Mandanten
|1 inklusive / maximal 10

|POS / Kassen
|2 inklusive / maximal 2

|====

Partner können außerdem Plugins und Dienstleistungen auf plentyMarketplace anbieten.

==== Hosting-Optionen

Jeder Anwender muss *eine* der von plentymarkets angebotenen Hosting-Optionen wählen. Die folgenden Hosting-Optionen in Form von Server-Standorten stehen hierbei zur Verfügung:

 * AWS Dublin
 * AWS Frankfurt

Die Speicherung und Sicherung von Daten findet ausschließlich am ausgewählten Server-Standort statt. Die Sicherung von Daten in Form von Backups findet ausdrücklich *nur* am gewählten Server-Standort und niemals an weiteren Standorten statt.

Weitere Informationen zu den einzelnen Hosting-Optionen werden im Kapitel <<Datasecurity, Speicherkonzept, Löschkonzept, Aufbau, Sicherheitsarchitektur AWS Cloud>> beschrieben.
