= Anhang: Formulierungsvorschlag zur Verfahrensdokumentation für plentysystems Anwender

Dieser Anhang liefert Formulierungsbeispiele für eine Verfahrensdokumentation beim Einsatz der Software plentysystems. Die Beispiele bedürfen in jedem Fall Anpassungen an die tatsächlichen Gegebenheiten des Unternehmens, das plentysystems einsetzt. Die hier angegebenen Beispielformulierungen sind nicht rechtlich geprüft. +
_Hinweis: Dieses Kapitel ist nicht Teil des Formulierungsvorschlag und sollte nicht in Ihre Verfahrensdokumentation übernommen werden._

== Edition und Hosting

Ich nutze die Software plentysystems in der Edition … In dieser Edition sind folgende Module … integral. Außerdem habe ich folgende optionale Module hinzugebucht: … +
Ich habe mich für das von plentysystems angebotene Hosting in … entschieden.

== Fachliche Beschreibung plentysystems

plentysystems ist eine modular aufgebaute und Plugin-fähige Software für den Handel mit Sachgütern, digitalen Gütern und immateriellen Gütern. +
plentysystems wird in unserem Unternehmen insbesondere zum Verkauf von … sowie zur zentralen Verwaltung von Produktinformationen und zur Abwicklung von Bestellungen genutzt. Hierbei kommen die genannten Module zum Einsatz. Die Vorteile beim Einsatz von plentysystems liegen für unser Unternehmen insbesondere darin, dass Artikelinformationen zentral in plentysystems erfasst und verwaltet werden und von hier aus an verschiedene Kanäle für den Verkauf übermittelt werden. Des Weiteren liegen Vorteile darin, dass egal über welchen Kanal ein Artikel verkauft wurde, nach dem Verkauf eine Übermittlung der Auftrags- und Kundendaten an das plentysystems System des Anwenders erfolgt, sodass die anschließende Abwicklung wieder zentral in unserem plentysystems System erfolgt. Ein weiterer Vorteil liegt in der Möglichkeit diese Abwicklung bis zu einem hohen Grad zu automatisieren.

== Fachliche und technische Beschreibung Benutzer und Benutzerrechte

Die Benutzer dienen der Zuordnung von Zugriffsrechten sowie der Nachvollziehbarkeit von Änderungen im System.

Die folgende Tabelle zeigt, welche Benutzer im System eingerichtet sind oder waren, welchem Benutzerzugang sie angehören und über welche Rechte sie verfügen.


|===
|Benutzername|Benutzerzugang|Benutzerrechte|Gültigkeit

|Xxx Xxx|Admin| * alle|01.01.2019 - aktuell
|Xxx Xxx|Backend| * alle Lager|31.12.2016 - 01.09.2019
||||
||||
|===
