name: Create procedure document PDF

on:
  push:
    branches:
      - master
      
jobs:
  update-procedure-document:
    name: Update procedure document
    runs-on: macos-latest
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v2
        
      - name: Setup Ruby, JRuby and TruffleRuby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.5
      
      - name: Setup OpenJDK
        uses: actions/setup-java@v1.4.3
        with:
          java-version: '11' # The OpenJDK version to make available on the path
          architecture: 'x64' # defaults to 'x64'
            
      - name: Install Asciidoctor
        run: gem install asciidoctor

      - name: Install Asciidoctor-PDF
        run: gem install asciidoctor-pdf

      - name: Install Asciidoctor-Diagram
        run: gem install asciidoctor-diagram

      - name: Install text hyphenation
        run: gem install text-hyphen

      - name: Run main.rb
        run: ruby ./main.rb

      - name: Upload PDF Artifact
        uses: actions/upload-artifact@v2
        with:
          name: Verfahrensdokumentation
          path: ./Index.pdf

