name: Create procedure document PDF

on:
  push:
    branches:
      - master
      - kevin/github_action

jobs:
  update-procedure-document:
    name: Update procedure document
    runs-on: macos-latest
    steps:
      - name: Setup Ruby, JRuby and TruffleRuby
        uses: ruby/setup-ruby@v1.38.0
        with:
          ruby-version: 2.3.7
      
      - name: Setup OpenJDK
        uses: joschi/setup-jdk@v2
        with:
          java-version: '11' # The OpenJDK version to make available on the path
          architecture: 'x64' # defaults to 'x64'
            
      - name: Checkout repository code
        uses: actions/checkout@v2
        
      - name: Install Asciidoctor
        run: gem install asciidoctor

      - name: Install Asciidoctor-PDF
        run: gem install asciidoctor-pdf

      - name: Install Asciidoctor-Diagram
        run: gem install asciidoctor-diagram

      - name: Install text hyphenation
        run: gem install text-hyphen

      - name: Run main.rb
        run: ruby ./main.rb

      - name: Commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add ./Index.pdf
          git commit -m "Update PDF" ./Index.pdf
          git push

